### ISSUE TITLE
Linking diagrams for models with duplicate variables

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1004]
This has to do with implementing gpkit/gpkit/interactive/linking_diagram.py in models with hierarchy, with duplicate variable names. 

I have tried to make a linking diagram for hoburg/d8/CFP_Fuselage_Performance_int_HT.py, in commit cb63fa5, when I realized that the previous linking diagram infrastructure doesn't like duplicate variable names. 

As an example, the aircraft model in CFP has:
```python
ac = Aircraft()
subsystems = [Fuselage(), Engine(), VerticalTail(), HorizontalTail(), Wing()]
```
I implement linking_diagram in the file make_figure.py, and it returns the following error
```python
Traceback (most recent call last):
  File "C:\Users\Berk\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2666, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "C:\Users\Berk\Anaconda2\lib\site-packages\IPython\utils\py3compat.py", line 276, in execfile
    exec(compiler(scripttext, filename, 'exec'), glob, loc)
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\D8\d8\make_figure.py", line 111, in <module>
    make_figure()
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\D8\d8\make_figure.py", line 55, in make_figure
    zidane[tuple(keychain[key])] += [key]
KeyError: ('VerticalTail', 'Wing', 'Wing')
```
because some variable names appear both in Wing and VerticalTail, although there are two distinct variables with the same name (example 'I_{cap}', which is a wing spar moment of inertia). 

As a workaround, I was going to suggest scrubbing through the constraints within the hyperclasses of Aircraft and AircraftP, instead of variables within the model, to make the diagram. This way you avoid the issues with duplicate names (although you will oddly have two variables with the same name that are not related at all in the diagram). Or is there another way to fix the issue? Let me know what you think.

**Comment by bqpd** [comment]
That sounds good! If you have multiple variables with the same name in the diagram, you should probably print their full name (that is, including model).

**Comment by bqpd** [comment]
And/or, the models in a variable's name tell you where it came from, which would be useful information to visualize...

**Comment by 1ozturkbe** [comment]
Yes that would be great! How does one do that? :P

**Comment by bqpd** [comment]
There is a better way!

`varkey.models` will have the list of a varkey's models, with the lowest level on the end, while each model will have a name/num attribute; so if you're iterating over models, you already see what varkeys they have, and can assign each variable to the model in your list that closest to the right / the point of creation in `varkey.models`

**Comment by 1ozturkbe** [comment]
Sweet! Sounds like it is going to be almost trivial! Will try to implement later today.

**Comment by 1ozturkbe** [comment]
It doesn't exactly work. It turns out that each variable shows up as having the models as such:
```python
['Aircraft','Submodel']
```
because each variable shows up once when it is defined in a submodel, and when it pops up within the Aircraft hyperclass. 
I do think it's generally a better idea to just scrub the high-level constraints.

**Comment by bqpd** [comment]
This doesn't change the usefulness of the information contained within each variable, but if you're using `setup`, variables are created with all the models they'll ever have; they're no longer "added" add the end of model creation.

**Comment by bqpd** [comment]
I think I'm confused about what information you're looking for; doesn't `['Aircraft','Submodel']` communicate that the variable was created in `Submodel`?

**Comment by 1ozturkbe** [comment]
No. It's because the Aircraft hyperclass inherits all of the constraints from the submodels, so whether or not that variable shows up in a constraint in Aircraft, it will still show up as a variable in Aircraft.

**Comment by bqpd** [comment]
Ohhhh. Hmm, `m.unused_variables` might have what you want, then?

**Comment by 1ozturkbe** [comment]
What I am really interested in are the variables that have constraints in the Aircraft hyperclass that link different subsystems. And I'm not sure unused_variables does that.

**Comment by bqpd** [comment]
Ah. Yeah, I think you'll have to parse the constraints list for that.

**Comment by 1ozturkbe** [comment]
Hey @bqpd , I have been struggling with this for hours, and haven't made any progress on making a dictionary of with the linking variable names as keys, and the models linked as the entries. I was wondering if you could assist. Woody would like to have a linking diagram for D8 for his presentation to the Dean of Engineering on the 20th. It is a great opportunity to show off what we are doing, so help would be huge! I just pushed the latest commit (e2ddd06) of CFP_Fuselage_Performance_int_HT in hoburg/d8. Lmk if we can figure this out in time.

**Comment by bqpd** [comment]
superseded by #1088
