### ISSUE TITLE
An elegant way to remove constraints that contain certain variables from a model on the fly

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1005]
, has anyone come up with.

Bonus points for specific combinations of variables.

**Comment by bqpd** [comment]
Gross hack but simple: You could iterate over each constraint and overload its `as_posyslt1(self, substitutions)` to return `[]` if it meets certain criteria (if a PosyIneq) and its `as_gpconstr(self, x0)` to return itself:

```python
for constraint in M.flat(constraintsets=False):
    if "x" in constraint.varkeys:
        constraint.as_gpconstr = lambda (self, x0): return self
        constraint.as_posyslt1 = lambda(self, substitutions): return []

```

**Comment by pgkirsch** [comment]
Nice. Maybe I just need to read up on lambda functions, but what do x0 and substitutions add here?

**Comment by bqpd** [comment]
Nothing! We just need to make them both two-argument functions, so I figured I'd specify what the args where.

**Comment by bqpd** [comment]
Oops, syntax error: there should be no parens around args.

**Comment by bqpd** [comment]
This could be done with a list comprehension, I think?
