### ISSUE TITLE
should variables not in any constraints appear in the model?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1006]
I noticed that if you have a variable in a setup method that is also not in any constraints it will appear in the actual GP solved by `mosek`/`cvxopt`. I feel like this shouldn't happen?

**Comment by bqpd** [comment]
This is intentional! It allows for the creation of simple `template` models, like the atmosphere model in http://gpkit.readthedocs.io/en/latest/modelbuilding.html#multipoint-analysis-modeling

**Comment by bqpd** [comment]
(that said, it can cause some confusing bugs, so maybe we should have a warning of some kind?)

**Comment by mayork** [comment]
yeah a warning might be good. in very large models it is not immediately obvious when this occurs.
