### ISSUE TITLE
SP solve issues: var == value solves, var.sub(value) doesn't.

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1009]
This is an issue in hoburg/d8/CFP_Fuselage_Performance_int_HT.py, commit  9bfa0b9. 

I have a variable called thetadb, which describes the double-bubble fuselage joint angle. Currently I'm substituting the value 0.366 (the value from the half-scale). 

The odd part is that the SP solves when I put this value in as an equality ``` thetadb == 0.366```  in my constraints. But if I do the substitutions:
```python
thetadb = Variable('\\theta_{db}', 0.366,  '-', 'DB fuselage joining angle')
```
or
```python
'\\theta_{db}' : 0.366
```
in the substitutions dict, the solve returns UNKNOWN. A bit odd. I checked the substitutions and they seem to be fine. Any idea what could be happening?

**Comment by mayork** [comment]
Any chance the variable is defined twice? I had that happen to me last week and the behavior was very similar.

**Comment by 1ozturkbe** [comment]
I wish... I wanted to to a sweep with the fuselage joint angle when I realized that this was happening. The variable only exists within fuselage, and there is only one equation outside of fuselage that involves this variable. 
This also used to not be an issue; I remember it working properly doing sweeps some time ago. Might be an undesired side effect of a recent gpkit commit.

**Comment by bqpd** [comment]
Got it. This isn't a recent gpkit thing, it's because some constraints became posynomial inequalities after substitution, and we didn't properly catch that. Now (in https://github.com/hoburg/gpkit/pull/1020) it solves the same when thetadb is a number as when it's a variable, and in fewer GP solves than it took with the equality!
