### ISSUE TITLE
Replacing Uninformative Variables from GPfit

### ISSUE THREAD

**Issue by cjk12** [hoburg/gpkit#1028]
I've been working with GPfit recently, and it returns constraints that look like:
```python
gpkit.PosynomialInequality(w_fit**3.5 >= 1.38e+41*u_fit_(0,)**-0.15*u_fit_(1,)**-9.5 + 1.62e-07*u_fit_(0,)**0.0064*u_fit_(1,)**-0.16)
```
It's possible that this exists, but it would be really nice if there were a property of a constraint, such as `cosntraint.replace()` that could allow me to do something like:
```python
from gpkit import Variable

x = Variable("x", "-")
y = Variable("y", "-")
z = Variable("z", "-")

const = x >= y

const.replace(x,z)
print const
```
and have it return:
```
z >= y
```
IE, the variable `x` has simply been replaced in the constraint by the variable `z`.  Something of this sort would be nice so I can replace `u_1` with `C_L`, `u_2` with `Re`, `w` with `C_D` etc...  And since GPfit returns vector variables, that would be great too in addition to the scalar example I've got here.

**Comment by bqpd** [comment]
Does subinplace({"w": "x"}) work here?

**Comment by cjk12** [comment]
This has some strange behavior:

```python
import unittest
from numpy import log, exp, log10, vstack
from gpfit.fit import fit
from numpy.random import random_sample

Vdd = random_sample(1000,) + 1
Vth = 0.2*random_sample(1000,) + 0.2
P = Vdd**2 + 30*Vdd*exp(-(Vth-0.06*Vdd)/0.039)
u = vstack((Vdd,Vth))
x = log(u)
y = log(P)
K = 4

cstrt, rmsErr, a, b, c = fit(x,y,K,"ISMA")

from gpkit import Variable, Model
Re = Variable("Re", "-", "Reynold's number")
cstrt.subinplace({"w_fit":"Re"})
print cstrt
```

```
0.0128*Re_fit**-0.66*u_fit_(0,)**2.6*u_fit_(1,)**-2.6 + 0.308*Re_fit**-0.31*u_fit_(0,)**0.64*u_fit_(1,)**-0.82 + 0.891*Re_fit**-0.25*u_fit_(0,)**0.5*u_fit_(1,)**-0.093 + 1.01*Re_fit**-0.076*u_fit_(0,)**0.15*u_fit_(1,)**0.012 <= 1
```

**Comment by bqpd** [comment]
Strings values will just rename: try cstrt.subinplace({"w_fit": Re}), if
that doesn't work we should fix that, but for now cstrt.subinplace({"w_fit":
Re.key}) should work.

**Comment by cjk12** [comment]
This appears to work:

```python
import unittest
from numpy import log, exp, log10, vstack
from gpfit.fit import fit
from numpy.random import random_sample

Vdd = random_sample(1000,) + 1
Vth = 0.2*random_sample(1000,) + 0.2
P = Vdd**2 + 30*Vdd*exp(-(Vth-0.06*Vdd)/0.039)
u = vstack((Vdd,Vth))
x = log(u)
y = log(P)
K = 4

cstrt, rmsErr, a, b, c = fit(x,y,K,"ISMA")

from gpkit import Variable, Model
Re = Variable("Re", "-", "Reynold's number")
cstrt.subinplace({"w_fit":Re})
cstrt
```

Thanks @bqpd

**Comment by cjk12** [comment]
Actually, is this any different for vector variables?  For example, if I have `u` with two elements, how do I replace the first one with variable `x` and the second element with variable `y`?

**Comment by bqpd** [comment]
`.sub({"u": [x, y]})` seems to work just fine.

Note that if you have an older version of gpfit, `u` is not a vector variable.

**Comment by cjk12** [comment]
Awesome, thanks.  Just saved me a lot of time.

**Comment by bqpd** [comment]
Great!

(note that new gpfit only returns cstrt, rmsErr from `fit`)

**Comment by cjk12** [comment]
Yea I hacked that.  Thanks for the heads up.
