### ISSUE TITLE
document slicing vectorized models and flat commands, improved constraint storage in sliced model

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1038]
I forget the technical term but i would like to be able to split vectorized models the way you can "split" lists. By splitting I mean how running the following

```python
l = [1, 2, 3, 4]
print l[:2]
```
outputs [1, 2].

So if I have a vectorized model, say m, I'd like m[:2] to return the first two elements of all constraints. I don't think currently happens, see the example below where 

```python
from stand_alone_simple_profile import FlightState

In [11]: with Vectorize(4):
    ...:     state = FlightState()
    ...:     

In [12]: state
Out[12]: 
gpkit.FlightState(
  # minimize
        1
  # subject to
        V_FlightState = V_FlightState
        a_FlightState = [R_FlightState_(0,)**0.5*T_{atm}_FlightState, Atmosphere_(0,)**0.5*\gamma_FlightState_(0,)**0.5, R_FlightState_(1,)**0.5*T_{atm}_FlightState, Atmosphere_(1,)**0.5*\gamma_FlightState_(1,)**0.5, R_FlightState_(2,)**0.5*T_{atm}_FlightState, Atmosphere_(2,)**0.5*\gamma_FlightState_(2,)**0.5, R_FlightState_(3,)**0.5*T_{atm}_FlightState, Atmosphere_(3,)**0.5*\gamma_FlightState_(3,)**0.5]
        V_FlightState = [M_FlightState_(0,)*a_FlightState_(0,), M_FlightState_(1,)*a_FlightState_(1,), M_FlightState_(2,)*a_FlightState_(2,), M_FlightState_(3,)*a_FlightState_(3,)]
        ['FlightState']_[0]
        ['FlightState']_[0])

In [13]: state[0]
Out[13]: 
gpkit.ConstraintSet(
        V_FlightState = V_FlightState
        a_FlightState = [R_FlightState_(0,)**0.5*T_{atm}_FlightState, Atmosphere_(0,)**0.5*\gamma_FlightState_(0,)**0.5, R_FlightState_(1,)**0.5*T_{atm}_FlightState, Atmosphere_(1,)**0.5*\gamma_FlightState_(1,)**0.5, R_FlightState_(2,)**0.5*T_{atm}_FlightState, Atmosphere_(2,)**0.5*\gamma_FlightState_(2,)**0.5, R_FlightState_(3,)**0.5*T_{atm}_FlightState, Atmosphere_(3,)**0.5*\gamma_FlightState_(3,)**0.5]
        V_FlightState = [M_FlightState_(0,)*a_FlightState_(0,), M_FlightState_(1,)*a_FlightState_(1,), M_FlightState_(2,)*a_FlightState_(2,), M_FlightState_(3,)*a_FlightState_(3,)])

In [14]: state['a']
Out[14]: gpkit.NomialArray([a_FlightState_(0,) [m/s], a_FlightState_(1,) [m/s], a_FlightState_(2,) [m/s], a_FlightState_(3,) [m/s]])
```

It also appears you can't do something like m[0] and return just the first index of all constraints. I'm guessing this has to do somehow with list inheritance. However, it would be very very helpful to have this functionality in the engine code. @bqpd any chance this is possible?

**Comment by mayork** [comment]
nevermind, i'm stupid. didn't realize these were all just nested lists.

However, it was suggested this and the flat commands could probably be documented better

**Comment by mayork** [comment]
it actually seems like slicing an entire model's constraints is still either non-intuitive or not possible even after accounting for the nested list effect...see https://github.com/hoburg/d8/issues/12.

**Comment by bqpd** [comment]
I think it's pretty intuitive for the list to contain the constraints you put into it :p

Even if it was turned into a 2d constraint matrix, what you want to access is `state[0][:,0]`, so you'd just be replacing `[v[0] for v in state[0]]` with that and saving 11 characters or so.

**Comment by bqpd** [comment]
@mayork, closing this for now because I think the list comprehension syntax is a good fit to your specific issue above, but please continue to open issues for this & similar syntax issues as they come up!
