### ISSUE TITLE
How to handle NEAR_OPTIMAL solution status

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1048]
As mentioned in #1047 I have a model (at commit 184467c058267d1fefa1 on the D8 repo) that returns

```
Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : NEAR_OPTIMAL
  Primal.  obj: 1.1998763649e+01    Viol.  con: 3e-02    var: 0e+00  
  Dual.    obj: 1.2009877944e+01    Viol.  con: 0e+00    var: 7e-02  
* End solution on dual form. *
```

The NEAR_OPTIMAL occurs during the first GP solve. We then do a feasibility solve, which I'm not sure makes sense. More generally, Woody and I weren't sure how to handle and solve that returns NEAR_OPTIMAL.

**Comment by bqpd** [comment]
Great issue! We're seeing this commonly in the ECOS solver I've been working at incorporating as well.

**Comment by mayork** [comment]
any updates on this? I think we would like to try continuing the solve as if near optimal is optimal....

**Comment by mayork** [comment]
i just wanted to keep this alive...I'm still seeing near optimal occasionally in the D8 so I think it would be interesting to change how we handle near optimal.

**Comment by bqpd** [comment]
What file is it that triggers this? I have some code that should work, but can't test it.

**Comment by mayork** [comment]
There were a few D8.py commits where it would occur about 1 in every 4 solves. I'll look for the in a bit, I know I committed the code but it was a while ago so it might take a minute to find it

**Comment by mayork** [comment]
wait nvm i listed the commit in the issue description...commit 184467c058267d1fefa1 on the D8 repo

**Comment by bqpd** [comment]
`D8.py` does not run for me at that commit because

```python
ValueError: the substitution {w_{fuse}: [ 6.  6.]} is invalidated by the subinplace {w_{fuse}: [w_{fuse}_Fuselage.1_(0,) w_{fuse}_Fuselage.1_(1,)]}, because [w_{fuse}_Fuselage.1_(0,) w_{fuse}_Fuselage.1_(1,)] does not have a `key` attribute
```

**Comment by mayork** [comment]
run D8.py at https://github.com/hoburg/d8/commit/937af35f9a6bdafa7921f008f09753e07c74c392

**Comment by mayork** [comment]
@bqpd this commit as well https://github.com/hoburg/d8/commit/ecdfe60f0487fd665d7861a44d333291c37e58d7

**Comment by mayork** [comment]
i think this is a major hold back on D8 currenlty

**Comment by bqpd** [comment]
Allowing near optimal solves to be treated as optimal solves does not let either of those models solve. I think this is more fundamental than expected.

**Comment by bqpd** [comment]
Wait, may have made a stupid mistake, checking.

**Comment by bqpd** [comment]
Yup, the actual solution status code returned by mosek is `NEAR_DUAL_FEAS`, not `NEAR_OPTIMAL`. C'est la vie.
