### ISSUE TITLE
Units error in substitutions 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1049]
This has been a recurrent problem, and I have been putting off an issue on it for a while. Now it is time. 

Look at CFP_Fuselage_Performance_int_HT.py in hoburg/d8, commit 8cac3d6. 
If you run the code, you will get the following error:
``` python
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\nomials\nomial_math.py", line 358, in mono_lower_bound
    return self.mono_approximation(x0)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\nomials\nomial_math.py", line 194, in mono_approximation
    m0 *= (x0[vk])**e
  File "C:\Users\Berk\Anaconda2\lib\site-packages\pint\quantity.py", line 851, in __pow__
    raise DimensionalityError(self._units, 'dimensionless')
DimensionalityError: Cannot convert from 'force_pound' to 'dimensionless'
```
This is because of the following substitution on line 984:
```python
'W_{engine}': 11000*units('lbf'), # Engine weight substitution
```
Extremely puzzling why this doesn't work, since I have put units in other substitutions and it has worked fine. Let me know if you have any ideas @bqpd.

**Comment by bqpd** [comment]
Seem like that substitution is in the exponent of the monomial approx. Will take a look!

**Comment by 1ozturkbe** [comment]
Any updates on this? Kind of seems like a trivial problem, but one that has relatively immediate importance. If we cannot make use of units in substitutions array, we cannot validate that we are substituting the right values without checking the variable definitions.

**Comment by whoburg** [comment]
let's make sure we add a unit test before closing this
