### ISSUE TITLE
Latest version of master returns Rank ValueError when it solved with 0.4.2.1

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1052]
Updated to latest version of master (I was previously at e5f95f4ea5fbf1c1711ec843cd6f5a3bffd44062) and most variants of my model solve fine, except for some, which return a ValueError.

<details>
  <summary>Error traceback</summary>
  <p>

```python
    ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/philippe.kirschen/Documents/Optimization/HOPS/HOPS.py in <module>()
    496                          tubematerial="concrete")
    497     try:
--> 498         sol = hl.solve()
    499     except RuntimeWarning:
    500         print "Default solver failed, trying LDL kkt solver..."

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     82         else:
     83             self.program, solvefn = genfunction(self, verbosity)
---> 84             result = solvefn(solver, verbosity, *args, **kwargs)
     85             solution.append(result)
     86         solution.program = self.program

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/geometric_program.pyc in solve(self, solver, verbosity, warn_on_check, *args, **kwargs)
    165             sys.stdout = self.solver_log   # CAPTURED
    166             solver_out = solverfn(c=self.cs, A=self.A, p_idxs=self.p_idxs,
--> 167                                   k=self.k, *args, **kwargs)
    168             self.solver_out = solver_out
    169         finally:

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/_cvxopt.pyc in cvxoptimize(c, A, k, *args, **kwargs)
     42     g = log(matrix(c))
     43     F = spmatrix(A.data, A.row, A.col, tc='d')
---> 44     solution = gpsolver(k, F, g, *args, **kwargs)
     45     return dict(status=solution['status'],
     46                 primal=solution['x'],

//anaconda/lib/python2.7/site-packages/cvxopt/cvxprog.pyc in gp(K, F, g, G, h, A, b, kktsolver, **kwargs)
   2159         else: return f, Df, H
   2160 
-> 2161     return cp(Fgp, G, h, dims, A, b, kktsolver = kktsolver, options = options)

//anaconda/lib/python2.7/site-packages/cvxopt/cvxprog.pyc in cp(F, G, h, dims, A, b, kktsolver, xnewcopy, xdot, xaxpy, xscal, ynewcopy, ydot, yaxpy, yscal, **kwargs)
   1964 
   1965     sol = cpl(c, F_e, G_e, h, dims, A_e, b, kktsolver_e, xnewcopy_e, 
-> 1966          xdot_e, xaxpy_e, xscal_e, options = options)
   1967 
   1968     sol['x'] = sol['x'][0]

//anaconda/lib/python2.7/site-packages/cvxopt/cvxprog.pyc in cpl(c, F, G, h, dims, A, b, kktsolver, xnewcopy, xdot, xaxpy, xscal, ynewcopy, ydot, yaxpy, yscal, **kwargs)
    780             singular_kkt_matrix = False
    781             if iters == 0:
--> 782                 raise ValueError("Rank(A) < p or "\
    783                     "Rank([H(x); A; Df(x); G]) < n")
    784 

ValueError: Rank(A) < p or Rank([H(x); A; Df(x); G]) < n
```

</p></details>

The only changes I made to the code were updating from `TightConstraintSet` to `Tight` and the units thing in #1051.

Any ideas what might have changed that would cause this? None of the commits jumped out as being obvious causes..

**Comment by pgkirsch** [comment]
Errr the models that solve fine give wildly different solutions........

**Comment by bqpd** [comment]
These are GP models returning different solutions? D:

**Comment by bqpd** [comment]
(also, sweet error traceback syntax above)

**Comment by bqpd** [comment]
Now that this is an academic exercise, want to try MOSEK? :p

**Comment by bqpd** [comment]
What does `.debug()`  say? My guess is that this is some kind of linking bug.

**Comment by bqpd** [comment]
How's it do at e1f76b1871992999c6d24d5325dc016fefccef50 and 3aa79dfb0b46eac376420f08624f1eba4455f1df ?

**Comment by pgkirsch** [comment]
Yes, GP's returning different solutions. Not all cases, but about half. In each case the objective is improving by about 0.7%. Some variables (a couple in each) are changing by absurd amounts (e.g `10^46`). Others (about 10 each) are changing by close to 100%, and the rest are changing by more reasonable amounts.

(Thanks)

I would prefer not to.

What in the `.debug()` output am I looking for? I see some success messages..

3aa79df gives the same answer as I was getting before updating.

**Comment by bqpd** [comment]
Realllllllly! Could you search for where between 3aa79df and HEAD it fails, the?

**Comment by bqpd** [comment]
My theory is that some variables have become or always were unbounded, which would also explain the huge changes. `.debug()` might say which variables those were...are there any differences in the output of `.debug()` between 3aa79df and HEAD?

**Comment by pgkirsch** [comment]
It's bb5f381f0efea5ab62920c2310dd08ed4a31a5a3

**Comment by bqpd** [comment]
Probably the 12 lines in `gpkit/constraints/set.py`, then.

**Comment by pgkirsch** [comment]
Unfortunately these are not unbounded - at least not all of them. For example, drag is changing by 5%.

**Comment by pgkirsch** [comment]
What do the relax values mean in the `.debug()` table? (They are all 1)

**Comment by pgkirsch** [comment]
It specifically happens for one of the aero models

**Comment by pgkirsch** [comment]
And for the record, regarding the original issue, the rank ValueError only gets raised starting at commit 4a256fab7fdd6a2f4663335ad7a73f4794540c02

**Comment by bqpd** [comment]
Are you saying that the commit before 4a256fa (that is, 48118cc1f9582a466fb41a6ea2a18906651a4937) ifthe most recent commit on the master branch at which your code runs succesfully?

**Comment by pgkirsch** [comment]
Yes. And half of my model variants continue to work fine up until (not including) bb5f381.

**Comment by bqpd** [comment]
Okay, so could you do the following for each of these three files: `gpkit/constraints/geometric_program.py`,  `gpkit/nomials/data.py`, `gpkit/nomials/nomial_math.py

```bash
git checkout  4a256fa
git checkout  4a256fa~1 $FILE
# check if all model variants run
```

**Comment by pgkirsch** [comment]
Your suspicion is correct.

```
git checkout 4a256fa
git checkout 4a256fa~1 gpkit/constraints/geometric_program.py
```
Not all models work


```
git checkout 4a256fa
git checkout 4a256fa~1 gpkit/nomials/data.py
```
Not all models work

```
git checkout 4a256fa
git checkout 4a256fa~1 gpkit/nomials/nomial_math.py
```
All models work

**Comment by bqpd** [comment]
This is like that blade runner scene. ENHANCE. ENHANCE.

How about if you change line 452 of `nomial_math` from

```python
if not exps[0] or cs[0] == 0:
```
back to 
```python
if not exps[0]:
```

**Comment by pgkirsch** [comment]
Using 4a256fa as a base and then making that change, gives me a `PosynomialInequality P became Signomial after substitutions...`, where `P` looks like `x >= c1*y*z/c2` where `c1` and `c2` are substituted values (both positive).

**Comment by bqpd** [comment]
Hmm....okay, what if you use `HEAD` as a base and run `git checkout 4a256fa~1 gpkit/nomials/nomial_math.py`.

**Comment by pgkirsch** [comment]
Every model runs, still getting the same discrepancy in solution though.

**Comment by bqpd** [comment]
When you said "All models work" a few comments back, did you have no such discrepancy?

**Comment by bqpd** [comment]
(if those working models did have this discrepancy, what commit did that appear at?)

**Comment by pgkirsch** [comment]
Correct, no such discrepancy at  4a256fa with a 4a256fa~1 nomial_math.py.

The discrepancy started at bb5f381.

We should maybe split this thread to avoid confusion - there are two separate issues here (my fault for combining them).

**Comment by bqpd** [comment]
Debugging in person, the issue is both more and less than this...will create new issues as relevant
