### ISSUE TITLE
Print out version in most verbose solve

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1053]
I think it might be good to print out the GPkit version, or even commit hash (if pulled from git), when solving in most verbose mode.

**Comment by pgkirsch** [comment]
I realize the commit hash probably isn't possible given that the hash is assigned during the commit process...

**Comment by bqpd** [comment]
Yerp. Is this to make debugging easier? I tend to think that asking for a `print gpkit.__version__` line isn't too unreasonable...

**Comment by pgkirsch** [comment]
Yeah, more for traceability. This was something I really wish I had had with the `aircraft` model, so I could align the version of the model with the version of GPkit.

**Comment by bqpd** [comment]
Would the print statement not work for that?

**Comment by pgkirsch** [comment]
No, it would! But I'm also wondering if tools/models that use GPkit could do something cute with the `.git/HEAD` and/or `.git/refs/heads/master` files (obviously outside of the scope of this ticket).

**Comment by bqpd** [comment]
(superseded by #1063)
