### ISSUE TITLE
Is it possible to use two different linking philosophies simultaneously?

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1054]
I'm slowly adopting `setup` initialized models and looking to use the new philosophy for linking variables that @whoburg recently introduced me to so that I can use material models (e.g. `compressivestress <= steel['compressiveyieldstrength']`, where steel is an instance of a constraintless model).

But my overarching model is still a `LinkedConstraintSet`. Does it have to be one or the other? The idea of converting everything at once terrifies me, so I would like to do it piecewise, but I'm currently getting substitution conflict errors because `steel != concrete`.

**Comment by pgkirsch** [comment]
I'm at somewhat of a crossroads here so any thoughts are much appreciated!

**Comment by bqpd** [comment]
It doesn't have to be one or another, especially for this usecase, so I'm not sure why you're seeing that error that steel != concrete?

**Comment by pgkirsch** [comment]
I think it's because the models in which the material models are referenced are themselves used in a LinkedConstraintSet, resulting in
```python
ValueError: substitution conflict: could not link because youngsmodulus_Steel was set to 2e+11 but youngsmodulus_Concrete was set to 41000000000.0
```

**Comment by bqpd** [comment]
Oh, yeah. Solutions: 1) give them different names. 2) Convert your linked models piece-by-piece to setup methods, then implement this.

**Comment by bqpd** [comment]
You can switch away from linkedconstraintsets in a piecewise fashion, but you can't add new identically-named variables in low-level models before you've switched away.

**Comment by pgkirsch** [comment]
Gotcha. Thanks!

**Comment by pgkirsch** [comment]
Wait. You totally have an `exclude` kwarg in LinkedConstraintSet that should work here, right?

**Comment by bqpd** [comment]
For this particular case, yup! That increases maintenance problems instead of decreasing them, though. :p

**Comment by pgkirsch** [comment]
I think it's a reasonable bandaid for now. Thanks for implementing this!
