### ISSUE TITLE
Unknown solve is all 1s

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1055]
I'm trying to debug an engine and wing integrated file (at https://github.com/hoburg/d8/commit/25e1dd51fea7e3458a3e7754096dca65fba8c466). The model solves for ranges 2,810 nm and below. I was running with a range of 2,812 which does not converge (the first GP iteration returns unknown). Using the method from https://github.com/hoburg/gpkit/issues/1047 I inspected the unknown result and all free variables had a value of 1. @bqpd any idea what is going on here?

**Comment by mayork** [comment]
I supplied order of magnitude initial guesses for many of the variables and now I get an ill posed unknown solve the fist GP iteration, a feasibility solve, a couple cycles of the dual infeasible then feasibility solve before ending on an unknown solve that is again all 1s

@1ozturkbe this issue relevant to D8

**Comment by mayork** [comment]
also, if I run debug on the model it outputs a result nearly identical to the 2,810 nm case which solves reliably and has not variables bounded or constants relaxed...

**Comment by bqpd** [comment]
This sounds like a fun one.

**Comment by bqpd** [comment]
Tentative theory is that another constraint (perhaps related to the monomial approximations) make the higher range primal infeasible, debug isn't finding it for some reason, and the 1's are just the initial guess passing through because it never solves.

**Comment by bqpd** [comment]
this code seems at a44bf8de7bae122b957bc22c473e0d2b8cbee733 to have a different error, solving until the A matrix becomes singular
