### ISSUE TITLE
Current GPkit SP Heuristic cannot solve D8 model

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1059]
The integrated D8 model at the commit and file below does not solve with our traditional SP heuristic. The first solve returns DUAL_INFEASIBLE (so the model is primal infeasible). A feasibility solve then occurs (an optimal solution is found) before another primal infeasible solve. This pattern continues until the solver returns UNKNOWN. 

However, the model reliably solves using a relaxed constants heuristic (and all relax values are 1 at the end of the final solve). This is the first model we cannot solve with our heuristic but can solve with another heuristic.

file: `CFP_Fuselage_Performance_int_HT.py`
commit: https://github.com/hoburg/d8/commit/b13d88bbafe7470fdf1172149dd0c4084c94c9b4

**Comment by 1ozturkbe** [comment]
As a reminder from our discussions @mayork and I think that using a relaxed-constants solve with penalty functions in the objective not only helps with convergence, but likely significantly speeds up the solve. It may be useful to profile this benefit with one of the larger SPs we have developed that solves with both methods (a pre-2/20 commit of CFP_Fuselage_Performance_int_HT.py on hoburg/d8, or one of Martin's engine codes would be a good candidate).

**Comment by bqpd** [comment]
superseded by #1119
