### ISSUE TITLE
Signomial Equality can be violated

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1067]
in this commit https://github.com/hoburg/d8/commit/685521cdf5d68e7d6a664805b0e78f402e3f554f run D8.py and look at the variables 'hft' and 'dhft' then the constraint on line 805. The signomial equality is violated by roughly 3000%.

**Comment by mayork** [comment]
@bqpd any thoughts on this? we're seeing it again

**Comment by bqpd** [comment]
This is a weird one, I think your guess is probably better than mine. A good way to debug this might be to plot the EQ / approx at each time step, to check that the approx is accurate?

Note that if the cost is insensitive to the value in question it's not required to converge with our current SP criteria.

**Comment by bqpd** [comment]
Could not reproduce; model does not solve on master or nomialmap. My guess is, as above, that the variable was not important to the cost
