### ISSUE TITLE
[fix1048] Not computing sensitivities to relaxed constants

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1073]
[For this, I am running commit d39b91a9 of hoburg/d8, in the fix1048 branch, which tries to resolve issues with NEAR_OPTIMAL solutions] 
Trying to solve the model with relaxed constants, and calling for the sensitivities, returns this:
```python 
sol['sensitivities']
Out[7]: 
{'constants': {\theta_{db}_Mission, Aircraft, Fuselage: -0.00020274757236380924,
  M_{takeoff}_Mission, Aircraft, Engine, EngineConstants: -0.017451664358190976},
 'la': array([  1.00000000e+00,   4.11813259e-06,   3.42431630e-06, ...,
          1.00000729e+01,   9.99992711e+00,   0.00000000e+00]),
 'nu': array([  9.93715754e-01,   6.28424712e-03,   1.13610955e-06, ...,
          1.00000729e+01,   9.99992711e+00,   0.00000000e+00])}
```
The only sensitivities shown are for the constants that are in the 'exclude' category of the relaxed_constants. It seems like the sensitivities for the other variables are not even being computed. Please help.

**Comment by bqpd** [comment]
Yup, if you relax the constants we don't currently process their sensitivities. They're stored in the lambdas for the relaxation constraints, though, so it should be easy to generate them. Let me know if you want me to write that for loop and I'll do it next time I'm at a computer.

**Comment by mayork** [comment]
We want to do that for sure

**Comment by 1ozturkbe** [comment]
Hey @bqpd, if this is an easy fix, @mayork and I would appreciate having this fix quickly (a bunch of D8 stuff relies on being able to obtain these numbers). Thanks!

**Comment by bqpd** [comment]
see https://github.com/hoburg/gpkit/pull/1074

(note that you'll want to multiply all sensitivities by 1/whatever power you put the original cost to, so I think 20 in your case?)

**Comment by mayork** [comment]
Sweet, thanks Ned!

**Comment by mayork** [comment]
@1ozturkbe checkout the branch `near_optima_and_sens` I think it'll do everything we need

**Comment by mayork** [comment]
@bqpd we're presenting to aurora this week and it'd be great to have this working for signomials

**Comment by bqpd** [comment]
(it's working now, right? waiting to merge to master until it works on d8 + has a unit test)

**Comment by bqpd** [comment]
(also, could you add a test for these sensitivities so that the unit tests will catch it if I break them again?)

**Comment by mayork** [comment]
yep this is working quite well and sure i can add a unit test that makes sure we are computing sensitivities

**Comment by mayork** [comment]
@bqpd was the relaxed constants solve method merged to gpkit anywhere?

**Comment by mayork** [comment]
i don't see any merge of relaxed constants to master..can we merge the PR and make an issue to add a unit test after merging relaxed constants into master?

**Comment by bqpd** [comment]
the relaxed consts senss fix? I'm holding off on adding relaxedconsts as an SP algorithm until I understand it a little better.

**Comment by mayork** [comment]
yeah can we merge the fix1048 branch now...can't really write a unit test for it until relaxedconsts is added to gpkit
