### ISSUE TITLE
Returning soltime from autosweep

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#1078]
@bqpd, I'm sure you have a good reason for doing this, but can you explain why, when I use autosolve, `bst.nsols = 9` but `bst.sols` only has 2 solution dicts.  Mostly I want to return how long it took to solve the 9 passes.  

```python
In [7]: bst = autosweep_1d(M, tol, M["h_{batt}"], [hmin, hmax], solver="mosek")

Solved after  9 passes, cost logtol +/-0.00735
Autosweeping took 5.15 seconds.

In [8]: len(bst.sols)
Out[8]: 2

In [10]: bst.nsols
Out[10]: 9
```

**Comment by bqpd** [comment]
Oh, bst.sols only contains the solutions at its ends, but it should have a split_bst or similar attribute which contains a sub-bst with other sols...

Probably I should just make a .solarray property to collate all the solutions.

**Comment by mjburton11** [comment]
This is what I can see so far...  am I missing something?
```python
In [7]: bst.__dict__.keys()
Out[7]: 
['splits',
 'splitub',
 'bounds',
 'sweptvar',
 'sols',
 'splitlb',
 'costs',
 'nsols',
 'tol',
 'costposy',
 'splitval']

In [8]: bst.splits
Out[8]: 
[<gpkit.tools.autosweep.BinarySweepTree at 0x1096143d0>,
 <gpkit.tools.autosweep.BinarySweepTree at 0x1097bba90>]

In [9]: bst.splitub

In [11]: bst.splitub

In [12]: bst.splitlb

In [13]: bst.splitval
Out[13]: 285.56032053379835

In [14]: bst.costs
Out[14]: array([-0.91630981, -1.93341134])
```

**Comment by bqpd** [comment]
bst,splits contains other bsts, where bst.splits[0].sols[0] == bst.sols[0],
bst.splits[0].sols[1] == bst.splits[1].sols[0],  bst.splits[1].sols[1] ==
bst.sols[1]

**Comment by mjburton11** [comment]
Ahh... Got it.  Well it would be great if you could put in the .solarray property.  Is that something that could be done soonish?

On another note, I am finding that the summed time of each solution is less than the time printed when an autosweep is completed.  (i.e. `Autosweeping took 2.76 seconds` but I calculated 1.78) Is the discrepancy because you count the time it takes to do the substitution and fitting?

**Comment by mjburton11** [comment]
@bqpd ping!

**Comment by whoburg** [comment]
@bqpd did you have an answer on the time discrepancy?

**Comment by bqpd** [comment]
The method I proposed above did some double-counting.

**Comment by bqpd** [comment]
Wait, hmm

**Comment by bqpd** [comment]
I'm not sure why that discrepancy was ocurrng before, nor if it still exists with the new `solarray` implementation
