### ISSUE TITLE
Integer vs Float in constraints

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1080]
@1ozturkbe have discovered needing to make all values double manually in constraints that are vectorized (for example `x==3000` should be `x==3000.`) This appears to make a difference in if a model runs or not (see commit 6ecbcbd7c233e85d7d). Anyways, did a little investigation with Woody and created this example
```python
from gpkit import Variable
x = Variable("x")
c = (x==7)
print c.left
print c.right
print c.right/2

from gpkit import VectorVariable
x = VectorVariable(1, "x")
c = (x == 7)
print c
print c.left
print c.right
print c.right/2
```

This seems...not correct.

**Comment by bqpd** [comment]
I don't think this is the underlying bug, because that's just accessing the ArrayConstraint's left and right, which aren't used for anything but printing:

```python
In [5]: c[0].right/2
Out[5]: gpkit.Monomial(3.5)
```

Should still be fixed; related to the issue of latex-printing such constraints.

**Comment by bqpd** [comment]
Superseded by #956
