### ISSUE TITLE
automatic installation of dependecies

### ISSUE THREAD

**Issue by langit** [hoburg/gpkit#1086]
I wonder if this is a good idea: in the setup.py, add one line in the end of arguments like this:

```

setup(
    name="gpkit",
    ...,
    license=LICENSE,
    long_description=LONG_DESCRIPTION,
    install_requires=['numpy', 'scipy', 'pint', 'cvxopt'],
)

```

**Comment by bqpd** [comment]
actually, we already do this! sorry, thought you were referring to a different syntax. Not sure why pip doesn't always install the dependencies automatically.
