### ISSUE TITLE
Add a blurb about GPkit to the Wikipedia page on GP? 

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1089]
What do you think? It might be fun and allow more people to discover the awesome power of GPs! Let me know if I'm crazy.

**Comment by lochieferrier** [comment]
Done! Feel free to edit.

**Comment by 1ozturkbe** [comment]
You are a champion! Wooohooo, I can't believe we haven't done this earlier!

**Comment by bqpd** [comment]
:globe_with_meridians:

**Comment by 1ozturkbe** [comment]
bqpd, please let us know if this results in more clones of GPkit! btw, is there a way for us to see this data. I'm just curious...

**Comment by bqpd** [comment]
There's public data in the graphs of the github, but the docs analytics are using my private account...we could create a shared lab gmail account to share analytics access?

**Comment by bqpd** [comment]
Though we can't track clones, I've seen two visitors coming to the repo
through wikipedia.
