### ISSUE TITLE
stray rst-e file appears when building docs

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#1095]
Every time I build the html version of the docs, a file `docs/source/autodoc/gpkit.rst-e` appears. Is this local to my machine, or can others reproduce?

**Comment by bqpd** [comment]
Doesn't appear here

**Comment by edfan** [comment]
Occurs for me- will look into it

**Comment by edfan** [comment]
Arbitrary OS X vs GNU sed discrepancies... lack of a space was causing the "-e" flag to be appended for whatever reason.

**Comment by bqpd** [comment]
OS X sed is this makescript's bane, I swear.

**Comment by bqpd** [comment]
Superseded by #1102
