### ISSUE TITLE
clarify when substitutions occur, behavior for submodels

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#1100]
Here's a simple example where a substitution done 2 layers deep does not actually get substituted:

```python
from gpkit import Model, Variable


class Car(Model):
    def setup(self):
        W = Variable("W", "lbf", "weight")
        self.engine = Engine()
        self.chassis = Chassis()
        self.components = [self.engine, self.chassis]
        suspW = self.chassis.suspension.topvar("W")
        self.chassis.suspension.substitutions.update({suspW: 50})   ## sub in question
        return [self.components,
                W >= sum(c.topvar("W") for c in self.components)]


class Engine(Model):
    def setup(self):
        W = Variable("W", 400, "lbf", "weight")


class Chassis(Model):
    def setup(self):
        W = Variable("W", "lbf", "weight")
        Wother = Variable("W0", 300, "lbf", "non-suspension chassis weight")
        self.suspension = Suspension()
        return [W >= Wother + self.suspension.topvar("W"),
                self.suspension]


class Suspension(Model):
    def setup(self):
        W = Variable("W", 20, "lbf", "weight")

if __name__ == "__main__":
    c = Car()
    c.cost = c.topvar("W")
    sol = c.solve()
    print sol.table()
```

Note: running the code above, the final value of `W_Car/Chassis/Suspension` is 20 lbf.

If the `## sub in question` line is changed to 
```python
self.chassis.substitutions.update({suspW: 50})   ## sub in question
```
then the final value of `W_Car/Chassis/Suspension` is 50 lbf.

So, the current behavior is that substitutions made in setup methods only stick if the model whose substitutions were changed is included in the returned constraints of the setup method.

**Comment by bqpd** [comment]
Yup! I'm tempted to just link & make identical all substitutions dictionaries, since no-one's started using them in the time that the functionality has been there.

**Comment by bqpd** [comment]
(if I did that the example above would work)

**Comment by whoburg** [comment]
any cons to that approach? Speed decrease?

**Comment by whoburg** [comment]
BTW, here's a description of the current behavior in case we keep it (we should document it):

When doing substitutions inside a setup method, it is ok to do `some_model.substitutions.update(subs)` only if `some_model` is included in the constraints returned by that same setup method.

**Comment by bqpd** [comment]
No cons, so implemented this!
