### ISSUE TITLE
SP sweeps throw error in post process

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1113]
I tried to do a sweep in an SP and got this error in post process

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9b17bb90b609> in <module>()
----> 1 sol = run_optimal_D8(True)

/Users/mayork/Documents/GpGit/d8/SP_aircraft.pyc in run_optimal_D8(fixedBPR, pRatOpt)
    499 
    500     sol = m_relax.localsolve(verbosity=4, iteration_limit=200, reltol=0.01, skipsweepfailures=True)
--> 501     post_process(sol)
    502 
    503     percent_diff(sol, 'D82', Nclimb)

/Users/mayork/Documents/GpGit/d8/relaxed_constants.pyc in post_process(sol)
     40     """
     41 
---> 42     for i in range(len(sol.program.gps)):
     43         varkeys = [k for k in sol.program.gps[i].varlocs if "Relax" in k.models and sol.program.gps[i].result(k) >= 1.00001]
     44         if varkeys:
```

**Comment by bqpd** [comment]
which branch were you on and what was the error? :p

**Comment by mayork** [comment]
whoops copied N-1 lines...

```
AttributeError: 'list' object has no attribute 'gps'
```

I got this on both `master` and `fastsp`

**Comment by mayork** [comment]
it's been a while since I ran an SP sweep so I have no idea what commit would have caused this..might be worth adding a unit test for this

**Comment by bqpd** [comment]
The issue is in your post_process script; when you run a sweep,`.program` is an array of the individual SPs.

**Comment by mayork** [comment]
gosh im stupid lol...I was thinking "ironic I have a post process function named the same thing"

**Comment by bqpd** [comment]
Heh, no worries! If you write that script as `Mission.process_result` it'll run the same for sweeps or single solves.
