### ISSUE TITLE
Sol.table(latex = 2) does not output units for relaxed_constants

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#1120]
Hey @bqpd, noticed a small bug in the solution latex outputs. When I run SP_aircraft in hoburg/SPaircraft and run 
```python
print sol.table(latex = 2)
```
I get this (just an example snippet):
```latex
\begin{longtable}
\multicolumn{3}{l}{\textbf{Mission/Aircraft/Engine/Relax}} \\ \\
$HTR_{f_SUB}$ & $$ & 1 - HTRf^2 \\
$HTR_{lpc_SUB}$ & $$ & 1 - HTRlpc^2 \\
$T_{t_{4.1_{max}}}$ & $$ & Max turbine inlet temperature \\
 &  &  &  \\
\end{longtable}
```
T_{t_{4.1_{max}}} should have units of K. It's the same with all of the relaxed constants. The same issue does not occur with latex = 1 or 3 however.

**Comment by bqpd** [comment]
Hmm, I'm getting units just fine on `latex=2` here. Can you send me or put in a repo a script that shows this?

**Comment by 1ozturkbe** [comment]
Wow, false alarm. My bad. I totally thought that latex=2 wasn't giving units, but then I realized that there are three outputs for every variable that have been substituted and relaxed. Eg. for the turbine max inlet temperature there are:
\multicolumn{3}{l}{\textbf{Mission/Aircraft/Engine}} \\ \\
$T_{t_{4.1_{max}}}$ & $~\mathrm{K}$ & Max turbine inlet temperature \\
 &  &  &  \\
AND
\multicolumn{3}{l}{\textbf{Mission/Aircraft/Engine/Relax}} \\ \\
$T_{t_{4.1_{max}}}$ & $$ & Max turbine inlet temperature \\
 &  &  &  \\
AND
\multicolumn{3}{l}{\textbf{Mission/Aircraft/Engine/Relax}} \\ \\
$T_{t_{4.1_{max}}}_{before}$ & $~\mathrm{K}$ & Max turbine inlet temperature \\
 &  &  &  \\
And of course, the relaxed-constant variable is dimensionless, and I got confused, and thought I was looking at the '_{before}'. My bad.
