### ISSUE TITLE
substitutions not deleting

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#1131]
@bqpd @whoburg ahh! need you're help on this quick! 

Running `gasmaleperf.py` on jho repo on branch `newsolves`.  It appear that deleting a substitution only temporarily deletes it re-inserts it when trying to solve.  I'm convinced this is why I got `DUAL_INFEAS` because I know it will solve with higher payloads.  Below is the ipython output (I also saw the same behavior as a script):

```python 
In [1]: %run gasmaleperf.py
Beginning signomial solve.
Allowing negative dual variable(s) as small as -1.69108000173e-12.
Allowing negative dual variable(s) as small as -1.64037945553e-13.
Solving took 4 GP solves and 24.2 seconds.
144.324433952

In [2]: M.cost = 1./M["W_{pay}"]

In [3]: del M.substitutions["W_{pay}"]

In [4]: M.substitutions["W_{pay}"]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
KeyError: W_{pay}_Mission/Aircraft

In [5]: sol = M.localsolve("mosek")
Beginning signomial solve.
RuntimeWarning: final status of solver 'mosek' was 'DUAL_INFEAS_CER', not 'optimal'.

The solver's result is stored in model.program.solver_out. A result dict can be generated via program._compile_result(program.solver_out).

In [6]: M.substitutions["W_{pay}"]
Out[6]: 10
```

**Comment by mjburton11** [comment]
any word on this? @whoburg need to fix for JHO performance metrics

**Comment by whoburg** [comment]
@bqpd this is relatively urgent, need for some Air Force questions that we need to answer by tomorow.

**Comment by bqpd** [comment]
@mjburton11, I can't run `gasmaleperf.py`, are you on a particular branch of gpkit-models

**Comment by mjburton11** [comment]
No, I was running it on master

**Comment by mjburton11** [comment]
what's the error?

**Comment by bqpd** [comment]
`KeyError: m_{fac--fit}_Mission/Climb/FlightSegment/AircraftPerf/WingAero`

**Comment by mjburton11** [comment]
That's a problem with `fit_constraintset.py` in gpfit...

**Comment by mjburton11** [comment]
Is it an issue in process result?

**Comment by bqpd** [comment]
yup, good call!

**Comment by bqpd** [comment]
so it's solving, but you're looking for a variable that's not there

**Comment by bqpd** [comment]
`solve_jho(Mission())` and `max_speed(Mission())` run into that issue

**Comment by mjburton11** [comment]
dang it... why is it passing tests... but didn't catch that

**Comment by bqpd** [comment]
while `optimum_speeds(Mission())` is UNKNOWN and `max_payload(Mission())` is DUAL_INFEAS_CER

**Comment by bqpd** [comment]
tests don't run here:

```
======================================================================
ERROR: test_model_gasmaleperf_py_mosek_cli (gpkit.tests.from_paths.TestFiles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tao/projects/gpkit/gpkit/tests/helpers.py", line 62, in test
    testfn(name, import_dict, path)(self)
  File "/home/tao/projects/gpkit/gpkit/tests/from_paths.py", line 50, in <lambda>
    lambda self: getattr(self, name)()))  # pylint:disable=undefined-variable
  File "/home/tao/projects/gpkit/gpkit/tests/from_paths.py", line 41, in test_fn
    mod.test()
  File "gasmaleperf.py", line 352, in test
NameError: global name 'M' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.390s

FAILED (errors=1)
```

**Comment by mjburton11** [comment]
That's because on `gpkit-models` master I forgot to include M in the solve_jho model.  I since fixed that in branch newsolves.

**Comment by bqpd** [comment]
ok great!

**Comment by mjburton11** [comment]
so I also saw max_payload as DUAL_INFEAS_CER. I assumed that was because it was adding in the `W_{pay}` substitution, hence the issue.

**Comment by bqpd** [comment]
any idea what the difference in states between our two folders are? are there any uncommitted files?

**Comment by bqpd** [comment]
I think you're probably right about the DUAL_INFEAS, looking into it...

**Comment by mjburton11** [comment]
are you referring to gpfit differences?

**Comment by mjburton11** [comment]
Also, `optim_speeds` won't work unless you first get all the substitutions inputted from `solve_jho` method.  You should probably do the same for `max_payload`.

**Comment by bqpd** [comment]
What exactly should I run?

**Comment by bqpd** [comment]
(referring to differences in _any_ of the repositories, after the question of why I'm getting this KeyError and you're not...)

**Comment by mjburton11** [comment]
run
```python
M = Mission()
sol = solve_jho(M)
max_payload(M)
```

**Comment by mjburton11** [comment]
I'm at my work computer... :( I don't know what, if anything is different.

**Comment by bqpd** [comment]
all repos are on master except jho with no uncommitted changes? hmm what gpkit branch are you on...that might be my issue...

**Comment by bqpd** [comment]
Yeah I think that was why I was getting the FCS KeyError

**Comment by mjburton11** [comment]
I thought I was on master. Now that I think about it, I may have changed something on gpfit. Give me 15 min and I'll look into it.

**Comment by bqpd** [comment]
Naw I think that was my bad. Debugging now.

**Comment by bqpd** [comment]
Okay, so that re-appearing "W_{pay}" doesn't happen on master~1, but the model still gets dual-infeasible

**Comment by mjburton11** [comment]
So did the issue around `m_{fac--fit}` get resolved?

**Comment by bqpd** [comment]
it's something in `nomialmaps`, punting for now

**Comment by mjburton11** [comment]
hmm ok... cause I was gpfit master so... who knows.

**Comment by mjburton11** [comment]
I'm still seeing the reappearing `W_{pay}` on gpkit master

**Comment by mjburton11** [comment]
Just ran this on master: 
```python
In [5]: M.substitutions["W_{pay}"]
Out[5]: 10

In [6]: del M.substitutions["W_{pay}"]

In [7]: sol = M.localsolve("mosek", verbosity=0)
RuntimeWarning: final status of solver 'mosek' was 'DUAL_INFEAS_CER', not 'optimal'.

The solver's result is stored in model.program.solver_out. A result dict can be generated via program._compile_result(program.solver_out).

In [8]: M.substitutions["W_{pay}"]
Out[8]: 10
```

**Comment by bqpd** [comment]
Might have it. Should there be a fixed value for `t_loiter`?

**Comment by mjburton11** [comment]
Yes. That's my bad.  Should be 6

**Comment by bqpd** [comment]
haha yeah it's 10.02 pounds for 6 days

**Comment by bqpd** [comment]
65 pounds for 2 days

**Comment by mjburton11** [comment]
oh yeah! I just tried it too and it seemed to work. Weird, that I wasn't seeing this before.

**Comment by bqpd** [comment]
There's definitely a substitutions bug. Do you want the gross fix or should the right one to master?

**Comment by mjburton11** [comment]
Ok, so I'm getting that it solves, but the solution is `sol("W_{pay}") = 10`

**Comment by mjburton11** [comment]
```python
In [5]:     oldcost = M.cost
   ...:     M.cost = 1./M["W_{pay}"]
   ...:     oldsubw = M.substitutions["W_{pay}"]
   ...:     M.substitutions.update({"t_Mission/Loiter": 4})
   ...:     del M.substitutions["W_{pay}"]
   ...:     sol = M.localsolve("mosek")
   ...: 
Beginning signomial solve.
Allowing negative dual variable(s) as small as -1.35754990725e-12.
Solving took 2 GP solves and 5.84 seconds.

In [6]: sol("W_{pay}")
Out[6]: <Quantity(10.0, 'force_pound')>
```

**Comment by bqpd** [comment]
Yup, you were right about the substitutions bug although it wasn't causing infeasibility (because a constant cost is totally feasible)

Gross fix:
```python
def max_payload(M):
    oldcost = M.cost
    M.cost = 1./M["W_{pay}"]
    oldsubw = M.substitutions["W_{pay}"]
    M.substitutions.update({"t_Mission/Loiter": 2})
    sp = M.sp()
    del sp.substitutions["W_{pay}"]
    sol = sp.localsolve("mosek")
```

try that

**Comment by mjburton11** [comment]
Great! Let me know when the bug is fixed on master.

**Comment by mjburton11** [comment]
Also, while I have you on the line, can you help me get Mosek installed?

**Comment by mjburton11** [comment]
I'm getting an import error, even though I installed it

**Comment by bqpd** [comment]
try re-running `from gpkit.build import build_gpkit; build_gpkit()`

**Comment by bqpd** [comment]
what's the import error?

**Comment by mjburton11** [comment]
```python
ImportError: Could not load MOSEK library: 
ImportError(OSError('dlopen(/Users/mjburton11/.gpkit/expopt.so, 10): Library not loaded: 
libmosek64.8.0.dylib\n  Referenced from: /Users/mjburton11/.gpkit/expopt.so\n  Reason: image not 
found',),)
```

**Comment by bqpd** [comment]
What's the output of `from gpkit.build import build_gpkit; build_gpkit()`?

**Comment by mjburton11** [comment]
do I run that in ipython? or command line?

**Comment by mjburton11** [comment]
`OSError: [Errno 13] Permission denied: 'gpkit/_mosek/lib/__init__.py'` got this error when I tried running in ipython

**Comment by bqpd** [comment]
ohhhh

**Comment by bqpd** [comment]
I think root owns your mosek lib

`sudo chown -R $your_username gpkit` and then run build_gpkit again in ipython

**Comment by bqpd** [comment]
(or `python -c "from gpkit.build import build_gpkit; build_gpkit()"` from the command line)

**Comment by mjburton11** [comment]
Now getting this error: `OSError: [Errno 13] Permission denied: '/Users/mjburton11/.gpkit/expopt.so'`

**Comment by bqpd** [comment]
`sudo chown -R $your_username ~/.gpkit`

**Comment by mjburton11** [comment]
Hmmm, that didn't seem to work.  got the same import error

**Comment by bqpd** [comment]
What was the output of `python -c "from gpkit.build import build_gpkit; build_gpkit()`

**Comment by mjburton11** [comment]
```
Found the following solvers: mosek, mosek_cli, cvxopt
#     Replacing directory gpkit/env
Replaced the directory gpkit/env
```

**Comment by bqpd** [comment]
And you're in the top-level `gpkit` directory when you run that? (that is, the same folder as `setup.py`) ?

**Comment by bqpd** [comment]
Sorry, forgot it required that. :-/

**Comment by mjburton11** [comment]
yep

**Comment by bqpd** [comment]
Ugh, maybe macs changed their dynamic linking again, @edfan was also having an issue. Use "mosek_cli" for now, I'll try to grab a mac this week and debug.

**Comment by mjburton11** [comment]
Ok, yeah "mosek_cli" works for now.

**Comment by bqpd** [comment]
Or better yet try the `.bash_profile` edit in #1131

**Comment by bqpd** [comment]
This really shouldn't be (and briefly wasn't) necessary, we had fancy DYLIB linking working at one point.

**Comment by mjburton11** [comment]
#1131 is this issue? is there a different issue that I should be looking at?

**Comment by bqpd** [comment]
Derp, yes, meant #1104

**Comment by bqpd** [comment]
@mjburton11, does that let you use MOSEK?

**Comment by mjburton11** [comment]
No, that didn't fix it... :(
