### ISSUE TITLE
Highest level constraint not solved tightly; Tight() doesn't notice.

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1132]
I have a relatively small model (~10 constraints). It is an SP and has vector variables.

The model looks something like:

``` python
objective = x
constraints = [
    x == a*y,
    ...
    # more constraints
    ]
```

The model solves, but only takes two iterations which seems like a red flag. The solution seems right, and is validated with a separate calculator, except that the optimal value of `x` is too high (about 10%) and that first constraint isn't tight, even when I make it into an equality constraint! Alarmingly, even wrapping it in `Tight([])` doesn't trigger a warning.

**Comment by pgkirsch** [comment]
Anonymized code sent to @bqpd @whoburg for reference. (+1 for #834)

**Comment by pgkirsch** [comment]
Two discoveries:
1. It had nothing to do with being an SP (in fact the program could be simplified to a GP).
2. It was a scaling issue. Changing the unit of `x` from tons to kgs solves the issue.

**Comment by pgkirsch** [comment]
It is still concerning to me that Tight didn't catch this though, so I'm going to leave this open, to be closed as either @bqpd  or @whoburg see fit.

**Comment by pgkirsch** [comment]
(Solver is cvxopt)

**Comment by bqpd** [comment]
Could you send us the GP version? I think Tight needs to be updated for Signomial Equalities.

**Comment by pgkirsch** [comment]
Done. Sorry for the delay.

**Comment by bqpd** [comment]
GP version is all-tight on my computer with mosek...trying cvxopt

**Comment by bqpd** [comment]
Also all-tight with cvxopt

**Comment by bqpd** [comment]
Even the SP version with cvxopt and old pint is tight on my computer...closing this for now

**Comment by whoburg** [comment]
@pgkirsch, do you agree this is fixed?
