### ISSUE TITLE
Best practice method for accessing variables in subsystem models

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1137]
Say I have a system model (e.g. aircraft) with a subsystem (e.g. wing) that has a variable (e.g. mass). What is the best practice method for accessing the variable? `ac['mass_Aircraft/Wing.1']` is somewhat gross.

EDIT: other subsystems may also have the variable, so `ac['mass']` is not an option here.

**Comment by pgkirsch** [comment]
@mayork @1ozturkbe how do you guys typically access variables in sub-models from the system level model? Or do you always have unique varkeys?

**Comment by mayork** [comment]
I do what you said above, a better method is probably called for because it can get really ugly.

**Comment by bqpd** [comment]
I think best practice is for `ac` to have a `.wing` attribute so that you can do `ac.wing["mass"]`

**Comment by pgkirsch** [comment]
That would be super dope

**Comment by bqpd** [comment]
It doesn't require anything on the GPkit end, just python!

As mentioned elsewhere, my hope is still to deprecate square-bracket notation and have that be `ac.wing.mass`

**Comment by pgkirsch** [comment]
Ah yeah, dumb, sorry.
