### ISSUE TITLE
.debug() relax tolerance should be lower and exposed as a kwarg

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1143]
It seems like `.debug()` performed some awesome black magic on a troubled model, but then, like all good magicians, didn't tell me how to do the trick. Is there something to be gleaned from this:

```python
In [2]: sol1 = hl1.solve()
   ...: 
Using solver 'cvxopt'
Solving for 242 variables.
Solving took 10.4 seconds.
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
<ipython-input-1-0da4b2f64ebd> in <module>()
      4 hl1 = HyperloopSystem(propulsion="podside")
      5 hl1.substitutions.update({'cruisevelocity': 210, 'minpodcapacity': 5.2})
----> 6 sol1 = hl1.solve()

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     82         else:
     83             self.program, solvefn = genfunction(self, verbosity)
---> 84             result = solvefn(solver, verbosity, *args, **kwargs)
     85             solution.append(result)
     86         solution.program = self.program

/Users/philippe.kirschen/Documents/Optimization/gpkit/gpkit/constraints/gp.pyc in solve(self, solver, verbosity, warn_on_check, *args, **kwargs)
    201                 "A result dict can be generated via "
    202                 "program._compile_result(program.solver_out)." %
--> 203                 (solvername, solver_status))
    204 
    205         if solver_status.lower() == "near_dual_feas":

RuntimeWarning: final status of solver 'cvxopt' was 'unknown', not 'optimal'.

The solver's result is stored in model.program.solver_out. A result dict can be generated via program._compile_result(program.solver_out).

In [3]: hl1.debug()
> Trying to solve with bounded variables and relaxed constants
Using solver 'cvxopt'
Solving for 537 variables.
Solving took 20.1 seconds.
> ...success!

> Trying to solve with relaxed constraints
Using solver 'cvxopt'
Solving for 571 variables.
Solving took 7.78 seconds.
> ...success!
```

**Comment by pgkirsch** [comment]
I should add that `debugoutput['boundedness']` is an empty dict.

**Comment by pgkirsch** [comment]
@mayork Does this use your relax heuristic?

**Comment by mayork** [comment]
it solved with both a relaxed constants method and a relaxed variables method (what was in Boyd's paper I sent you). Since boundedness is empty you should check to see if there are any relaxed constants or constraints (not sure how to do this, if you look at post process on the SP aircraft repo it will check automatically for relaxed constants).

**Comment by bqpd** [comment]
debug should print any relaxed variables...is this an SP?

**Comment by pgkirsch** [comment]
GP. I noticed one slack variable was slightly greater than 1 just by looking at the dict  but I figured there might be a specific command for finding all of them.

**Comment by bqpd** [comment]
There is if you use RelaxConstants manually, but debug really should be
printing that out if it's greater than 1.01

**Comment by pgkirsch** [comment]
Ah gotcha. It's 1.002 so doesn't meet the threshold. Should I interpret this as meaning that the problem is primal infeasible?

**Comment by bqpd** [comment]
I should probably change that threshold to be much smaller. Yeah, you're 2%
infeasible.

**Comment by bqpd** [comment]
meant .2%

**Comment by pgkirsch** [comment]
You could just expose it like the Tight tolerance?

**Comment by bqpd** [comment]
Maybe!
