### ISSUE TITLE
ConstraintsRelaxed not working as expected

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1145]
This may be a case of me not using syntax correctly, but I tried to emulate the syntax from the docs, so I'm not sure.

I have a model:
```python
class System(Model):
    def setup(self, ....):
        # lots of nonsense
        constraints = ConstantsRelaxed(constraints,
                                       include_only=["problemchild"])

        self.cost = constraints.relaxvars.prod() * objective**0.01
        return constraints, substitutions
```

I know that increasing `problemchild` from its initial value solves the model, yet solving the above returns unknown and gives a warning about `problemchild` having no upper bound.

**Comment by mayork** [comment]
@pgkirsch it looks to me like you're mixing relaxed constants and relaxed constraints. Was that intentional? I think that you might not be penalizing slack on the constants with your current code.

**Comment by pgkirsch** [comment]
@mayork Thanks for the reply. I'm deliberately using relaxed constants, because I just want to relax one fixed variable.

Isn't that what the `.relaxedvars` part of the objective does?

**Comment by bqpd** [comment]
Yeah, this should work. This might be the first time the `include_only` syntax has been used...could you make a MWE?

**Comment by bqpd** [comment]
Is this maybe a pint-version issue?

**Comment by bqpd** [comment]
Works fine on 0.6 as well

**Comment by pgkirsch** [comment]
I think this was a model issue and not a bug. I don't think I will be able to recreate a MWE. If you say the syntax I showed should work, then it must be the case that relaxation of the particular variable gives a nearly dual-infeasible model. Closing this issue.
