### ISSUE TITLE
sol.key_variables()

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#1146]
Closely related to #805.

The number of variables that really characterize a system is usually a pretty small subset of all the variables (my data point is that I really only care about ~7 variables out of ~250). I like efforts to make table less unwieldy (e.g. `sol.summary`), so I'm proposing a `sol.key_variables()` (maybe `sol.characteristic_variables()`?) that prints variables that have been tagged somehow as being important (probably in the Variable declaration, but maybe in the `.solve` if that's preferable.

**Comment by bqpd** [comment]
You can make your own key_variables list as a model attribute and pass it as the first argument to table/summary!

**Comment by pgkirsch** [comment]
Good point!
