### ISSUE TITLE
Does GPkit work with Mosek 8?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#1155]

**Comment by mayork** [comment]
@bqpd

**Comment by bqpd** [comment]
It solves, but I agree that something's funny with the timing...

**Comment by whoburg** [comment]
what's "it"?

**Comment by bqpd** [comment]
MOSEK 8

**Comment by bqpd** [comment]
(I confused this issue with another, though, is which is also why my statement is confusing)

**Comment by whoburg** [comment]
Reopening this because as far as I can tell (from 5a37a515878fdca264aabe9cc42fce956883a389), gpkit does not currently work with Mosek 8, and this is the only ticket I can find tracking that issue.

**Comment by bqpd** [comment]
That was my misunderstanding! It appears to work fine, though we should test this

**Comment by whoburg** [comment]
- [ ] need to switch the docs back, they currently say mosek 7
