### ISSUE TITLE
Verify that check_result() is not taking a long time inside GP.solve()

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#125]
Profile this after implementing #23 .

**Comment by whoburg** [comment]
I added some timing machinery in f46cba54a2e876e02f06dba39fd7c6010a071638. This means that `GeometricProgram.solve()` will now print more time information, if `verbosity > 1`.

@bqpd, if you like this, I think we should move this to 0.4, and use the fancy models we use as test cases to get a feel for the times.

**Comment by bqpd** [comment]
Sounds good!

**Comment by bqpd** [comment]
@whoburg, let's meet up and take a quick look at this.

**Comment by bqpd** [comment]
Anecdotally verified during profiling.
