### ISSUE TITLE
use NomialData more often

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#273]
Some functionality could be better implemented as methods of `PosyTuple` (e.g. substitution), or at least we could make methods that take in `PosyTuple` classes instead of  `varlocs`, `exps`, etc.

Renaming idea: `NomialData`.

`small_scripts.locate_vars` could be refactored as part of this. Everywhere it is called we should probably instead be calling the constructor of a `NomialData`.

Related to #226.

**Comment by bqpd** [comment]
Substitution should happen in NomialData?

**Comment by whoburg** [comment]
also `simplify_and_mmap`

**Comment by bqpd** [comment]
This seems pretty closeable to me with the refactor
