### ISSUE TITLE
refactor substitution?

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#283]
From #279 :

 - [x] getsubs and vectorsub are undocumented and confusing (they seem to have similar roles, but one returns something, and the other operates by side effect)
 - [ ] In #273 we discussed that functions involving varlocs, exps, cs, should perhaps be implemented as part of NomialData
 - [x] A lot of repeated code, e.g. under elif isinstance(sub, VarKey) vs elif isinstance(sub, Monomial).
 - [x] "too-many-branches" warning from pylint -- feels like a maze of conditionals...

**Comment by bqpd** [comment]
Some amount of 3 and 4 above is the attempt to do typed programming in Python. :-/ Which would be great to fix, I'm just not sure how.

**Comment by bqpd** [comment]
This got a whole lot better.
