### ISSUE TITLE
unitstr should not exist

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#292]
Refactor the `small_scripts.unitstr` function; eliminate it if possible.

Related: Currently as a user I am aware of 4 ways to specify something without units (that's probably too many). They are:
1. `"dimensionless"`
2. `''` (empty string)
3. `None`
4. `"-"`

**Comment by bqpd** [comment]
@whoburg, do you think `unitstr` might now capture enough functionality / prevent enough code duplication to justify its existence?

**Comment by whoburg** [comment]
I'm fine with it existing if it needs to, my bigger concern is standardization of unit strings across object types.

1. All unit-ed gpkit objects should have a `unitstr` attribute.
2. The unitstr attribute should return a string whose format is consistent across all the types.
3. Arguments to unitstr (like `dimless`) should be standardized.
4. As described above, we should standardize how unitless things are specified (and printed).

It seems most natural to me to implement `unitstr` as a method of the objects (possibly using inheritance), but I'm fine with it being in small_scripts if that makes more sense to the guy writing the code.

**Comment by bqpd** [comment]
Made a commit to standardize all these things!
