### ISSUE TITLE
should we be on pythonxy?  

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#311]
https://code.google.com/p/pythonxy/
(cvxopt is)

Would greatly simplify windows installation for some users

**Comment by bqpd** [comment]
That would be amazing. Will test on my Win laptop.

**Comment by bqpd** [comment]
I think we should use this instead of Anaconda on Windows.

**Comment by whoburg** [comment]
Could also use pythonxy to install cvxopt on Windows, even if gpkit is not on it.

**Comment by whoburg** [comment]
This remains open to determine whether we should get in touch with pythonxy and ask them to include us in their package.

**Comment by bqpd** [comment]
Closed since we no longer use pythonxy on windows.
