### ISSUE TITLE
Add numpy to pylint

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#330]
So that PosyArray is known to have the `.sum` method inherited from numpy, etc.

**Comment by whoburg** [comment]
Can you give example of file where this type of warning occurs? (I know it's an issue but need specific example to try to address)

Note this is a know issue but there doesn't seem to be a clean fix:
http://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members

**Comment by bqpd** [comment]
Oh, hmm. It's happening in `posyarray.py`

**Comment by whoburg** [comment]
More info: https://bitbucket.org/logilab/pylint/issues/58

Thus, I don't see an easy fix. I tried adding `extension-pkg-whitelist=numpy` as suggested by some, but that doesn't seem to fix it.

I think the issue should stay but I don't know how to fix for 0.3.0.

**Comment by bqpd** [comment]
Sounds reasonable.

**Comment by bqpd** [comment]
@galbramc, this appears to no longer be an issue?

**Comment by galbramc** [comment]
Apparently nor. Most likely upgrading pylint fixed this.
