### ISSUE TITLE
2D GP interpolations are seemingly not convex

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#34]
Builds on #33. Could look something like:

``` python
sol = gp.splinesol({'V': np.linspace(45, 55, 50), 'V_min': np.linspace(20, 25, 50)})
```

Greatly reduces the number of optimizations that need to be done for a given plot.

**Comment by whoburg** [comment]
@whoburg guilty of letting this fall through for too long. Will not, however, be dealt with for initial gpkit release.

**Comment by bqpd** [comment]
(bump)

**Comment by bqpd** [comment]
It's not that they aren't convex, just that high dimensional intersections are more complicated than expected. I have some examples in an ipynb from this summer.

**Comment by whoburg** [comment]
this used to capture the thing that we now refer to as autosweeps -- should it stay open (with a new title)?

**Comment by bqpd** [comment]
hmm! could be fun to have as a historical artifact, although the discussion is a bit cluttered...
