### ISSUE TITLE
refactor NomialData.locate_vars

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#352]
or at the very least, more inline comments for all the conditional branches

**Comment by whoburg** [comment]
half of the conditionals are to make `varkeysbyname` dict -- no longer necessary because `KeyDict` does this automatically.

**Comment by bqpd** [comment]
Also refactor nomialdata's two construction methods (nomials is currently not created by __init__)

**Comment by bqpd** [comment]
This is now just six lines of code in `NomialData.__init__` :clap:

**Comment by whoburg** [comment]
:+1:
