### ISSUE TITLE
allsubs and separate_subs should not exist

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#366]
I feel that we're spending too much time grouping and ungrouping substitutions and sweeps. I feel that code to handle substitutions vs sweeps should just be kept separate (sweeps can rely on substitution perhaps).

Might as well just use a `sweep=` kwarg instead of adding sweeps to the substitutions dict.

Got initial verbal buy-in on this from @bqpd  :)

**Comment by bqpd** [comment]
Everything's in `substitutions` now
