### ISSUE TITLE
refactor constraint inheritance

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#387]
MonoEQConstraints are currently instances of Posynomial but not Monomial:

```python
In [1]: from gpkit import Variable, Monomial, Posynomial

In [2]: x, y = Variable('x'), Variable('y')

In [3]: c = (x == y**2)

In [4]: type(c)
Out[4]: gpkit.nomials.MonoEQConstraint

In [5]: isinstance(c, Posynomial)
Out[5]: True

In [6]: isinstance(c, Monomial)
Out[6]: False
```

I think we can probably solve this by having MonoEQConstraint inherit from Monomial instead of from Constraint, which puts MonoEQConstraint beside Constraint and SignomialConstraint in the inheritance tree.

**Comment by bqpd** [comment]
Sounds good!

**Comment by bqpd** [comment]
Thought about this last night while falling asleep, and I think that Constraints should _not_ inherit from Signomial, but instead have a signomial attribute and define their own `sub` method. I'll code something up to make this idea clearer.

**Comment by bqpd** [comment]
@whoburg  what's the status of this?

**Comment by whoburg** [comment]
Yes, I agree that MonoEQConstraints are PosynomialConstraint (sets), in the sense that they can be expressed equivalently as a set of posynomial constraints.

The refactor definitely fixed most of the inheritance issues.

Do we have an issue open somewhere to track out need to draw out an updated inheritance diagram for the docs?

**Comment by bqpd** [comment]
Yup. :D (#350)
