### ISSUE TITLE
Supporting equality constraints in signomials?

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#397]
When I try to put an equality constraint in a signomial, I get the following error:

```
TypeError: Iterable ......... contains element 'False' of invalid class <type 'bool'>.
```

Obviously, an easy work around is to add both `<=` and `>=` constraints, but should we not support equality constraints? Sorry if this is something that has already been discussed and decided upon.

Also sidenote: what happened to getting rid of `SignomialsEnabled`?

**Comment by bqpd** [comment]
Oh shoot, was it supposed to be `EnableSignomials`? Forgot about that change, wonder what happened to it.

**Comment by pgkirsch** [comment]
No no `SignomialsEnabled` is great, but I thought the new SP refactor was going to eliminate the need for a special signomial distinction altogether. Or did I imagine that?

**Comment by bqpd** [comment]
Naw, you still have to tell gpkit to allow negatives and zeroes. We could remove that, potentially, since we have the solve / local solve catch to remind people about global/local optima?

**Comment by pgkirsch** [comment]
I thought that was the plan based on a conversation with @whoburg but it's not important. I'm happy with how it is.

**Comment by bqpd** [comment]
I really like that idea.

**Comment by whoburg** [comment]
Hmm, I'm a little more resistant to that change. Sorry @pgkirsch, I did not mean to make it seem that `SignomialsEnabled` would be going away -- only that we upgraded the logic of how Signomials are handled in a number of ways.

I really think it's important to let users know from the beginning that Signomials are very different than Posynomials, even if that's difficult.

**Comment by whoburg** [comment]
Regarding signomial equality constraints, we don't currently support them.

The GP relaxation of a Signomial equality constraint is likely to be infeasible, so we'll have to use a feasibility-based formulation to solve these, but it's certainly doable.

**Comment by whoburg** [comment]
Also, if we ever implement signomial equality, I'd vote for using a constructor or function to create the constraint, and not trying to implement via operator overloading. Otherwise it becomes really confusing whether `==` means "make me an equality constraint" or "compare these two things and return a bool". We currently only have that type of confusion for Monomials.

**Comment by bqpd** [comment]
You're note "in for a penny, in for a pound"?

**Comment by whoburg** [comment]
on the operator overloading or the signomial anarchy?  :)

**Comment by bqpd** [comment]
The former. The argument for the latter is that it allows users to make SP models which they can then improve to GP models...

**Comment by whoburg** [comment]
I propose closing this. The two items we discussed were

1. Should `==` work for Signomials, and 
2. Should `SignomialsEnabled` be eliminated.

I vote no on both.

I'm open to implementing 1. as a separate `SignomialEqualityConstraint` class or method (or similar).

@bqpd, do you want to keep this open?

**Comment by bqpd** [comment]
What if `==` only worked withing `SignomialsEnabled`? ;)

**Comment by whoburg** [comment]
That's interesting, I'm more open to that. And it would do a boolean comparison outside `SignomialsEnabled`?

I'm curious what will happen with #400. Until that's resolved, I think we can't support signomial equality at all (because even that simple case doesn't find the optimal answer).

**Comment by bqpd** [comment]
#400 is a good example of a simple failure mode: only one side of the eq is tight, but approximating both at each step makes the solve unbearably slow.

**Comment by whoburg** [comment]
(and I think we've conclusively shown that the progress made is strictly due to chattering within the numerical tolerance of the solver.) @pgkirsch

**Comment by bqpd** [comment]
(@pgkirsch, why did you close this?)

**Comment by pgkirsch** [comment]
Closed because I thought it was decided that we don't want to implement signomial equality constraints. If this isn't true I'll reopen. 

If anything a new replacement issue could be something along the lines of "Automatic checking of signomial constraint tightness".

**Comment by bqpd** [comment]
I think we'll need them for the Xu algorithm, though?

**Comment by pgkirsch** [comment]
True, but the only purpose of the Xu algorithm would be to serve as a benchmark for the GPkit algorithm. I have already written the xu_tests to see how GPkit does compared to the Xu algorithm using the examples from Xu paper. Given that equality constraints are somewhat of a pain to implement and that the Xu algorithm requires a number of parameters/a fair amount of tuning, I don't necessarily see the value of implementing it ourselves.

**Comment by whoburg** [comment]
We could reopen this and move it to future? My impression of the current status is that we think supporting signomial equality constraints is both:

a) hard
b) potentially a commonly-requested feature

Therefore, we probably need more planning to figure out clever ways of handling them. My guess is that it's NP hard in general. To me there are two ways that implementing signomial equality constraints could help us:

1) @pgkirsch had trouble implementing the Xu algorithm, which implies to me that our code design could be improved. Implementing Xu would help with this, and would give us a "maybe it will work, maybe it won't" type of heuristic algorithm.

2) There might be a restricted class of signomial equality constraints for which we can say more about the solution behavior -- e.g. maybe things get better if the signomial is quasi-convex, or monotonic? We could develop along these lines and write some papers.

Is this the main ticket capturing signomial equality? If so I think we should leave it open but perhaps move to a future milestone.

**Comment by bqpd** [comment]
Yeah, this is the main ticket. It's in SP bugs and features, which is pretty future as future goes.

**Comment by bqpd** [comment]
Heyyyy so we implemented Signomial Equalities and it's great! They're only sorta annoying.
