### ISSUE TITLE
documentation of modular models

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#432]
Modular models playing together should be thoroughly documented on read the docs.

**Comment by whoburg** [comment]
When we talk about "modular models" we mean the same thing as "model composition", correct?

**Comment by bqpd** [comment]
Yup!

**Comment by bqpd** [comment]
superseded by #442

**Comment by whoburg** [comment]
#442 is a more complex model; this is meant to capture describing the basic functionality, API, etc. Potentially closed by #823 but that's not merged yet.

**Comment by whoburg** [comment]
actually this looks like a dup of #537.
