### ISSUE TITLE
modular model graphical visualization

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#433]
@pgkirsch already built a visualization for viewing the interaction of Variables within a Model. It's build on www.graphviz.org. Could extend that to viewing multiple models and their interactions (shared variables).

**Comment by bqpd** [comment]
Awesome! Yes, this should be done. There's also some Python-specific network plotting libraries that could maybe do this.

**Comment by bqpd** [comment]
replaced by the more specific #1088
