### ISSUE TITLE
Large beam example takes too long in GPkit

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#437]
Large beam example takes minutes, says seconds.

**Comment by bqpd** [comment]
@whoburg; timing is accurate, but solve time doesn't currently include the various substitution/model manipulation steps in Model(). Should it?

**Comment by bqpd** [comment]
@whoburg, this is ready to close pending our decision above

**Comment by whoburg** [comment]
ok, let me make sure I understand -- does this mean the large beam example is an example of a case where GPkit computations significantly outweigh the actual solve time? If so, I propose we convert this to an issue about profiling that and reducing it.

**Comment by bqpd** [comment]
Sounds good.

**Comment by bqpd** [comment]
The large beam example is no longer our best case for this...
