### ISSUE TITLE
test and document a more complex modular model

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#442]
inspiration may be found in these old tests: https://github.com/hoburg/gpkit/pull/493/files#diff-56ac5b7bf40778347e85ccfe2383ebceL209

**Comment by bqpd** [comment]
Goodness gracious. Where to begin with this one. Document 16.82 first? :p

**Comment by bqpd** [comment]
superseded by #879; we're not going to maintain a complex model outside of that repo

**Comment by whoburg** [comment]
also superseded by #537
