### ISSUE TITLE
Manually specifying relationships between inter-model variables

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#447]
Extremely closely related to, and building on, issue #444.
## Example of need 1: Specifying relationships between inter-model variables

Say I have a `wing` model and a `tail` model. Both of these models require a `structure` model, however the definition of the tail reference area, `Svt`, is different from the `wing` and `structure` models' definitions of the reference area, `S`. More specifically `Svt = S/2`.

If I import the structure model into the tail model, I currently need to add a constraint that specifies `Svt == S/2`, which means I need to add a Variable declaration `S = Var...` that my base tail model otherwise wouldn't care about. Otherwise I could add an `Svt` variable and corresponding constraint to the `structure` model, but it doesn't care about `Svt` and is confused about what it is and why it has been burdened with another variable.
## Example of need 2: Differently named variables in interacting models

The current solution to #444 is awesome, but it doesn't discriminate between cases where variables with the same name are intended to be the same quantity and when they aren't. I believe that the user should only be responsible for choosing unique names within the scope of a model. Consider an example where you have an aircraft with thrust `T`. Its engine and flight conditions submodels also has thrust variables named `T`. But by convention, the landing gear model uses `T` to mean wheel track. Obviously if thrust is equal to wheel track we have a problem, not to mention that `pint` will get wildly offended and throw a tantrum. If the designer is manually responsible for specifying which variables connect to each other then you put the responsibility on them to get the distinction right. You could argue the designer should use something other than `T`, but that is suggesting that any model curator should have perfect foresight for all future models and their variable naming conventions.

Another obvious variable name that will be wildly overloaded is `W`.

Very open to syntax suggestions. The only thing I can think of would replace the overloaded `&` (which, for the record, I do really like):

```
...
# parent = Model(objective, constraints)
base_tail = Model(objective, constraints)

# links = # {child_varkey: f(parent_variable)}
links = {'T': T, 'S': Svt*2, `AR`: A} 

# parent.import_model(child)
base_tail.import_model(Structure())
```

**Comment by bqpd** [comment]
re: 1, I think that Svt == S/2 constraint seems reasonable; like, you'd have that written down in a QPROP-style explaination, wouldn't you?

**Comment by bqpd** [comment]
re: 2, indeed! 

When variable names will collide poorly, use `|`, not `&`. (concat, not merge)

I had (and could bring back) a linking helper, but with the new composition it's not too bad:

```python

landinggear = LandingGear() # has 'W' for plane's weight, 'T' for wheel track
airplane = Airplane()  # has 'W' for plane's weight, 'T' for thrust

concatm = airplane | landinggear
concatm.substitutions.update({landinggear["W"]: airplane["W"]})

# OR

mergem =  airplane & landinggear
del mergem.substitutions[landinggear["T"]]
del mergem.substitutions[airplane["T"]]
```

**Comment by pgkirsch** [comment]
Yeah it's not *unreasonable*, but such a constraint would only exist because of the sub-model, which somewhat defeats the point of modularity.

**Comment by bqpd** [comment]
But you've already designed your model explicitly around a particular Structure model...

**Comment by pgkirsch** [comment]
Ah cool to know about the `substitutions.update` trick. Would it be completely invalid to do:
```
concatm = vtail | structure
concatm.substitutions.update({vtail["S_{vt}"]: 0.5*structure["S"]})
```

**Comment by bqpd** [comment]
That should work. I haven't tested too many edge cases with Monomial substitution, so you should try it and report the bugs :p

**Comment by bqpd** [comment]
@pgkirsch:

Need 1 still isn't solved, but Need 2 can be met by: `m.subinplace(wing["x"], tail["y"])` or `m.subinplace({wing["x"]: tail["y"], ...})`

**Comment by whoburg** [comment]
@pgkirsch: is need 1 holding you up?

@bqpd, I'm lost --  there isn't a simple way to accomplish need 1 using substitution?

**Comment by bqpd** [comment]
@whoburg: oh yeah! this could be done with monomial subs.

**Comment by bqpd** [comment]
We should document how to do this things.

**Comment by bqpd** [comment]
Documented (and heavily built upon) by the performance-modeling example :D
