### ISSUE TITLE
sens only gives variable sensitivities, but accepts signomial input

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#450]
Is doing so even possible? I am skeptical.

**Comment by whoburg** [comment]
Aren't the monomial sensitivities just the `nu` dual variables? I'm confused about this ticket.

**Comment by bqpd** [comment]
Yeah! Those can't be recreated from the variable sensitivities, right?

**Comment by whoburg** [comment]
I still don't understand what "variable sensitivities" are. When solving a GP, what the solver returns as the dual solution is the `nu`'s, which are exactly monomial sensitivities. When grouped by posynomials and added, they become posynomial sensitivities (`lambda`).

I must be missing something?

**Comment by whoburg** [comment]
We're talking about `SolutionArray.sens`, right? Doesn't the solution array store the `nu`'s from the solver?

**Comment by bqpd** [comment]
sorry, constant sensitivities, as computed from the nu's

And, yeah, but unless the arg to sens is either an index or exactly one of those monomials I don't think that'll help?

**Comment by whoburg** [comment]
oh --- yeah. I don't think sens should accept arbitrary signomials as input. It's not clear to me what that would mean mathematically.
