### ISSUE TITLE
infeasible models -- suggested substitution finicky

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#467]
There appears to be some sort of path-dependent state that causes the suggested substitution associated with an infeasible model to change depending on previous solves.

To see an example, 
 - check out the `BreguetRange` branch on gpkit.models
 - git gpkit/models/aircraft an `__init__.py` if it doesn't have one (waiting on PR)
 - run the following in ipython notebook

```python
from gpkit.models.aircraft.breguet_range import BreguetRange
m = BreguetRange()
m.interact()
```
Slide the W_oew slider to the right, above 10,000, and watch the behavior. It's possible eventually to get 
```
THE PROBLEM IS INFEASIBLE
    but would become with this substitution:
{}
```
When W_oew = 10062.5.

**Comment by bqpd** [comment]
Yeah, and the numbers are sometimes wrong. There's some bug in constants
feasibility, I think.

**Comment by bqpd** [comment]
Obsolete.

**Comment by whoburg** [comment]
yep, the behavior noted above appears to be gone.
