### ISSUE TITLE
controlpanel minor issues

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#469]
- [x] If I change the slider settings (bounds) for a given slider, I think the number of discrete options should remain constant. Right now, if I narrow the window, it coarsens the discretization of the slider.

 - [ ] might be a mathjax error or something, but currently my model equations tab says

```
[Math Processing Error]
```

**Comment by bqpd** [comment]
1. Good call, I was originally thinking that and it should be totally doable.
  2. It's a persistent MathJax error; if you create the controlpanel a few times it'll come out. Something to do with render order/an overloaded mathjax build queue.

**Comment by bqpd** [comment]
@whoburg, if you want to show the model in the controlpanel I think we should create a new issue.

**Comment by whoburg** [comment]
I think that's better done in a latex pdf output for now, so ok with closing this.
