### ISSUE TITLE
model construction too slow

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#479]
As mentioned in #478, "This is far too slow during model construction. I noticed this on Tony's examples too, that vector-based construction is faster than object-oriented. This should be fixed!"

**Comment by bqpd** [comment]
@whoburg, status of this? Moving to Next Release.

**Comment by whoburg** [comment]
Was there any MWE for the original issue?

I do think it's a problem that it currently takes us approx 10 times as long to generate a model as is takes the solver C call to solve it, and another 8 times the solver time to do our post-processing.

If things continue scaling this way, we could be taking minutes to construct models that take seconds to solve, which is obviously not good.

**Comment by bqpd** [comment]
It's gotten faster...closing this issue as too obvious / vague

**Comment by whoburg** [comment]
this remains a serious issue. As one example, here is the current performance on https://github.com/hoburg/gpkit-models/commit/bb6f9ddbf6a75215649d1c46555de1e3758ce65f

```python
In [1]: from gasmale import GasMALE

In [2]: %time m = GasMALE(discrete=True, DF70=True)
CPU times: user 12.5 s, sys: 108 ms, total: 12.6 s
Wall time: 12.7 s

In [3]: %time sol = m.solve("mosek")
Using solver 'mosek'
Solving for 934 variables.
Solving took 0.144 seconds.
CPU times: user 2.48 s, sys: 110 ms, total: 2.59 s
Wall time: 1.44 s

In [4]: 12.7/0.144
Out[4]: 88.19444444444444
```

... so, it takes 88 times as long to build the model as to solve it.

**Comment by bqpd** [comment]
I didn't close it because it was fixed, but because it was vague :p

**Comment by bqpd** [comment]
Closing this issue because model-based construction is now just as fast as vectorized construction, though both are still too slow.

**Comment by whoburg** [comment]
Do we have an issue to capture the fact that both are still too slow?

**Comment by bqpd** [comment]
Hmm, no, though we have issues for specific slow codes. I'm wary of vague/uncloseable issues, but if we had a specific speed target I'd be down!

**Comment by whoburg** [comment]
specific speed target is for time spent in GPkit functionality (building models, checking solutions, packing results) to be less than the time spent by the solver, for several of our large models (such as the one referenced above).

**Comment by whoburg** [comment]
related to #437

**Comment by bqpd** [comment]
superseded by #996
