### ISSUE TITLE
latex() printing bugs

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#480]
Noticed a few latex bugs. In order of perceived ease of fixing:
- [ ] Controlpanel printing should be modularized
- [x] The opening line of the latex string should be `\begin{array}{ll}` instead of `\begin{array}[ll]`
  (http://latex.wikia.com/wiki/Array_(LaTeX_environment))
- [x] Some constraints and objectives are followed by the units of the objective/constraint in square brackets whereas other aren't
- [ ] Currently the latex environment chosen does not support multi-page models, which is a problem for larger models. This might be best resolved by using a different environment (e.g. align).
- [x] Making seemingly innocuous changes will toggle on/off the MODELNAME part of a variable name. e.g. I changed one of my variable strings from `Wpp` to `W\'\'` and suddenly all of my variables have subscript `Fuselage` appended to them.
- [ ] M. Drela suggests putting a small space between variables in monomials, if there is no exponent taking up space. This probably isn't specific to the latex() method but that's just where I noticed it.
- [ ] modelname is printed in latex output (and controlpanel sliders!), even when all variables come from the same model, which is distracting
- [x] latex for merged models gets very long, making latex difficult to read and controlpanel difficult to use
- [ ] latex for some unit strings underscores letters after underscores. ex: `pound_force_per_square_inch`

**Comment by pgkirsch** [comment]
A screenshot to illustrate a couple of the points

![screen shot 2015-11-20 at 14 32 31 pm](https://cloud.githubusercontent.com/assets/8702579/11310456/bb81ab18-8f97-11e5-940f-cd1412f867ca.png)

**Comment by pgkirsch** [comment]
Also is there any way of printing the model without substitutions?

**Comment by bqpd** [comment]
Yeah! There's a show_subs argument

**Comment by whoburg** [comment]
Models with no submodels currently print the entire Model name for every variable in a controlpanel, which is pretty distracting. For example, "SolarUAV" in this one:
<img width="421" alt="screen shot 2016-01-13 at 1 15 26 pm" src="https://cloud.githubusercontent.com/assets/6042395/12303347/c6e73c40-b9f7-11e5-9998-83d08e0735f0.png">

**Comment by bqpd** [comment]
@whoburg: I think the best fix for this one is to have each model / Constraint handle its own interactives representation in the new branch (it's one of the impetuses)

**Comment by whoburg** [comment]
sounds good, but is there a hotfix we can make now? The model equations latex is hard to read, and I'm finding myself not sharing my model with others because of it.

![screen shot 2016-01-20 at 12 12 47 pm](https://cloud.githubusercontent.com/assets/6042395/12456741/28e1ef0e-bf6f-11e5-91cb-bfbdf40518c2.png)

**Comment by bqpd** [comment]
Quickest fix is to stop printing model names in latex...

**Comment by whoburg** [comment]
sounds good. As a user I'd be willing to make a call that causes that printing to be disabled (so that we don't break modelname printing for users using modularity). Something like

```
m = SolarUAV()
m.disable_modelname_printing()
m
```

Or the disable could be at the gpkit level -- whatever is easiest.

@bqpd: would you be willing to implement? (Put in a PR and I'll approve). This would be a big help.

**Comment by bqpd** [comment]
Oh god this'll be ugly. Okay.

**Comment by bqpd** [comment]
@pgkirsch, did this get fixed in the latest latex PR?

**Comment by pgkirsch** [comment]
I believe so!

**Comment by whoburg** [comment]
I'm reopening this because a bunch of the checkboxes in the original issue are not yet completed.

**Comment by bqpd** [comment]
@whoburg, I believe this should remain closed....

1st unchecked box above is now in https://github.com/hoburg/gpkit/issues/885

4: became https://github.com/hoburg/gpkit/issues/780

2, 3, 5: not clear of the scope of this, feel free to open a new issue

**Comment by whoburg** [comment]
great, I opened #949 and updated the original description with links to issues
