### ISSUE TITLE
latex modelname printing

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#484]
fc0e4f2afec20a4ec7b91572e70a5af60545e51e introduced some problems with latex printing
 - [ ] modelname is printed in latex output (and controlpanel sliders!), even when all variables come from the same model, which is distracting
 - [x] latex for merged models gets very long, making latex difficult to read and controlpanel difficult to use

**Comment by bqpd** [comment]
Fixed 2 in refactor, need to fix for controlpanel as well; right now it just doesn't print any modelnames at all.

**Comment by bqpd** [comment]
Merging this issue into #480
