### ISSUE TITLE
interact substitutions affecting feasibility?

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#488]
Some models that are feasible with values seem infeasible with interact's substitutions; I have an example ipynb from @mjburton11 that I'm going to get working...

**Comment by whoburg** [comment]
@bqpd to search his e-mail and find the corresponding ipynb

**Comment by bqpd** [comment]
We should test this in general; interact and controlpanel are now some of the first things new users see in a demo. (I guess we should document that, too)

**Comment by bqpd** [comment]
I haven't been able to find anything buggy.
