### ISSUE TITLE
Sphinx autodoc broken

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#501]
Our docs do not currently include our docstrings.

**Comment by whoburg** [comment]
Good catch - this is a problem. Which is more likely: a) that there's a bug with Sphinx's autodoc, or b) that our config is somehow wrong? I assume b but want to make sure.

**Comment by bqpd** [comment]
99% sure it's B

**Comment by whoburg** [comment]
some debugging notes from looking at this a bit with @galbramc 

 - autodoc currently builds fine on my mac
 - autodoc did not build fine for @galbramc on Ubuntu
 - @galbramc was able to fix this on his machine by editing `conf.py` in 8da0392d9e09a81a45c6d7527b844832b41b84c9

Glossary is still not building on RTD; we seem to be getting the import errors described in http://read-the-docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc

@bqpd, that FAQ mentions changing settings on admin page; I think you're our admin?

**Comment by bqpd** [comment]
I'm not sure we can install into a virtualenv, though, because of numpy...

**Comment by bqpd** [comment]
But hey! It worked! Great success.

**Comment by bqpd** [comment]
Looks like it doesn't install the packages requirements, thankfully.

**Comment by galbramc** [comment]
Wait, what happened? It just worked!

**Comment by galbramc** [comment]
I see an extra command in the last build, namely "python setup.py install --force"

http://readthedocs.org/projects/gpkit/builds/4377446/

That seems to have done the trick. @bqpd, did you change some settings in RTD?

**Comment by bqpd** [comment]
Yup.
