### ISSUE TITLE
weight breakdown visualization

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#507]
Automatically generate these as output

<img width="523" alt="screen shot 2016-02-02 at 5 29 03 pm" src="https://cloud.githubusercontent.com/assets/6042395/12766554/844577cc-c9d2-11e5-888f-8cd185368749.png">
<img width="463" alt="screen shot 2016-02-02 at 5 29 11 pm" src="https://cloud.githubusercontent.com/assets/6042395/12766555/844e0248-c9d2-11e5-98f0-3c70008abd9f.png">

**Comment by whoburg** [comment]
@mayork

**Comment by whoburg** [comment]
@mayork if you have initial thoughts on how to design this before getting started on coding, post them here - I'm sure you'll get lots of feedback and ideas.

**Comment by mayork** [comment]
I think taking inputs as a series of nested tuples would be easiest...so if we had three weights only, a total and w1 and w2 one level down the input would look like this ('w',['w1','w2'])...my only question is do @whoburg what weights do you want to take as given? I was thinking have a numerical value input for the lowest level weights makes the most sense but am not sure what you want

**Comment by bqpd** [comment]
What about nested (potentially ordered) dicts? `{"w": {"w1": 1, "w2": 3}}

**Comment by whoburg** [comment]
Oh I like the nested dicts idea. Here's a more complicated one:

`{"W": {"W_pay": 100*units("lbf"), "W_fuel": None, "W_wing": {"W_spar": None, "W_skin": None, "W_sys": 100*units("N")}}}`

This allows non-numeric base cases (via None), which is going to be important, e.g. if W_fuel is bounded by another model.

A nice thing is that the logic for deciding what to do with each (key, value) pair in each dict is simple:

```python
if isinstance(value, dict):
    # recurse
else:
    # pass value to `Variable` constructor as the `value` arg.
```
From my limited testing `Variable` deals just fine with values that are numeric, values that have units, and values that are None.

**Comment by bqpd** [comment]
Yup, and the strings allow convenient access to a solution KeyDict.

**Comment by mayork** [comment]
I'm having a little trouble creating constraints after I create all the Var objects...currently I'm trying to put the Vars into a nested list and recursively loop over the list...anyone have a better idea?@bqpd

**Comment by whoburg** [comment]
Might be good to push what you have so far to a branch so we can take a look at the code. If you need help with the git syntax to do so let me know, happy to help.

**Comment by whoburg** [comment]
Design discussion:
original thought was to have the dict keys be strings and have the corresponding `Variable` objects get created upon parsing. What, if anything, should we do about automatically creating variable descriptions?
 - leave as None?
 - let `Breakdown` take a descr keyword arg that is a string applying to all variables, e.g. "Weight breakdown variable"?
 - let `Breakdown` take a descr keyword arg that is a `lambda: varnamestr` that applies to all variables, and defaults to something reasonable, e.g. `lambda varnamestr: "W breakdown variable %s" % varnamestr`?
 - something else?

We could also require the user to create the `Variable` objects in advance, but might add more typing than we want here.

**Comment by mayork** [comment]
@whoburg 
not sure how to create a new branch but I'll look at the documentation and see if I can figure it out, if not I'll let you know

Currently, I have the variable description left as none. It seems like any of these would be easy enough to implement though. Do you think users will be using the LaTex print out much or just the diagram? It seems like the optimization portion of this is fairly trivial so the diagram might be the key output, in which case a generic description like weight break down variable or none would work

**Comment by whoburg** [comment]
To create a new branch from a clean master
```
git checkout -b new_branch_name
# (do your work, make your changes to files)
git status
git add (space-separated list of files that you have edited)
git commit -m "initial stab at weight breakdown code (or similar descriptive comment)"
git status
git push origin new_branch_name
```
if you have made changes locally (but not yet committed), you can stash them before switching branches:

```
git stash
git checkout -b new_branch_name
git stash pop
git status
```
... (and start the top set of instructions starting at `git add`)

**Comment by bqpd** [comment]
per design discussion, why not accept dictionaries? (Variable does.)

```{"W": {"W_pay": 100*units("lbf"), "W_fuel": None, "W_wing": {"W_spar": None, "W_skin": None, "W_sys": {"value": 100*units("N"), "descr": "System weight"}}}```

**Comment by whoburg** [comment]
Love it

**Comment by mayork** [comment]
I'll add that functionality in and then push what I have to a new branch later today or tomorrow

**Comment by bqpd** [comment]
Then you can just run ```python
# for key, value
if isinstance(value, dict):
descr = value
elif value:
descr = {"value": value}

variable = Variable(key, **descr)
```

**Comment by whoburg** [comment]
Actually shoot, dictionaries might be problematic as the base case, because the recursion will want to create a breakdown using the dict keys as variables.

Probably easy to fix with a simple flag, any ideas?

**Comment by mayork** [comment]
I'm not sure I understand @whoburg last comment but I'm currently using ordered dictionaries as the base case and that seems to work

**Comment by bqpd** [comment]
Oh good call. What about a list of args instead? Slightly hackier, but `[100, "N"  "System weight"]` is also a bit easier to read.

**Comment by bqpd** [comment]
@whoburg, @mayork: so if we did `type(value) == dict` we wouldn't pick up the OrderedDicts. Slightly non pythonic, but convenient.

**Comment by bqpd** [comment]
pseudocode:
```python
descr = {}  # auto generated description for other tools to use

if isinstance(value, dict):
    descr.update(value)
elif not value is None:
    descr["value"] = value

var = Variable(name, value)
```

**Comment by whoburg** [comment]
I'm confused by the last two comments

 - @bqpd are you suggesting that a `Breakdown` will need to be initialized with an ordered dict? I think that's too intrusive -- we should allow users to specify standard dicts like the examples we gave above, without importing `OrderedDict`.

 - pseudocode could use more explanation -- `value` and `name` are not defined, and it should be made clear that this pseudocode implements parsing the variable dicts, as opposed to being the full recursion for parsing the breakdown dicts.

**Comment by mayork** [comment]
I currently am initializing with an ordered dict...if it's initialized with just a dict wouldn't a list have to be input with the keys in the proper hierarchy?

**Comment by whoburg** [comment]
Sorry I must be really confused. I don't understand what's ordered here -- unless you're trying to allow the user to specify what order things occur in the weight breakdown figure -- but I think that should be optional, not required behavior.

I still think that
`Breakdown({"W": {"W_pay": 100*units("lbf"), "W_fuel": None, "W_wing": {"W_spar": None, "W_skin": None, "W_sys": 100*units("N")}}})`
should be a valid way to initialize. This fully captures the desired hierarchy.

The problem remains that if the final value in the recursion is a `Variable` kwarg dict, like `{"value": 100*units("N"), "descr": "System weight"}`, then the recursion will continue into that dict, which is not the intended behavior.

I'm ok with the list/tuple suggestion, where Variable args would be given as `[100, "N", "System weight"]`.

I don't really understand how OrderedDicts are relevant here.

Am I missing something fundamental?

**Comment by bqpd** [comment]
Naw @whoburg, you're right. I was assuming the user would create OrderedDicts to preserve their desired ordering, but if they input raw dicts as you specify (which makes sense and should be an option) then we run into the confusion.

**Comment by whoburg** [comment]
ok cool - in that case the plan I've heard so far is @bqpd's list/tuple suggestion, where Variable args would be given as `[100, "N", "System weight"]`. Of course, `None`, values like `5`, and Quantities like `10*gpkit.units("lbf")` would also be valid base case values.

**Comment by bqpd** [comment]
:+1:, though as noted above this has the flaw of not being easily extensible to nonstandard VarKey fields.

**Comment by mayork** [comment]
I think right now I'm having the problem of recursing too far into the dict input...what I'm confused on is how to access the variables during the recursion if just an ordinary dict is used because the key order won't be preserved, right?

**Comment by mayork** [comment]
sorry commented and then the page refreshed with new comments...so abandon dict and go with list/tuple?

**Comment by bqpd** [comment]
Yup, at least for now.

**Comment by mayork** [comment]
sounds good, I'll rework what I have

**Comment by mayork** [comment]
@whoburg just pushed initial class in a new branch. Wasn't sure how to use the built in automatic testing with this case so I also pushed a short testing script I wrote in case anyone wanted to mess around with the code. 

I got up to the point of getting values for all the variables from the solver, I have no idea where to start on generating the actual diagrams...@bqpd thoughts?

**Comment by bqpd** [comment]
Whoa, can we get it to look like @whoburg's original references? :D

**Comment by bqpd** [comment]
Closing this issue because the PR seems a better discussion thread for feature-requests like this
