### ISSUE TITLE
old version of GPkit on PyPI? (t_issue476)

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#512]
A user attempting to install reports,

"I'm attaching a screenshot of the error. I have uninstalled and reinstalled python(x,y) a couple of times and get the same error. "

![python](https://cloud.githubusercontent.com/assets/6042395/12848041/55ec8a04-cbe5-11e5-9cf7-e3c421eff49a.JPG)

**Comment by whoburg** [comment]
The `Could not load settings file.` is concerning -- this seems similar to what @mayork experienced.

**Comment by whoburg** [comment]
This is high priority.

**Comment by mayork** [comment]
I got a could not load settings file error but it was not accompanied by the import error. Are they getting the message from the python xy installer that there is already a version of python installed on their machine?

**Comment by whoburg** [comment]
tracked down the setting file (first line of error dump) by running `gpkit.build.build_gpkit()`. Still vexed that this needs to be done. but still have the t_issue476 error

**Comment by whoburg** [comment]
how is the line of code `from gpkit.tests import t_issue476` getting run!?!? I don't think that's part of gpkit anymore.

Does pip have some super old version it's trying to install for windows?

**Comment by bqpd** [comment]
Hmm, maybe, but that really shouldn't happen.

**Comment by whoburg** [comment]
The work-around for this issue is to clone the gpkit repo and then run `python setup.py install`. Confirmed to work for OP.

@bqpd, if we can't fix this in the near future, I think we should modify http://gpkit.readthedocs.org/en/latest/installation.html#updating-gpkit-between-releases so that it suggests running `python setup.py install` instead of `pip install` for windows users (or for all users, if it's easier).

**Comment by bqpd** [comment]
Will do. So python xy installs a systemwide `'python` command?

**Comment by whoburg** [comment]
I now have some in-person experience dealing with the `Could not load settings file.` message on multiple people's computers -- this seems to occur for every fresh windows install.

The workaround I use is:
1. start ipython
2. `import gpkit` (results in "Could not load settings file." message)
3. Check the value of `gpkit.__file__`
4. cd into the directory containing `gpkit.__file__`.
5. Run `import gpkit.build; gpkit.build.build_gpkit()`
6. Test install. Has worked in every case so far.

The key step seems to be navigating to the directory containing `gpkit.__file__` before running the build script. @bqpd: if there is not a better way, could you update the docs to reflect the above? We'll be doing about 5 new windows installations tomorrow for another group of users so this is high priority.

Have not seen the t_issue476 crop up again -- appears to be isolated to one user. Re: what type of `python` python xy installs, not sure, and don't have a windows machine to test.

**Comment by bqpd** [comment]
re: `t_issue476`, phew

**Comment by whoburg** [comment]
I changed the title to make this focused on the t_issue476 problem. #509 captures the Could not load settings issue.

**Comment by whoburg** [comment]
I just noticed that I have a `t_issue476.pyc` in my `gpkit/tests/` dir. Wondered if it might be relevant to this issue.

**Comment by bqpd** [comment]
Huh. I imagine it could.

**Comment by bqpd** [comment]
This hasn't happened since February, I'm inclined to close this issue until it reoccurs.
