### ISSUE TITLE
Constraint tightness checking

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#516]
Currently a number of my SP models have a few lines of code at the bottom that check to see if certain key signomial constraints are tight and return an error if they aren't (using `numpy testing`). Given that the refactor will have keys for constraints, making constraint tightness checking (for all types of constraints) seems like it will become much easier. This would be a sweet feature that could help clean up code and provide useful information to a modeller.

**Comment by bqpd** [comment]
Yeah! Actually, it'd be super easy to write a TightConstraintSet class that checks this kinda of thing for all its base inequalities.

**Comment by whoburg** [comment]
(or make it a kwarg of `ConstraintSet.__init__`)?

**Comment by bqpd** [comment]
Isn't optional functionality is what subclasses are for? :p Converting an existing ConstraintSet to a TightConstraintSet would be easy: `TightConstraintSet(cs)`

**Comment by whoburg** [comment]
yeah makes sense and agreed it's a good use of subclasses. I was just wondering whether we might have lots of different post-solve checks we might want to do, one of which is tightness checking -- if we had 10 such checks inheritance would start to feel unwieldy.

**Comment by bqpd** [comment]
@pgkirsch, let's sit down sometime and write this in the refactor.

**Comment by pgkirsch** [comment]
Sounds good. I am free now until 6 or all day tomorrow.

**Comment by bqpd** [comment]
@pgkirsch did this happen in #591 to your satisfaction?
