### ISSUE TITLE
mention minimum pip version in documentation

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#517]
As reported by @galbramc: I noticed the gpkit install does not work with pip 7, but it works with pip 8. 

You might want to mention the minimum required version of pip in your documentation (unless this is not intentional).

**Comment by bqpd** [comment]
It's working with pip 7 on my computer.

**Comment by galbramc** [comment]
I could have been mistaken. This was in the process of trying to get gpfit
to work. Try creating a virtualenv, installing gpkit, and then running the
tests from gpfit. If it works with pip 7, then it was something else that
got fixed.

**Comment by bqpd** [comment]
Yeah, works here.

**Comment by galbramc** [comment]
Now what do you mean by works... because it does't actually work on any system according to the gpkit_Install testing

**Comment by bqpd** [comment]
gpfit tests run on my linux computer using pip 7, was what I meant to say.

**Comment by galbramc** [comment]
ahh ok, I must have been working through other problems when I though it was a 7 vs 8 issue

**Comment by whoburg** [comment]
Plan for this issue: leave it open until #509 is resolved, then confirm that clean install works on fresh virtualenv with pip 7.

**Comment by bqpd** [comment]
(it does)
