### ISSUE TITLE
feasibility example from docs does not run

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#520]
The feasibility example at http://gpkit.readthedocs.org/en/latest/advancedcommands.html#feasibility-analysis does not currently run. The error below comes from the uneven division `PosyArray(m.signomials)/feas["constraints"]`

current output:

``` python
ValueError                                Traceback (most recent call last)
<ipython-input-7-edeafb6f1253> in <module>()
     13 # USING CONSTRAINTS
     14 m = Model(x, [x <= x_max, x >= x_min])
---> 15 m.constraints = PosyArray(m.signomials)/feas["constraints"]
     16 m.solve()
     17 

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

```

**Comment by whoburg** [comment]
- [ ] Let's also make sure the `docs/` feasibility example(s), like this one, get run as part of unit tests, and
 - [ ] unit test feasibility_model with flavour="constants", as suggested by @galbramc due to a recent coverage report.

**Comment by galbramc** [comment]
So I can easily run the files docs/source/examples/*.py, but how do I execute the examples in docs/source/advancedcommands.rst?

**Comment by bqpd** [comment]
superseded / closed by the new feasibility models

**Comment by whoburg** [comment]
The feasibility docs are still out of date and not run as part of the unit tests.

**Comment by bqpd** [comment]
They're run as part of the unit tests in the relevant PR...

**Comment by whoburg** [comment]
👍
