### ISSUE TITLE
Should be able to substitute initial values for a subset of variables in SP solve

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#524]
Currently, the initialization dict, `x0` requires all or nothing to work. It seems like it would be a fairly easy fix to allow only some variables to have explicitly specified initial values (everything else still defaults to 1/some automatically chosen value).

**Comment by bqpd** [comment]
@pgkirsch I think this got fixed, right?

**Comment by pgkirsch** [comment]
Yup, closed with #529
