### ISSUE TITLE
GP not simplified post-substitution

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#525]
Here is a simple GP (the fact that it has unbounded variables is irrelevant for this issue):

```python
from gpkit import Variable, Model

D  = Variable('D')
mi = Variable('m_i')
V  = Variable('V', 1)

m = Model(D + V,
          [V >= mi + 0.4])
#sol = m.solve("mosek")
print m.gp().A.todense()
print m.gp().varlocs
```
The output from the print statements above is:
```
D has no lower bound
m_i has no lower bound
[[0 0]
 [0 1]
 [0 0]
 [1 0]]
D has no lower bound
m_i has no lower bound
{m_i: [3], D: [1]}
```

Note that the `value` of `V` is `1`. Here is the same GP with `1` manually substituted for `V`:
```python
from gpkit import Variable, Model

D  = Variable('D')
mi = Variable('m_i')
V  = Variable('V', 1)

m = Model(D + 1,
          [1 >= mi + 0.4])
#sol = m.solve("mosek")
print m.gp().A.todense()
print m.gp().varlocs
```
But... the output from the print statements is now completely different:
```
D has no lower bound
m_i has no lower bound
[[0 0]
 [0 1]
 [1 0]]
D has no lower bound
m_i has no lower bound
{m_i: [2], D: [1]}
```
The fact that gpkit's substitution fails to produce the same result as a manual substitution means that the solver is passed a different problem. Indeed for the MWE's above, mosek returns `UNKNOWN` for the first (`V` has value=1) version, and has an issue #361 error for the second (manually-substituted) version.

**Comment by whoburg** [comment]
This is a priority -- I'm suspicious of this potentially contributing to other GP solver errors. Tracking it down would eliminate that ambiguity.

**Comment by bqpd** [comment]
The posynomial `0.4 + m_i` is getting turned into the mononomial `1.67*m_i` ???

**Comment by bqpd** [comment]
Oh lol, it's that optimization we do in `<=`: `0.4 + m_i <= 1` is getting transformed into `m_i <= 1 - 0.4` by a helpful gpkit.

**Comment by whoburg** [comment]
Hmm. I think the behavior for the two problems above should be the same. As a user, I'm expecting substitution to have the same behavior as substituting myself, and the fact that the solver behaves differently is especially unexpected.

I think we should either never do the simplification (including in `>=` and `<=`), or we should always do it (including post-substitution).

My vote is that we should always do it, but I'm open to discussion.

**Comment by bqpd** [comment]
I think we should always do it too, but that's only really feasible in the refactor. Quick fix here in master, if you need one, is to never do it.

**Comment by bqpd** [comment]
Working on this over on PR #580
