### ISSUE TITLE
unexpected exp overflow

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#526]
The following problem is dual-infeasible:
```python
from gpkit import Variable, Model
import numpy as np

CL = Variable("CL")
CD = Variable("CD")
V = Variable("V", "m/s", "cruise speed")
W = Variable("W", 200, "lbf", "weight")
rho = Variable(r"\rho", 1.2, "kg/m^3", "air density")
S = Variable("S", 190, "ft^2", "wing area")
m = Model(V*(W/(CL/CD)),
          [0.5*rho*CL*S*V**2 >= W,
           CL**1.51/CD <= 20])
sol = m.solve("mosek")
```
Mosek indeed returns a `DUAL_INFEAS_CER`. Surprisingly though, running the code above results in an overflow error,
```
gpkit/geometric_program.py:156: RuntimeWarning: overflow encountered in exp
  np.exp(primal)))
```
It seems to me that we should not be taking the `exp` of the primal solution if the solver returns `DUAL_INFEAS_CER`.

We should track this down and fix it to make sure it's not representative of a bigger issue.

**Comment by bqpd** [comment]
Oh, this is just that we don't check solver status before calling `exp`
