### ISSUE TITLE
newest version of pint breaks unit tests

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#544]
upgrading pint causes unit tests to fail as discovered by @galbramc

**Comment by bqpd** [comment]
It looks like it changes some property that used to be a Quantity to being a Unit. Sigh.

**Comment by whoburg** [comment]
@hgrecco we would respectfully welcome any high-level advice/input you might have

**Comment by hgrecco** [comment]
One breaking change is that `ureg.meter` now yields the `Unit`, not the Quantity`. Use `1. * ureg.meter` to get a quantity.

But if you provide the output of the tests I will be happy to give you better feedback.

**Comment by bqpd** [comment]
That seems like it's probably the issue, thanks!

**Comment by whoburg** [comment]
currently sitting with a new user who has failing unit tests due to this issue and a new install of pint. this is a huge priority.

**Comment by bqpd** [comment]
40m ahead of you (phew)
