### ISSUE TITLE
unit test errors with numpy 1.7

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#546]
Thanks to @galbramc's nightly CI setup, we now know that our unit tests fail on an old version of numpy (1.7.2). The errors are all of two types: unsupported operand type for PosyArray, and missing np.full -- like this:

```python
======================================================================
ERROR [0.001s]: test_vector (gpkit.tests.t_sub.TestNomialSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 73, in test_vector
    self.assertTrue(all(p.sub({x: 1, "y": 2}) == 2*z))
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'

======================================================================
ERROR [0.008s]: test_vector_init (gpkit.tests.t_sub.TestGPSubs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gpkit/tests/t_sub.py", line 147, in test_vector_init
    sol = m.solve(verbosity=0)
  File "gpkit/model.py", line 344, in solve
    *args, **kwargs)
  File "gpkit/model.py", line 503, in _solve
    solution.append(parse_result(result, constants, beforesubs))
  File "gpkit/solution_array.py", line 355, in parse_result
    vardict[veckey] = np.full(var.descr["shape"], np.nan)
AttributeError: 'module' object has no attribute 'full'
```

Do we care? If it's not an easy fix, we just say we're compatible with numpy version >= 1.8

**Comment by bqpd** [comment]
Fixed in refactor.

**Comment by galbramc** [comment]
Is this fixed in #493?

**Comment by bqpd** [comment]
Yup!

**Comment by galbramc** [comment]
How old do you want to go in regards to supporting numpy?

**Comment by bqpd** [comment]
Oh, wait, maybe not. I think we still use `full`.

**Comment by galbramc** [comment]
Yeah: https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/buildnode=macys,numpyversion=1.7.2,pintversion=0.7.2/183/console

**Comment by bqpd** [comment]
Ubuntu 12.04 has numpy 1.8, so I'm okay not supporting back to 1.7.

**Comment by bqpd** [comment]
We just need to add the requirements flag in `setup.py`

**Comment by galbramc** [comment]
Sure. It would be good to include in your documentation as well.

**Comment by whoburg** [comment]
If we care, it looks like we could achieve backwards compatibility by using `np.empty()` followed by `np.fill()`.
http://stackoverflow.com/questions/5891410/numpy-array-initialization-fill-with-identical-values
I'm somewhat against this though, because it seems that `full` is the 'right' way.

**Comment by bqpd** [comment]
Agreed!

**Comment by whoburg** [comment]
version requirement documented in #636
