### ISSUE TITLE
unit rendering in latex

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#561]
Latex for units should use `\textnormal` or similar to keep them from being printed in italics math. Here's an example screenshot from a solution table produced with `SolutionArray.table(latex=True)`.

![screen shot 2016-03-09 at 4 48 08 pm](https://cloud.githubusercontent.com/assets/6042395/13651793/e9cfe00e-e616-11e5-9c98-5bd54a3a333c.png)

**Comment by bqpd** [comment]
It uses mathrm now, I believe.
