### ISSUE TITLE
solution table: combine constants and sensitivities

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#562]
Let's make the default printing option for `SolutionArray.table` print a single table containing both constant values and constant sensitivities, ordered by sensitivity value. Otherwise, printing the two separate tables results in a lot of repeated information.

We can retain the separate tables as options in case anyone needs them, but remove them from the list of default tables to be printed.

**Comment by bqpd** [comment]
Ooh, I like that! Values and sensitivites as different columns?

**Comment by whoburg** [comment]
yep

**Comment by bqpd** [comment]
fixed, though not followed directly, by the `.summary()` method
