### ISSUE TITLE
freeing fixed variables

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#563]
Is it possible to "free" a variable in an existing model, such that its `value` is removed, and the corresponding model, when solved, treats that variable as a free variable?

In an existing model `m`, I tried `m["C_L"].key.descr.pop("value")`, but it doesn't actually remove the value from the descr. I also don't know if other changes would be needed to `Model` to implement this robustly.

... or maybe there's a much smarter way to accomplish converting fixed variables in an existing model to free variables?

**Comment by bqpd** [comment]
In the refactor, you can just remove it from the substitutions dict. :) All values have already been incorporated into it.

**Comment by bqpd** [comment]
This should be a test!

**Comment by bqpd** [comment]
This works, just needs to be tested and documented.

**Comment by bqpd** [comment]
It's used in the new primal feasibility models, so just needs to be documented.

**Comment by whoburg** [comment]
this is nitpicky, but I think this also deserves a unit test beyond the indirect test as part of primal feasibility models (whose implementation may change in the future)

**Comment by bqpd** [comment]
Also, my bad, it's actually not used in the new feasibility models but should be.

**Comment by bqpd** [comment]
actually, my bad, it is.

**Comment by whoburg** [comment]
is this unit tested somewhere? I don't consider the issue closed until it is.

**Comment by bqpd** [comment]
It's implicitly tested everywhere we use RelaxConstants...

**Comment by whoburg** [comment]
I still feel that this functionality would benefit from a focused unit test. This would document exactly what we expect to work (as a user, I don't currently know how to use this feature).

**Comment by bqpd** [comment]
We test this in t_model/test_cost_freeing

**Comment by bqpd** [comment]
It's also in the docs at https://gpkit.readthedocs.io/en/latest/advancedcommands.html#freeing-fixed-variables
