### ISSUE TITLE
vector sol lookup taking too long

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#567]
`TestSolutionArray.test_call_time` fails sporadically on Macys ElCap Jenkins machine.

Should not take > 0.05 seconds to look up a 20 element VectorVariable in a SolutionArray.

**Comment by galbramc** [comment]
Macys ElCap is a virtual machine running on Macys which is an actual machine. I could see the VM getting bogged down if macys is swamped with other jobs. What kind of timings do you see otherwise on other machines?

**Comment by galbramc** [comment]
This does seem to be consistently happening with numpy 1.10.4 (when it does happen). It's hard to say if that has anything to do with numpy 1.10.4, or the order which jenkins processes the jobs.

**Comment by bqpd** [comment]
I haven't seen this recently, is it fixed?

**Comment by galbramc** [comment]
Happened today. https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/171/buildnode=macys_ElCap,numpyversion=1.10.4,pintversion=0.7.2/

**Comment by bqpd** [comment]
Ah well.

**Comment by galbramc** [comment]
You are getting bit by this one quite a lot actually. Happened again for gpkit_Push_Depends, [see](https://acdl.mit.edu/csi/job/gpkit_Push_Depends/buildnode=macys,numpyversion=1.9.3,pintversion=0.7.2/20/testReport/junit/gpkit.tests.t_solution_array/TestSolutionArray/test_call_time/)

**Comment by whoburg** [comment]
Seems we are failing by quite a bit when we fail, last one was `AssertionError: 0.11090207099914551 not less than 0.05`

**Comment by bqpd** [comment]
This variance seems suspicious.

**Comment by bqpd** [comment]
todo: profile to check this isn't just our VM losing access to hardware for 0.1s

**Comment by galbramc** [comment]
it has happened both on macys and the VM. I don't know where it has happened most often though.

**Comment by bqpd** [comment]
Have we seen this recently?

**Comment by bqpd** [comment]
I see this every so often, but I really don't think it's our fault.

**Comment by galbramc** [comment]
Yeah, timings are tricky. It's possible that something else is just running at the same time causing the slow lookup, but it's really hard to tell.

**Comment by whoburg** [comment]
just ran the test a few times locally on my machine and the timings (the number being compared to 0.05 in the test) were:

```
0.000587940216064
0.000659942626953
0.000571966171265
0.000585079193115
0.000595092773438
0.000638008117676
0.000574827194214
```

So, I'm warming to the hypothesis that this is some strange testing framework / VM artifact. Anyone have ideas for another way to make sure this never slows down in the future? (it was once noticeably slow, causing us to write the test)

**Comment by galbramc** [comment]
Run the test twice to measure the O(n log(n)) (I'm assuming) expected time of the test. Measure the time of some other calculation to use as the reference time in the assertion. Those are the only two I am aware of.

**Comment by bqpd** [comment]
We haven't seen this for months.

**Comment by whoburg** [comment]
just happened again: https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/916/buildnode=macys,numpyversion=1.9.3,pintversion=0.6/

maybe the next thing to try is rewriting the test to measure (in quick succession) how the time scales for two different sizes of the array as suggested by @galbramc?

**Comment by bqpd** [comment]
Sounds great!

**Comment by whoburg** [comment]
happened again in https://acdl.mit.edu/csi/job/gpkit_Push_Depends/buildnode=macys,numpyversion=1.11.1,pintversion=0.6/164/

**Comment by bqpd** [comment]
since this should actually be `O(1)`, I think we should test this another way, or not at all.

**Comment by galbramc** [comment]
Happened again https://acdl.mit.edu/csi/job/gpkit_PullRequest_Depends/buildnode=macys,numpyversion=1.11.2,pintversion=0.6/1068/. 

If the operation is ```O(1)```, then you should be able to test the time, double the size, and check that you get the same time again (within some tolerance).

**Comment by bqpd** [comment]
Good plan.
