### ISSUE TITLE
apply constraint.subinplace to substitutions

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#585]
As it stands, substitutions may get stranded during a varkey/varkey substitution.

**Comment by bqpd** [comment]
Move to Middle Release because it's not totally clear this is the right thing to do.

**Comment by bqpd** [comment]
Update: pretty clear this is the right thing to do, should be part of the "speedup KeyDict" refactor

**Comment by whoburg** [comment]
reopening due to 6965ee04b90cb41a08e67ff9fd6466889d10967e
