### ISSUE TITLE
Coupled aircraft model returns UNKNOWN after commit 19e1d714

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#596]
My full aircraft model worked (really well) at 19e1d714, but does not work for any of the commits on master since then (it now returns UNKNOWN - the unbounded (1432) flavour). Any ideas what should have caused a unit test to fail but didn't?

See GPjet master (gpjet/aircraft/aircraft.py) for code.

**Comment by pgkirsch** [comment]
Found the culprit.

The following change made in `GeometricProgram.__init__`:

```
 -            constraint.substitutions.update(self.substitutions)
 +            constraint.substitutions = self.substitutions
```

Reverting this change makes my model work again.

@bqpd it looks like that change was made to fix a "united cost" issue. Is there another fix? Also shouldn't this kind of change have caused a unit test to fail?

**Comment by bqpd** [comment]
Oh gosh. That was actually a pretty important change. I'll need to dig into aircraft to see why it needs this.

**Comment by whoburg** [comment]
is this related to #585?

**Comment by bqpd** [comment]
Quite possibly.

**Comment by bqpd** [comment]
Doesn't solve for me at that commit; are you on the `master` branch of GPjet?

**Comment by bqpd** [comment]
Cannot reproduce :(

**Comment by pgkirsch** [comment]
Hmm it's still a problem with me. Latest `gpjet/master` and latest `gpkit/master`.

**Comment by pgkirsch** [comment]
And MOSEK

**Comment by bqpd** [comment]
Yeah, it doesn't solve for me there or at 19e1d714. :/

**Comment by pgkirsch** [comment]
Oh, but replace the line above and it should work

**Comment by bqpd** [comment]
I wish it were so!

**Comment by whoburg** [comment]
hmm, I'm very confused. Trying to reproduce, but I can't get the solver to switch to mosek. I'm running the latest commit on GPjet/master, having changed line 69 of the test method to call `sol = self.localsolve(solver="mosek", x0=self.init)`, and getting

```
In [1]: %run gpjet/aircraft/aircraft.py
D_{vis}_VerticalTail has no upper bound
D_Fuselage has no upper bound
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
/Users/whoburg/MIT/dev/GPjet/gpjet/aircraft/aircraft.py in <module>()
     70
     71 if __name__ == "__main__":
---> 72     a = Aircraft()
     73     a.test()
     74

/Users/whoburg/MIT/dev/GPjet/gpjet/aircraft/aircraft.py in __init__(self)
     52                                        'x_{CG}': 15
     53                                       })
---> 54             vtfu_sol = vtfu.localsolve(verbosity=0)
     55             vtfu.substitutions.clear()
     56

/Users/whoburg/MIT/dev/gpkit/gpkit/constraints/prog_factories.pyc in solvefn(self, solver, verbosity, skipsweepfailures, *args, **kwargs)
     78         else:
     79             self.program, solvefn = genfunction(self, verbosity-1)
---> 80             result = solvefn(solver, verbosity-1, *args, **kwargs)
     81             solution.append(result)
     82         solution.program = self.program

/Users/whoburg/MIT/dev/gpkit/gpkit/constraints/signomial_program.pyc in localsolve(self, solver, verbosity, x0, rel_tol, iteration_limit, **kwargs)
    110                 nearest_feasible = feasibility_model(gp, "max")
    111                 self.gps.append(nearest_feasible)
--> 112                 result = nearest_feasible.solve(verbosity=verbosity-1)
    113                 result["cost"] = None
    114             x0 = result["variables"]

/Users/whoburg/MIT/dev/gpkit/gpkit/geometric_program.pyc in solve(self, solver, verbosity, *args, **kwargs)
    188                 " If the problem was Primal Infeasible, you can generate a"
    189                 " feasibility-finding relaxation with model.feasibility()." %
--> 190                 (solvername, solver_out.get("status", None)))
    191
    192         result = self._compile_result(solver_out)

RuntimeWarning: final status of solver 'cvxopt' was 'unknown', not 'optimal'.

The infeasible solve's result is stored in model.program.solver_out. A result dict can be generated  via program._compile_result(program.solver_out). If the problem was Primal Infeasible, you can generate a feasibility-finding relaxation with model.feasibility().
```

**Comment by whoburg** [comment]
is it because `nearest_feasible.solve` does not take in a solver argument?

**Comment by bqpd** [comment]
Hmm, maybe!

**Comment by whoburg** [comment]
@bqpd, possibly the cause of the aircraft model not working -- still trying to do feasible solves with cvxopt?

**Comment by pgkirsch** [comment]
Is there something that I can do to help this get fixed? I permanently have the proposed fix in my code, which is probably not ideal, but it's necessary if I want my models to solve.

**Comment by bqpd** [comment]
Oops, yup, if the proposed fix works I'll implement it right away. Sorry for being slow on this one!

**Comment by pgkirsch** [comment]
No worries! It sounded like there was an important reason for the change you made though. Is that no longer an issue?

**Comment by bqpd** [comment]
Oh, shoot, nvm. I was thinking woody's issue had fixed yours, but you only have MOSEK installed. :-/

**Comment by pgkirsch** [comment]
Somewhere down the road this issue was resolved. The line that was the problem is unchanged, so the mystery continues. In the meantime, this issue can be closed.
