### ISSUE TITLE
Raising Variables to Substituted Variables

### ISSUE THREAD

**Issue by cjk12** [hoburg/gpkit#597]
It would be nice if this worked:
```python
from gpkit import Variable, Model, units
import gpkit

mwx = Variable("mwx", 1, "-", "Maximum Takeoff Weight Weighting Exponent")
MTOW = Variable("W_{MTO}", "-", "Maximum Takeoff Weight")

constraints = [MTOW >= 10]
objective = MTOW**mwx

m = Model(objective, constraints)
sol = m.solve('cvxopt', verbosity=1)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-6a678a48de69> in <module>()
      6 
      7 constraints = [MTOW >= 10]
----> 8 objective = MTOW**mwx
      9 
     10 m = Model(objective, constraints)

TypeError: unsupported operand type(s) for ** or pow(): 'Variable' and 'Variable'
```

So that I could sweep over the exponent in `controlpanel`...

**Comment by bqpd** [comment]
Ooh, interesting example. I don't think that's best done with a Variable,
though? But this is definitely a use case that comes up. @whoburg?

**Comment by whoburg** [comment]
I'm noticing a lot of cases where users want to play with the objective after model creation (this is one example; another is flipping back and forth between MTOW and 1/endurance).

I don't think we should allow a `gpkit.Variable` to be used as an exponent. One problem is that it's not clear what to do with units. (note that the units of the objective change every time `mwx` is changed in the example above -- this is excusable for an objective, but probably not so in constraints).

So, my reaction is that we could handle this in controlpanel by allowing for sliders that aren't `Variable`s in the model. @bqpd, do we already have a related issue with linkedsweeps? Another related issue might be feasibility models with varying exponents on the slack variables.

**Comment by bqpd** [comment]
Yeah, hooks for custom controlpanel sliders is probably good. I don't think we have a related issue with linkedsweeps?

In general, changing the cost function is a great thing for a user to be doing and we should definitely encourage it more than we do at present.

**Comment by whoburg** [comment]
agree with that.

**Comment by bqpd** [comment]
superseded by #825
