### ISSUE TITLE
gpkit.constraints not importing

### ISSUE THREAD

**Issue by cjk12** [hoburg/gpkit#598]
`from gpkit.constraints import ConstraintSet`

yields:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-510a93c96677> in <module>()
----> 1 from gpkit.constraints import ConstraintSet

ImportError: No module named constraints
```

similarly for `gpkit.constraint`

**Comment by cjk12** [comment]
There is definitely a `constraints` folder in the gpkit directory, but I'm not sure why it isn't importing...

**Comment by bqpd** [comment]
Yeah, sorry, the correct thing to use is `gpkit.constraints.set`. We'll making a user-facing ConstraintSet that's easier to access soon.

**Comment by cjk12** [comment]
```python
from gpkit.constraints.set import ConstraintSet
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-fb182660d70a> in <module>()
----> 1 from gpkit.constraints.set import ConstraintSet

ImportError: No module named constraints.set
```

**Comment by cjk12** [comment]
Also @whoburg I can't reopen this issue.  Not sure why.

**Comment by bqpd** [comment]
Huh, that should definitely work...

**Comment by cjk12** [comment]
In case it matters, the word `set` has turned green, as if it were a keyword for something...

**Comment by cjk12** [comment]
I can see the file you are pointing me to, but for some reason, it seems like the `__init__.py` file isn't loading the constraints package?  It's like the folder doesn't exist.

**Comment by cjk12** [comment]
This is from my terminal now:
```python
from gpkit.constraints.set import ConstraintSet
```
```
Could not load settings file.
```

Pretty sure `set` is a keyword that my computer is trying to perform...

**Comment by cjk12** [comment]
Nope, changed the name and that didn't work, so I have no idea...

**Comment by bqpd** [comment]
Hmm, I think that's probably not the issue. Your gpkit doesn't seem to be
finding its settings file, though, which is disconcerting...

**Comment by cjk12** [comment]
I'll try another clean install...  That generally fixes my issues.

**Comment by cjk12** [comment]
Works now with a clean install...  I have no idea.
