### ISSUE TITLE
equality constraints with no variables

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#601]
This is a carry-over from a behavior noticed by @pgkirsch in https://github.com/hoburg/gpkit-models/pull/45. MWE:

```python
from gpkit import Variable, Model
x = Variable("x")
y = Variable("y", 2)
m = Model(x,
          [x >= 1,
           y == 2])
m.solve()
```
Note that after substitution, the second constraint becomes `2 == 2`. This currently results in a `ValueError: infeasible constraint: constant term too large.`.

This is confusing because the constraint is actually feasible. Can we raise a more informative error?

**Comment by bqpd** [comment]
Line 442 of `nomial_math.py` has a `<=` constraint, which is what's causing this error. We could
  
1. Raise a separate error on always-satisfied constraints.
2. Return the constraint `1 <= 1`

**Comment by whoburg** [comment]
I vote for raising the separate error for now. It's incorrect to say the constraint is infeasible, but I do think we should raise the error to inform the user that their model includes an always-satisfied constraint.

**Comment by bqpd** [comment]
Fixed in PR

**Comment by whoburg** [comment]
hmm, after merging #604, the behavior on the original example is that it solves fine. Is that expected? Should it instead raise the tautological constraint error?

**Comment by bqpd** [comment]
Do we want it to? Currently monomial ineqs are not simplified, and so don't raise that error. From your original post I thought that we wanted this to solve...

**Comment by bqpd** [comment]
Oops, my bad. Simplify isn't called for monomials, and I only tested posynomials. Will add a new test and PR.

**Comment by bqpd** [comment]
@whoburg is satisfied

**Comment by whoburg** [comment]
the original example does not run after merging #640. Needs a fix and a unit test.

**Comment by whoburg** [comment]
(I suppose one could argue about whether this should raise an error because `y` only appears in tautological constraints, vs whether it should run. I'm happy to hear opinions on the issue.)

**Comment by bqpd** [comment]
@whoburg, Made a new PR to address this, ready to review.
