### ISSUE TITLE
Checking whether a substitution key is actually in varkeys

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#609]
There have been a couple times now where I add a key:value pair to my substitution dict, but I accidentally misspell the varkey or forget an underscore or something, and then the problem solves (without the substitution I want) and I go on, blissfully unaware. One (hopefully easy) check that might be nice and would help to avoid silly user mistakes is something that ensures that all of your substitution keys are actually valid varkeys.

**Comment by bqpd** [comment]
Yeah! This could happen on solve? I think this is pretty high priority...

**Comment by bqpd** [comment]
Also, how about printing a notice instead of raising an error?

**Comment by whoburg** [comment]
agreed, and I don't have an opinion on printing vs raising yet -- happy for @bqpd to implement one and see how modelers like it.
