### ISSUE TITLE
Widget Example

### ISSUE THREAD

**Issue by cjk12** [hoburg/gpkit#612]
So perhaps a little off topic, but is there an example of a GP using a ipython widget?  I want to plot an airfoil shape in real time as I vary one of the geometry sliders...  The documentation appears to be somewhat behind on many of the new features.

**Comment by bqpd** [comment]
Yeah. If you have a function that produces the output you want, you just pass it as an argument: `controlpanel(fn_of_sol=your_function)`

Also check out http://nbviewer.jupyter.org/github/convexopt/gpkit/blob/master/docs/source/ipynb/Fuel/Fuel.ipynb and the recent https://github.com/hoburg/gpkit/pull/523.

**Comment by bqpd** [comment]
superseded by #643
