### ISSUE TITLE
solution table printing error

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#621]
This error can be reproduced at the 95bc8b4c8a9dc7fddbdeedd4b43a3cc28097651e commit of gpkit-models (currently on the `atmosphere` branch, will be merged to master soon)

```python
from atmosphere import Sutherland
SU = Sutherland()
SU.substitutions.update({"T": 288})
SU.solve()
```

This can be worked-around by changing `"T"` to `SU["T"]`, but I don't think that's obvious to users, so we should make the original example just work.

**Comment by bqpd** [comment]
Oh, hmm. Accidentally pushed the fix for this straight to master. D:

**Comment by whoburg** [comment]
confirmed fixed.
