### ISSUE TITLE
Is it not possible to create linked sweeps without using a function?

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#625]
I would like to create a linked sweep where A1 and B1 are corresponding values etc. 

Example syntax:
```python
x = Variable('x')
y = Variable('y')
..... 
.....
substitutions = {'x': ('sweep', [A1, A2, A3]), 
                 'y': ('sweep', [B1, B2, B3])}
```
Is something like this possible?

**Comment by bqpd** [comment]
Yeah, it's not currently possible to create linked sweeps without using a function. Try:

```python
x = Variable('x')
y = Variable('y')
..... 
.....
Bmap = {A1: B1, A2: B2, A3: B3}
substitutions = {'x': ('sweep', [A1, A2, A3]), 
                 'y': ('sweep', lambda A: Bmap[A], args=[x]}
```

**Comment by pgkirsch** [comment]
Ah neat, thanks! If this works, fixing #624 isn't a high priority anymore

**Comment by bqpd** [comment]
Should work! Also respondded to #624 with a way to do that.

**Comment by pgkirsch** [comment]
It works great, thanks!
