### ISSUE TITLE
Solving took 5 GP solves and 53.5 seconds.

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#645]
gulp

**Comment by bqpd** [comment]
hehehe. Not sure if I hope it's spending that time in GPkit or in the solver.

**Comment by pgkirsch** [comment]
The current version of `aircraft.py` takes a long time to solve and I'm not sure why.

**Comment by pgkirsch** [comment]
Even just combining the vertical tail and fuselage and solving takes 24 seconds

**Comment by bqpd** [comment]
:sob:

**Comment by whoburg** [comment]
Also having slowness issues over on the 1682 model after switching to `ConstraintSet`s -- see the `gas_male/gas_male_interactive.ipynb` on the `1682master` branch. The sweep in one of the last few cells takes several minutes, i.e. unacceptably long -- @bqpd could you take a look at a profile of this asap and see if anything obvious pops up? The change is pretty dramatic / basically unusable.

**Comment by bqpd** [comment]
What is the change? Is this since the refactor, or some more recent change?

**Comment by whoburg** [comment]
This was only recently switched to individual constraint sets instead of one giant Model, so not sure whether the change corresponded with the refactor or whether it came later.

**Comment by pgkirsch** [comment]
Any chance of progress on this ticket? It seems like a fairly high priority issue.

**Comment by whoburg** [comment]
yes - this is high priority.

**Comment by pgkirsch** [comment]
Latest aircraft model: 188 seconds

**Comment by pgkirsch** [comment]
@bqpd You probably already knew this, but the bottleneck seems to be with result packing. For each GP solve, result packing consistently takes > 20 seconds.

(Latest aircraft model: 3 minutes 40 seconds)

**Comment by bqpd** [comment]
Is this partially fixed by #680?

**Comment by pgkirsch** [comment]
@bqpd you are a wizard

**Comment by pgkirsch** [comment]
351 seconds --> 3.54 seconds

354 unique variables

**Comment by bqpd** [comment]
Great. Most of the speedups can be merged directly.

@pgkirsch you're a wizard too, but I'm afraid it's black magic...I've got another branch with even more speedups which passes all the unit tests but, once again, can't run `aircraft.py`.

**Comment by pgkirsch** [comment]
Huh...weird `profilin_better` is actually slower for me.

**Comment by bqpd** [comment]
Yeah, it should be. How much?

**Comment by pgkirsch** [comment]
only ~1 second

**Comment by bqpd** [comment]
Yeah, it removes the hackier fixes. I'm working on a less-hacky version
that's faster but doesn't work for aircraft yet.
