### ISSUE TITLE
Documentation for installing gpkit does not include "pint"

### ISSUE THREAD

**Issue by mopg** [hoburg/gpkit#646]
Under "3. Install GPkit", it does not say to run `pip install pint`, while it does for Windows.

Thanks to @pgkirsch

**Comment by whoburg** [comment]
I believe pip installs pint automatically as a dependency for all OS's except Windows -- @bqpd?

**Comment by bqpd** [comment]
Hmm, I don't think it says `pip install pint` for any of them on the version of the docs I'm looking at: http://gpkit.readthedocs.org/en/latest/installation.html

**Comment by whoburg** [comment]
(which is as it should be, correct?)

**Comment by bqpd** [comment]
Yup!

**Comment by whoburg** [comment]
@mopg says that he went through the install instructions but that pint wasn't installed at the end. We need to check whether pip is actually installing pint.

**Comment by whoburg** [comment]
We have determined that this is fixed on master but not pushed to pypi yet.

Thanks for raising the issue - we will get it fixed asap.

**Comment by whoburg** [comment]
we should also make sure that #654 does not break this.

**Comment by bqpd** [comment]
Pretty sure this is closed by the new install instructions; @whoburg, can you confirm?

**Comment by whoburg** [comment]
yes true, we now suggest installing pint at http://gpkit.readthedocs.org/en/latest/installation.html#install-dependencies. It will automatically be installed by pip once we upload the current master to PyPI.
