### ISSUE TITLE
Windows and gpkit

### ISSUE THREAD

**Issue by galbramc** [hoburg/gpkit#650]
@whoburg and @bqpd. I followed your suggested install process and installed python(x,y) to get cvxopt. This worked on windows 7, but the build is now failing... It could be that something on the windows machines is not correct, but it seems to be working as best as I can tell.

Also, python(x,y) only exists as 32-bit, and does not seem to work on windows 10. You should probably update your install instructions. It took me a long time to sort this out...

**Comment by whoburg** [comment]
What resolves/resolved this? #652? #654?

**Comment by galbramc** [comment]
Yep.
