### ISSUE TITLE
Sliders in interactive on Windows 10

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#658]
I'm running windows 10 and having trouble getting sliders to show up. No error is thrown, and the same code runs fine on Macs. I suspect it could be a problem with ipywidgets but can't find anything online...the code is on a different git but I could copy it over if need be

**Comment by whoburg** [comment]
Do the simple examples at https://ipywidgets.readthedocs.org/en/latest/examples/Using%20Interact.html#Basic-interact work for you?

**Comment by mayork** [comment]
yep, those work

**Comment by mayork** [comment]
wow this is weird I just opened up the d8 code again and this time it worked. not sure what was going on before, neither philippe or I could figure anything out...I guess I'll close this issue

**Comment by whoburg** [comment]
great. if this occurs again, please post as much diagnostic info as possible here.
