### ISSUE TITLE
Gallons not in pint

### ISSUE THREAD

**Issue by cjk12** [hoburg/gpkit#661]
Any chance we could add gallons to our version of pint?  It appears to not be in regular pint and I know we have added stuff before...

**Comment by whoburg** [comment]
Seems to work for me:

```python
In [1]: from gpkit import units

In [2]: units("gallon")
Out[2]: <Quantity(1, 'gallon')>
```

They even have units for both dry and liquid gallons.

**Comment by cjk12** [comment]
Oh, I was using `gal` and didn't see it in the documentation...  Oops.  Thanks.

**Comment by whoburg** [comment]
That's a good point about "gal" -- pint 0.6 did not have that shortcut, but 0.7.2 does. Once #665 is merged, gpkit will have "gal" too.
