### ISSUE TITLE
no upper bound warning triggered unexpectedly

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#666]
This is a MWE derived from one of the 'call an external solver' models. The result is `C_D has no upper bound` and a solver RankError, which is surprising since `CD` is the objective.

``` python
from gpkit import Variable, Model
from gpkit.constraints.set import ConstraintSet

CD = Variable("C_D", "-", "Drag Coefficient")
cdmin = Variable("cdmin", 0.5)

class SimpleCDModel(ConstraintSet):

    def as_posyslt1(self):
        raise TypeError("SimpleCDModel is not allowed to solve as a GP.")

    def as_gpconstr(self, x0):
        return (CD >= cdmin)

constraints = [SimpleCDModel([])]

m = Model(CD, constraints)
sol=m.localsolve()
```

**Comment by bqpd** [comment]
Works with `constraints = [SimpleCDModel([]), cdmin >= 0.1]`. The problem is introducing a new constant in the middle of a solve; it doesn't look for a value.

**Comment by bqpd** [comment]
Still should print out a _lower_ bounds warning instead of the upper bound warning.

**Comment by bqpd** [comment]
The _feasibility programs_ are what's missing an upper bound for CD, and correctly printing this out. So this isn't a bug, just a potentially unwanted feature...

**Comment by bqpd** [comment]
@whoburg, @pgkirsch, @mayork, @mjburton11, I'm tempted to make feasibility models not print bounds warnings. What sayest thou?

**Comment by pgkirsch** [comment]
I agree with this because SPs often give misleading bound warnings in the feasibility solves.

On Sep 9, 2016, at 20:00, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


@whoburg<https://github.com/whoburg>, @pgkirsch<https://github.com/pgkirsch>, @mayork<https://github.com/mayork>, @mjburton11<https://github.com/mjburton11>, I'm tempted to make feasibility models not print bounds warnings. What sayest thou?

**Comment by whoburg** [comment]
Hm, I'm less convinced. Bound warnings are often super useful for debugging Linking errors (including for SPs, which may go straight to feasibility solve mode)

I haven't seen the misleading bound warnings @pgkirsch mentions. Are we sure they were not the result of one of the many bugs we recently fixed?

I'm still not clear on why the example at the top of this ticket triggers a feasibility solve of any kind. The `as_gpconstr` approximate version seems primal feasible.

**Comment by pgkirsch** [comment]
I can't speak to the recent bug fixes, but I have had occasions where I get messages saying "Drag has no upper bound" when Drag would never realistically need to have an upper bound for any problems I've worked with. When this happens, I often get more than one of these warnings and in these cases they are on alternating solves (e.g. 2nd solve, 4th solve, 6th solve etc.) which led me to believe it was happening in the feasibility solves.

**Comment by bqpd** [comment]
Final solution: put original problem's cost in the feasibility-solve cost. This has several benefits, one of which is fixing those bound warnings organically.

**Comment by pgkirsch** [comment]
Nice!

On Sep 15, 2016, at 09:28, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


Final solution: put original problem's cost in the feasibility-solve cost. This has several benefits, one of which is fixing those bound warnings organically.
