### ISSUE TITLE
use pytest-ipynb to test ipython notebook features

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#669]
as suggested by @galbramc, https://pypi.python.org/pypi/pytest-ipynb should allow us to test interactive features as well as bugs that only occur in ipython notebooks, such as

 - [ ] pint errors raised by `import gpkit` described in #665 
 - [ ] #664  (controlpanel for SP)
 - [ ] chartJS

**Comment by galbramc** [comment]
Should this be combined with issue #572

**Comment by whoburg** [comment]
yes! good call. I'll copy everything above over there and close this one.
