### ISSUE TITLE
document excluding variables from a link

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#672]
Do we have a way of handling linked models that each have a (distinct) instance of the same sub-model.

In my example, I have linked `wing`, `horizontal tail`, and `vertical tail` models, all of which use an instance of `wingbox`. Unfortunately, I believe the `wingbox` variables are all currently linked across the 3 instances, so all 3 models are effectively using the same wingbox. Is there a clever way of handling this awkward linking request?

**Comment by pgkirsch** [comment]
For actual code, see `gpkit-models/aircraft.aircraft.py`, `aircraft_improvements` branch, commit `1706a544f762b8fe584c63238164c289d1843e7b`.

**Comment by bqpd** [comment]
You should be able to create a linked constraint with `excluded=[vk.str_without(["models"]) for vk in wing[1].varkeys])`, if the first constraint of wing is a wingbox

**Comment by bqpd** [comment]
@whoburg makes a strong case for always not colliding submodels.

**Comment by bqpd** [comment]
But it's not super simple to define what a `submodel` is. I've got some thoughts @pgkirsch, let's meet up and talk about it sometime!

**Comment by pgkirsch** [comment]
I agree about not colliding submodels, and I'm happy to meet up to discuss more!

In the meantime, I'm not sure I understand the `exclude` kwarg. Is that in the `LinkedConstraintSet` at the highest level (i.e. `aircraft - (wing, vtail, htail)`) , or in each second level `LinkedConstraintSet` (e.g. in `wing`)?

Also call me pedantic, but "if a wingbox is the first constraint of wing" seems like a dubious thing to say. I know it's inline with how we are trying to think about models just being glorified constraint sets (if I understand correctly) but.... bleh.

**Comment by bqpd** [comment]
Haha, it's true; we want richer ways to index into constraintsets.

**Comment by pgkirsch** [comment]
Sorry to be clear is there a way of doing this with current syntax? It would be super helpful for thesis writing if I could get it working ASAP.

**Comment by bqpd** [comment]
Yup, I'll take a look at your code!

**Comment by pgkirsch** [comment]
Thanks!

**Comment by bqpd** [comment]
Changing line 103 to these works:

```python
        from wingbox import WingBox
        wb = WingBox()
        lc = LinkedConstraintSet([hlc, vt, fu, lg, ht, wi],
                                 exclude=[vk.name for vk in wb.varkeys])
```

**Comment by pgkirsch** [comment]
Huh thanks! I'm not sure I understand why, but it works, as you promised.

Model takes 6 minutes to solve now though :(.

**Comment by bqpd** [comment]
Yeah, I've been profiling it. :( there's two places that it takes forever; in GP init making unusedsubkeys, and in ConstraintSet init making substitutions.

**Comment by bqpd** [comment]
Okay, got it down to a few seconds, but it's violating a lot of tight constraintsets in the final solve?

**Comment by pgkirsch** [comment]
3 I believe

**Comment by bqpd** [comment]
5 :(

**Comment by bqpd** [comment]
Actually wait two of those are actually basically identical, so 3

**Comment by pgkirsch** [comment]
Ah right makes sense. And getting it down to a few seconds is awesome! Thanks!

**Comment by bqpd** [comment]
Check out #680.

**Comment by bqpd** [comment]
Moving this to docs since the problem now is explaining how to exclude variables from being linked...

**Comment by bqpd** [comment]
No longer relevant, with performance modeling.
