### ISSUE TITLE
How to handle Named Constraint Sets

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#676]
As a new class, a method, or an attribute?

**Comment by bqpd** [comment]
probably as a new class

**Comment by whoburg** [comment]
I like the syntax `ConstraintSet(constraints, name="Spar", ...)` as a user, but I think I remember @bqpd convincing me that inheritance makes more sense here.

**Comment by bqpd** [comment]
Replaced by the new NamedVariables environment, and the de-emphasis of adding cost to named subnmodels.
