### ISSUE TITLE
"linked" variables that call functions of constants and/or variables

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#693]
@bqpd, had this issue using the function that we worked on yesterday.  It seems that all the variables that I am calculating using `lambda` functions are treated as free variables in the model.  Shouldn't they be constants? Because it's saying I can get more of this because nothing is constraining me... 

Here are my variables that I am calculating via `lambda`` function

``` python
              T_atm = VectorVariable(NSeg, 'T_{atm}',
                                      lambda T_sl, L_atm, h: T_sl - L_atm*h, 'K',
                                      'Air temperature', args=[T_sl, L_atm, h])
              P_shaftmax = VectorVariable(NSeg, 'P_{shaft-max}',
                                      lambda P_shaftmaxMSL, h_ref, h:
                                      P_shaftmaxMSL*(1-0.5178*(h/h_ref)**0.92),
                                      'hp', 'Max shaft power at altitude',
                                      args=[P_shaftmaxMSL, h_ref, h])
```

In the output, they are both under the free vars section: (obviously incorrect values)

```
\vec{T_{atm}} : [ 1.43e+05  403       1.47e+05  303      ... ]  [K]         Air temperature
\vec{P_{shaft-max}} : [ 6.37e+07  0.838     1.15e+08  1.18     ... ]  [hp]        Max shaft power at altitude  
```

**Comment by bqpd** [comment]
Oh, shoot. You might need to do a sweep for `linkedsweep` values to be active. Try that?

**Comment by bqpd** [comment]
- [ ] linked variables that replace linkedsweep but don't require a sweep
-  [ ] linked variables calling external functions
-  [ ] linked variables with gradient functions
