### ISSUE TITLE
kwarg for specifying which variables to print in solution tables

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#702]
Would be good to have a kwarg for the latex table options that allows you to specify which variables to include in a table.

Come to think of it, this doesn't just need to be for latex tables. I think @bqpd mentioned this a while ago, but as a user, I really only sanity check a small proportion of the variables in my problems, so even when printing regular solution tables to the command window this kwarg would be useful.

**Comment by bqpd** [comment]
My current feeling is that some variables are more generally important than others; when these are free variables, they're the ones you need to sanity check; when they're fixed variables, they're generally the ones you sweep. Most models only seem to have a few of these?

**Comment by bqpd** [comment]
On the other hand, is this a variable-level thing or a model(/submodel)-level thing?

**Comment by pgkirsch** [comment]
Agree with all that. I guess it's a model thing?

**Comment by bqpd** [comment]
Hmm, what if models had a list of important variables (we need a better name than "important"; "design"?) that you could delete from / add to, and that's what would print with each solve. `sol.table()` would still by default print everything?

**Comment by pgkirsch** [comment]
Hmmm I don't know if it's that set in stone though, ya know? Also, I would prefer for this stuff to be declared near the solve end of a script/model, rather than the Variable declarations if that's what you're suggesting..

**Comment by bqpd** [comment]
Yeah, that's exactly what I'm suggesting :D an optional attribute for models/constraintsets containing the variables they think are important.

**Comment by bqpd** [comment]
This has occurred, and is documented in the performance modeling example :D
