### ISSUE TITLE
Can we change the default behaviour of solution_array.__call__?

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#704]
I don't know if this will be too annoying to implement, but it would be great if the default behaviour of `sol(varkey)` returned what `mag(sol(varkey)` currently returns. I'm sure there is a reason for how it is at the moment, but needing to use `mag` is kind of annoying and ugly...

**Comment by bqpd** [comment]
@whoburg...

**Comment by bqpd** [comment]
(the idea was to prevent unit conversion errors)

**Comment by pgkirsch** [comment]
When writing to textfiles etc..  I can make do.

**Comment by bqpd** [comment]
If it's in non-automated code then this seems like a legit grievance. We could have a `SolutionArray.submag` function to save the import?

**Comment by whoburg** [comment]
is there a way to handle this by using pint's string formatting? http://pint.readthedocs.io/en/0.7.2/tutorial.html#string-formatting
