### ISSUE TITLE
Best way of flattening LinkedConstraintSets and TightConstraintSets

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#705]
I am trying to flatten a big model (aircraft) so I can use it with the fmincon comparison tool. Specifically, I would like to be able to access each constraint explicitly (e.g. not a sub-model) and its `oper` attribute. I have tried `small_scripts.flatten`, but without success. Any suggestions?

**Comment by bqpd** [comment]
use `flat(constraintsets=False)`

**Comment by bqpd** [comment]
use `flat(constraintsets=False)`

**Comment by pgkirsch** [comment]
Awesome, thanks. But this appears to create a generator. Is there a way to turn that back into a model?

**Comment by bqpd** [comment]
Model (generator)

**Comment by bqpd** [comment]
Err, (cost, generator)

**Comment by pgkirsch** [comment]
Phenomenal. Thanks!
