### ISSUE TITLE
How does one access the cost?

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#710]
Asked by email:

"is there a way to access to optimal value of the objective function? Similar doing something like sol(‘x’) to get the solved value of x. I was looking at the documentation and didn’t see anything."

**Comment by whoburg** [comment]
we're in agreement that `sol["cost"]` is the correct answer, right?

**Comment by bqpd** [comment]
Yup! (it just needs to be documented explicitly; right now it's implict in myriad examples)

**Comment by whoburg** [comment]
This is potentially closed by #738; should we expand this issue to work on better documentation for the SolutionArray class?

**Comment by bqpd** [comment]
I don't think so, I think that's part of the general refactor-output-formats?
