### ISSUE TITLE
Printing Sensitivities on Windows

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#711]
When I run a solve with verbosity = 1, 2, or 3 sensitivities don't print. Not sure why, could be correlated to Windows...

Here's my print out for a simple example I'm running some uncertainty tests on (maximizing the volume of a box), I just get no uncertainty. I also am seeing this behavior in the D8 code

Cost
----
 1

Free Variables
--------------
d : 2   box depth 
h : 1   box height
w : 0.5 box width 

Sensitivities
-------------

**Comment by bqpd** [comment]
Were the sensitivities just too small?
