### ISSUE TITLE
A couple sol.table(latex=2) bugs

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#713]
- [x] Creates rows with three ampersands (instead of two) between sub-models.
- [ ] Should put square brackets around units

**Comment by pgkirsch** [comment]
In latex, too few columns is ok, whereas too many is not, so the easiest proposed fix to item 1 is replace 
```python
lines.append(["","", "", ""])
```
with 
```python
lines.append(["", "", ""])
```
on line 228.

**Comment by pgkirsch** [comment]
Actually, I realize that @bqpd and @whoburg might disagree with the second one (I think the code was changed away from square brackets?) so I'll leave that open for discussion. In the meantime the proposed change is ready for a super fast merge.

**Comment by pgkirsch** [comment]
Also piggy-backing on this issue: sensitivity table shouldn't print for `latex=2`.

**Comment by pgkirsch** [comment]
Sorry realized that there is a kwarg for achieving that last thing.

**Comment by bqpd** [comment]
Great! Re: square brackets around units, I'm fine with however you decide to represent them.

**Comment by whoburg** [comment]
I vote for no square braces around units in latex tables, because it seems like unnecessary clutter. Square brackets seem useful in text printouts where there are no columns to disambiguate.

If others agree, then I think this is closed by #714

**Comment by pgkirsch** [comment]
Sounds good

**Comment by pgkirsch** [comment]
You probably disagree with this, but I do wish that unitless variables would have a hyphen or something in the units column to indicate that they have no units, so that the table doesn't look incomplete...

**Comment by bqpd** [comment]
Yeah, for a table a thin horizontal line probably makes sense.

**Comment by whoburg** [comment]
What's a clean way to do this that avoids adding special cases?

the latex table unit string is generated by calling `var.unitstr`, which in turn calls `small_scripts.unitstr`, which has a `dimless` kwarg.

Should we add a `dimless` kwarg to `VarKey.unitstr`?

**Comment by whoburg** [comment]
or just pass through `**kwargs` in `VarKey.unitstr`?

**Comment by bqpd** [comment]
The latter sounds best.

**Comment by whoburg** [comment]
also should `VarKey.unitstr` be renamed to `VarKey.latex_unitstr`? Or alternatively, should it have a `latex=True/False` kwarg, so it can be used for non-latex printouts too?

**Comment by bqpd** [comment]
Yeah, it should probably be renamed.

**Comment by bqpd** [comment]
Reopened because we actually need the four empty strings to print plaintext tables with multiple models properly.
