### ISSUE TITLE
vector variable indices scrambled

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#724]
High priority. Have found a bug where VectorVariable indices get scrambled in constraints involving separate models

MWE:

```python
from gpkit import VectorVariable, Variable, Model

N = 15

class XgtRange(Model):
    def __init__(self, **kwargs):
        X = VectorVariable(N, "X", "m")
        X_min = VectorVariable(N, "X_{min}", range(1, N + 1), "m")
        constraints = [X >= X_min]

        Model.__init__(self, sum(X), constraints, **kwargs)

class Y(Model):
    def __init__(self, **kwargs):
        Y = VectorVariable(N, "Y", "m")
        xgtr = XgtRange()
        constraints = [xgtr,
                       Y >= xgtr["X"]]
        Model.__init__(self, sum(Y), constraints, **kwargs)


if __name__ == "__main__":
    print "-- just XgtRange --"
    xm = XgtRange()
    sol = xm.solve(verbosity=0)
    print "X is ", sol("X")
    
    print "-- now Y --"
    ym = Y()
    sol = ym.solve(verbosity=0)
    print "X is ", sol("X")
    print "Y is ", sol("Y")
```

Output from the above (note that Y is scrambled unexpectedly):

```
-- just XgtRange --
X is  [  1.00000003   2.00000624   3.00000734   4.00000675   5.00000571
   6.00000461   7.00000361   8.00000274   9.00000201  10.00000142
  11.00000095  12.0000006   13.00000033  14.00000015  15.00000005] meter
-- now Y --
X is  [  1.           2.00000031   3.00000035   4.0000003    5.00000023
   6.00000017   7.00000012   8.00000008   9.00000005  10.00000003
  11.00000002  12.00000001  13.00000001  14.          15.        ] meter
Y is  [  7.00000024  14.          10.00000007   3.0000007    6.00000034
   8.00000016   2.00000062   4.0000006   11.00000004  13.00000001
   9.00000011  15.           5.00000046  12.00000002   1.        ] meter
```

The underlying issue appears to be `__getitem__` involving a VectorVariable. `print xm["X"]` returns:
```
[gpkit.Variable(X_XgtRange_(6,) [m]), gpkit.Variable(X_XgtRange_(9,) [m]), gpkit.Variable(X_XgtRange_(2,) [m]), gpkit.Variable(X_XgtRange_(5,) [m]), gpkit.Variable(X_XgtRange_(7,) [m]), gpkit.Variable(X_XgtRange_(1,) [m]), gpkit.Variable(X_XgtRange_(3,) [m]), gpkit.Variable(X_XgtRange_(8,) [m]), gpkit.Variable(X_XgtRange_(4,) [m]), gpkit.Variable(X_XgtRange_(0,) [m])]
```

**Comment by whoburg** [comment]
patched by #725. Remaining issues to close this:

 - [ ] decide: is #725 the correct fix?
 - [ ] add unit test (the MWE above will do)

**Comment by bqpd** [comment]
I think #725 seems like a fine fix, though I wonder if it works for higher-dimensional arrays.

**Comment by whoburg** [comment]
Is there any value in considering a design where VectorVariables are keyed by a single varkey that has its own mechanism for storing all the indices for that VectorVariable? In other words, instead of separate varkeys for each index, does it make any sense to have a single varkey that has an array as its indices and can be sliced like a numpy array?

Seems perhaps more natural for indices to be in a (sorted) list than floating around as separate unsorted dict keys.

We can more this into a separate ticket if needed.

**Comment by bqpd** [comment]
We do this in keydicts, and could potentially do so in keysets as well!
It's just a single line to do so. Some parts of substitution would need to
be updated as well.

**Comment by bqpd** [comment]
We have a better fix now.

**Comment by whoburg** [comment]
(what was the better fix?)
