### ISSUE TITLE
python x,y possible on windows 10

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#730]
The read the docs site says

"Unfortunately, on Windows, due to 32-bit vs 64 bit issues, we do not currently know of a way to install both cvxopt and mosek simultaneously. If you are a Windows user, you should pick one solver or the other. For Windows 10, cvxopt does not appear to be an option."

I'm running 64 bit Windows 10 and cvxopt without a problem

**Comment by bqpd** [comment]
Awesome! When you start up python (or run `python --version`), what's the
version id you get?

**Comment by whoburg** [comment]
Thanks for pointing this out!

another question: are you using Anaconda, Python X,Y, or none of the above?
can you please copy/paste here the header printed out by python when you run 
`python`
at a command line?

**Comment by mayork** [comment]
![image](https://cloud.githubusercontent.com/assets/6796415/15765668/611fc792-2905-11e6-8e99-5b897e606e1e.png)

I have python x,y...I think I might need to install mosek, I might try to leave cvxopt on and see if I can get both to run

**Comment by bqpd** [comment]
@galbramc, it looks like 32bit python & python x,y can be used on windows 10?

**Comment by galbramc** [comment]
Intersting. Maybe I messed up when I tried to do it. As far as I can recall, I got an import error when I tried to import cvxopt with python x,y that was complaining about bits.

@mayork can you try to get 32 bit mosek setup on your system as well? The code for 32-bit mosek in build.py is currently commented out though.

**Comment by mayork** [comment]
@galbramc yeah I can. I think I need to install Mosek to solve some models better...my only question is will I have to install anaconda, or is there a way around that?

**Comment by galbramc** [comment]
No you should not need anaconda. There is nothing special about anaconda, it's just a wrapper that makes installing dependencies on Windows easier. There might be some other benefit, but I'm not aware of it.

Do you know how to fix build.py for mosek 32 but? You should be able to find the comments and code that needs to be uncomment.

**Comment by mayork** [comment]
okay just curious the gpkit docs say to get anaconda first. I don't know how to fix build.py but it sounds straightforward enough, I can take a look at it

**Comment by galbramc** [comment]
Yeah we wrote the documentation that way because python xy didn't work for me on the first try. I don't know why it didn't work for me but is working for you.

**Comment by mayork** [comment]
@galbramc so I followed all the install instructions for Mosek, uncommented the code in build.py and added mingw to my system path but I get this error 

Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine_component_testing.py", line 164, in <module>
    sol = offdesign.solve(kktsolve = "ldl", verbosity = 4, solver = 'mosek')
  File "C:\Python27\lib\site-packages\gpkit\constraints\prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity-1, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gpkit\geometric_program.py", line 169, in solve
    solverfn, solvername = _get_solver(solver)
  File "C:\Python27\lib\site-packages\gpkit\geometric_program.py", line 160, in _get_solver
    from ._mosek import expopt
  File "C:\Python27\lib\site-packages\gpkit\_mosek\expopt.py", line 22, in <module>
    raise ImportError("Could not load MOSEK library: "+repr(e))
ImportError: Could not load MOSEK library: ImportError('No module named lib',)

Its also worth noting that I have a 64 bit machine, so I also tried to edit line 159 of build.py to read 
rootdir = "C:\\Program Files (x86)\\Mosek" instead of rootdir = "C:\\Program Files\\Mosek" because mosek automatically put itself into Program Files (x86)....any idea what to do with this?

**Comment by mayork** [comment]
scratch that last idea, as suspected running 64 bit Mosek won't work

**Comment by bqpd** [comment]
Ah, dang. But python x,y does, huh?

**Comment by galbramc** [comment]
Did you install the 32 bit mosek and try that? I'm guessing that's what you
meant didn't work.

**Comment by mayork** [comment]
Yeah 32 and 64 bit didn't work. From what I saw online the 64 bit will not work with Python at all, but the 32 should

**Comment by galbramc** [comment]
I'm guessing it's still worth updating the documentation to say that python x,y works on windows 10?

**Comment by bqpd** [comment]
Is it? I think we prefer using Anaconda instead these days, right?

**Comment by galbramc** [comment]
If you want cvxopt on Windows you need to use python xy. But I think @mayork got python xy to work on Windows 10 when it didn't work for me.

**Comment by bqpd** [comment]
@pgkirsch has been doing lots of cvxopt installs with Anaconda, I think.

**Comment by bqpd** [comment]
as documented in https://github.com/hoburg/gpkit/issues/811
