### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#733]
Getting the following error in my engine model, commit  377b9dd found at
https://github.com/hoburg/gpkit-models/pull/72#issuecomment-224971711

Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\engine_component_testing.py", line 51, in <module>
    turbinesol = turbine.solve(verbosity = 4)
  File "C:\Python27\lib\site-packages\gpkit\constraints\prog_factories.py", line 80, in solvefn
    result = solvefn(solver, verbosity-1, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gpkit\geometric_program.py", line 204, in solve
    self.result = self._compile_result(solver_out)  # NOTE: SIDE EFFECTS
  File "C:\Python27\lib\site-packages\gpkit\geometric_program.py", line 310, in _compile_result
    k, = self.constraints.varkeys[k]
ValueError: need more than 0 values to unpack

I'm 99% sure the models is solving to an optimal state, with verbosity = 4 I get the following output before the error

Using solver 'cvxopt'
Solving for 11 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00 -8.6299e-01  2e+01  1e+00  1e+00
 1: -3.0447e+05  2.0751e+04  7e+00  6e+03  5e-01
 2: -9.7752e+03  7.4407e+00  3e-01  2e+02  2e-02
 3: -1.7001e+02 -1.3899e+01  4e-03  3e+00  3e-04
 4: -1.5466e+01 -1.3820e+01  4e-05  3e-02  8e-02
 5: -1.4027e+01 -1.3505e+01  7e-06  9e-03  1e-01
 6: -1.3548e+01 -1.3377e+01  1e-06  2e-03  7e-02
 7: -1.3366e+01 -1.3357e+01  2e-08  1e-04  1e-02
 8: -1.3357e+01 -1.3357e+01  4e-10  3e-06  3e-04
 9: -1.3357e+01 -1.3357e+01  4e-12  3e-08  4e-06
10: -1.3357e+01 -1.3357e+01  4e-14  3e-10  4e-08
Optimal solution found.
Solving took 0.06 seconds.

I also checked everything by hand and it seems feasible

**Comment by bqpd** [comment]
Uh oh, there seem to be no varkeys when the gp thinks there should be. Hmm.

**Comment by mayork** [comment]
This model was for a sub component of the engine, when I link this model with the other component models it works fine. Not sure if that helps at all.

**Comment by mayork** [comment]
@bqpd or @whoburg is there a work around to this where I can print or the solution table or in some other fashion see the solution? If not, could this become a higher priority fix? Seeing the solutions to the two models throwing this error would be really helpful

**Comment by bqpd** [comment]
Fixed in #740
