### ISSUE TITLE
"physical constant" type whose sensitivities are not printed

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#742]
@whoburg, we still want this?

**Comment by mayork** [comment]
I think this could be really useful, especially if the physical constant variables were allowed to be in the a variables exponent (i.e. gamma in the isentropic relation)

**Comment by bqpd** [comment]
I'm still a little antsy about variables in the exponents, but it's definitely doable.

**Comment by whoburg** [comment]
#825 captures the sensitivity to exponents issue. I'd be ok closing this unless anyone is clamoring for the `PhysicalConstant` type.

**Comment by bqpd** [comment]
Fine by me.

**Comment by whoburg** [comment]
(anyone is free to reopen this)
