### ISSUE TITLE
possibly an error on master?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#748]
I was running fixdes most of the day and just pulled and installed master. I'm now getting this error

```
Traceback (most recent call last):
File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 377, in 
m = CommercialAircraft()
File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 351, in init
cmc = CommericalMissionConstraints(1)
File "C:/Users/mayork/Documents/GitHub/gpkit-models/gpkitmodels/Commercial Sizing/test.py", line 191, in init
Model.init(self, W_ftotal, constraints, **kwargs)
File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\model.py", line 65, in init
self._add_modelname_tovars(self.name, self.num)
File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\model.py", line 100, in _add_modelname_tovars
self.subinplace(add_model_subs)
File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\costed.py", line 25, in subinplace
ConstraintSet.subinplace(self, subs, value)
File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\set.py", line 128, in subinplace
constraint.subinplace(subs, value)
File "c:\users\mayork\documents\github\gpkit\gpkit\nomials\nomial_math.py", line 442, in subinplace
nomial.subinplace(substitutions, value)
AttributeError: 'list' object has no attribute 'subinplace'
```

I think its an error on master that occured after merging fixdes because I pulled and installed nomialmap and I could run the code fine

**Comment by bqpd** [comment]
Hmm, somehow a list of constraints is not getting turned into a ConstraintSet. That's quite odd.

**Comment by mayork** [comment]
is there a way I can access the old fixdes branch? I don't see it anywhere right now, I'm guessing its gone since it was merged, but I was able to use the SignomialeEquality in two places and it fixed the engine model so I wouldn't mind continuing to work on a branch with the signomial equality

**Comment by whoburg** [comment]
@mayork, I restored the `fixdes` branch, hopefully that's helpful for debugging this. Please let us know what you find out.

**Comment by whoburg** [comment]
Also, if it's still broken on `fixdes`, try checking out commit 480e0a696f9846b8b087429ce57120e7d7d91982.

**Comment by mayork** [comment]
checking out fixdes didn't work. I got the following message from git 
![image](https://cloud.githubusercontent.com/assets/6796415/16310015/c878e548-3938-11e6-8bb6-ec70b391a012.png)
and when I tried to switch back to master I got this 
![image](https://cloud.githubusercontent.com/assets/6796415/16310029/e227385a-3938-11e6-835f-72709fbcfcfa.png)

I was able to check out 480e0a696f9846b8b087429ce57120e7d7d91982, and everything runs properly after installing the gpkit at that commit.

Hopefully that's somewhat helpful

**Comment by whoburg** [comment]
ok, the diverged message is because we rebased `fixdes` and force pushed -- not a concern.

@mayork, one more thing to confirm a hunch I have -- can you check out 273df2a5d2472455cb6f8937d43b42c6115d9fb7 and see if that runs too?

**Comment by mayork** [comment]
https://github.com/hoburg/gpkit/commit/273df2a5d2472455cb6f8937d43b42c6115d9fb7 also runs

**Comment by whoburg** [comment]
ok, so it looks like ce2aef2ffcffc53f58c1bc8e3ef2a1fa914aeaab is the likely culprit.

@mayork, what exactly should I run (commit, file, command) to reproduce this and debug?

**Comment by mayork** [comment]
@whoburg I was running engine.py form the Engine branch (https://github.com/hoburg/gpkit-models/pull/72). You don't need to do anything besides run the file. I believe the most recent commit should throw the error, but if it doesn't I'm sure https://github.com/hoburg/gpkit-models/pull/72/commits/6f69f866f10f63fc3517ad570f3f2cd9599aafd3 will.

**Comment by whoburg** [comment]
ok, I'm jumping in to tackle this so @bqpd can keep cranking on a paper

**Comment by whoburg** [comment]
sorry got delayed but this is about to be fixed

**Comment by whoburg** [comment]
thanks for reporting this issue @mayork
