### ISSUE TITLE
constraint list entering sol dict during sweeps?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#750]
I'm trying to plot a compressor map to make sure it looks right, and I'm using sweeps to generate the data. However, I keep getting this error. It looks like what's happening is my list of constraints is being used as a key in d_out[k] which I think means its somehow finding its way into the solution dict...not 100% sure on that last part though.

The code that causes this error is on the gpkit-models Engine branch at https://github.com/hoburg/gpkit-models/pull/72/commits/51f3645cdc38cf3a7fb44eeb92912a0c14060d66. Just run the file compressor_map_plots.py.

It doesn't matter if skipsweepfails is set to true or false, and it also doesn't matter if the sweep is linked. I think this could be a gpkit error, but I could also just be making a bonehead error.

```
Traceback (most recent call last):
  File "C:\Users\mayork\Documents\GitHub\gpkit-models\gpkitmodels\aircraft\compressor_map_plots.py", line 34, in <module>
    sol = lpcmap.localsolve(kktsolver="ldl", verbosity = 4, skipsweepfailures=False)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\prog_factories.py", line 77, in solvefn
    solver, verbosity-1, *args, **kwargs)
  File "c:\users\mayork\documents\github\gpkit\gpkit\constraints\prog_factories.py", line 132, in run_sweep
    solution.append(result)
  File "c:\users\mayork\documents\github\gpkit\gpkit\small_classes.py", line 85, in append
    _append_dict(sol, self)
  File "c:\users\mayork\documents\github\gpkit\gpkit\small_classes.py", line 111, in _append_dict
    d_out[k] = _append_dict(v, d_out[k])
  File "c:\users\mayork\documents\github\gpkit\gpkit\small_classes.py", line 111, in _append_dict
    d_out[k] = _append_dict(v, d_out[k])
  File "c:\users\mayork\documents\github\gpkit\gpkit\small_classes.py", line 111, in _append_dict
    d_out[k] = _append_dict(v, d_out[k])
KeyError: '\n        N_{bar_lc}_LPCMap = N_1_LPCMap*T_{ref}_LPCMap**0.5*T_{t_2}_LPCMap**-0.5\n        m_{lc}_LPCMap = P_{ref}_LPCMap*P_{t_2}_LPCMap**-1*T_{ref}_LPCMap**-0.5*T_{t_2}_LPCMap**0.5*m_{core}_LPCMap\n        1.32*\\pi_{lc_D}_LPCMap**0.92*p_{tild_lc}_LPCMap**0.92 = 1.61*\\pi_{lc}_LPCMap**0.82*p_{tild_lc}_LPCMap**0.18\n        m_{tild_lc}_LPCMap = m_{core_D}_LPCMap**-1*m_{lc}_LPCMap\n        N_{tild_lc}_LPCMap = N_{bar_lc}_LPCMap*N_{{bar}_D_lc}_LPCMap**-1\n        m_{{tild}_slc}_LPCMap = N_{bar_lc}_LPCMap**0.5\n        p_{{tild}_slc}_LPCMap = m_{{tild}_slc}_LPCMap**1.5\n        33.3*m_{{tild}_slc}_LPCMap = 1.51*m_{tild_lc}_LPCMap**0.098*zlc_LPCMap**2.2\n        p_{tild_lc}_LPCMap = 0.835*N_{tild_lc}_LPCMap**0.27*p_{{tild}_slc}_LPCMap**0.73*zlc_LPCMap**0.27
```

**Comment by bqpd** [comment]
Ah dang this is in the constraint-sensitivity code. Unexpected, but that code's been needing a fix. Is your sweep bounded by 0 below?

**Comment by mayork** [comment]
No the sweep wasn't bounded by zero. I just experimented and bounded it by zero, it didn't make a difference.

**Comment by mayork** [comment]
This could be worth fixing before the 11th if we're going to do the live sensitivity session

**Comment by bqpd** [comment]
Ooh that's definitely a priority.

**Comment by whoburg** [comment]
@mayork, can you check whether this is fixed for you now?
