### ISSUE TITLE
can't build docs

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#752]
Commit add9d6093bc48e4ae21b5378fe0b60b4d6715e2c broke `make html` on my mac. `make html` runs fine on the parent commit, whereas after the commit above I get:

```
whoburg$ make html
rm source/autodoc/*
sphinx-apidoc ../gpkit -o source/autodoc
Creating file source/autodoc/gpkit.rst.
Creating file source/autodoc/gpkit.constraints.rst.
Creating file source/autodoc/gpkit.interactive.rst.
Creating file source/autodoc/gpkit.nomials.rst.
Creating file source/autodoc/gpkit.tests.rst.
Creating file source/autodoc/gpkit.tools.rst.
Creating file source/autodoc/modules.rst.
sed -i '1i Glossary\n********\n\n*For an alphabetical listing of all commands, check out the* :ref:`genindex`\n' source/autodoc/gpkit.rst
sed: 1: "source/autodoc/gpkit.rst": bad flag in substitute command: 'c'
make: *** [apidoc] Error 1
```

**Comment by whoburg** [comment]
ping. It's hard to review PRs like #823 without being able to see the html output

**Comment by bqpd** [comment]
Mac sed doesn't accept `\n`. :( I'll just  skip this command on a mac?

**Comment by whoburg** [comment]
Does this help? http://nlfiedler.github.io/2010/12/05/newlines-in-sed-on-mac.html

It would be nice to have a cross-platform solution but worst case we can disable on a mac for now -- better to be able to build the user-written docs and no autodocs than no docs at all.

**Comment by bqpd** [comment]
See if https://github.com/hoburg/gpkit/pull/838 runs for you...

**Comment by whoburg** [comment]
Unfortunately I still get the sed warnings:

```
(gpkit)warrens-mbp-2:docs whoburg$ make html
./apidoc.sh
Creating file source/autodoc/gpkit.rst.
Creating file source/autodoc/gpkit.constraints.rst.
Creating file source/autodoc/gpkit.interactive.rst.
Creating file source/autodoc/gpkit.nomials.rst.
Creating file source/autodoc/gpkit.tests.rst.
Creating file source/autodoc/gpkit.tools.rst.
Creating file source/autodoc/modules.rst.
sed: 1: "source/autodoc/gpkit.rst": bad flag in substitute command: 'c'
sed: 1: "source/autodoc/gpkit.rst": bad flag in substitute command: 'c'
make: *** [apidoc] Error 1
```

**Comment by whoburg** [comment]
commenting out most of `apidoc.sh`, I note that the command `sed -i '1,3d' source/autodoc/gpkit.rst` already raises one of the bad flag errors.

I'm not super familiar with sed; there's this: http://www.culmination.org/2008/02/sed-on-mac-os-x-105-leopard/

**Comment by whoburg** [comment]
This change makes the first line work for me: `sed -i'' -e '1,3d' source/autodoc/gpkit.rst` (as described here: http://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux)

Sadly though, I still can't get the second sed command to run.

**Comment by bqpd** [comment]
Let's sit down at your laptop sometime this week to speed up the iteration time :p
