### ISSUE TITLE
Debugging signomial feasibility

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#754]
I tried to solve a model and it didn't converge under the iteration limit so I got this message
![image](https://cloud.githubusercontent.com/assets/6796415/16469991/d278252a-3e21-11e6-9edf-40e54854efb0.png)

I ran the command model.program.gps[-1] and got gpkit.GeometricProgram(1574487007)...what does that tell me?

**Comment by bqpd** [comment]
oh, sorry, gps don't have a great representation. but you can look at their `.constraints` if that's what you want.

What'd probably be more useful, though, is `[gp.result.get("cost", None) for gp in m.program.gps]`, which will tell you whether you were a) jumping between feasibility and regular solves or b) just doing feasibility solves.

**Comment by whoburg** [comment]
The number 1574487007 in gpkit.GeometricProgram(1574487007) is just a hash - it doesn't tell you anything. GeometricProgram objects in GPkit don't store the richer symbolic info in Model objects, and thus they don't print out anything pretty. A GP is just an A matrix, a c vector, and a p_idxs vector, for passing to a solver.

That said, `model.program.gps[-1].result` is a solution that you can inspect.

**Comment by whoburg** [comment]
ha, simultaneous reply

**Comment by mayork** [comment]
ah, okay thanks! both of those are useful commands to know!

**Comment by mayork** [comment]
I'm almost 100% sure this off design engine model is now dual infeasible. Without the bounding debugger it has 2 3 iteration solves which end in singular KKT matrix before cvxopt returns infeasible. When I run with bounded I get a number of real solves followed by rotating feasibility/real solve that goes until the iteration limit is reached.

Is there a way to see what variables are hitting the bounds from the bounding tool even though the model isn't solving? Can I see the solution to the first few GP solves somehow?

**Comment by bqpd** [comment]
Hmm, it might also be intrinsically primal infeasible?

**Comment by mayork** [comment]
I guess it could be. Are there any good ways to test for that?

**Comment by mayork** [comment]
when an equality constraint is enforced how "equal" do the values have to be? Is it possible that machine precision and round off could lead to an equality constraint not being possible?

**Comment by pgkirsch** [comment]
I am also getting a `singular KKT matrix`, which I have never seen before (though that may be because I have only ever really used MOSEK).

**Comment by mayork** [comment]
Yeah I see that pretty frequently, I still am not sure if it indicates anything different than unknown..did you try passing in kktsolver="ldl" as an input?
