### ISSUE TITLE
Linked vector variable solution storage

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#755]
In the flight profile code (https://github.com/hoburg/gpkit-models/pull/73) I have a number of vector variables declared globally then accessed inside different submodels which are linked. However, certain submodels only touch certain vector indices. For example, the climb model is only touching altitude in the first few indices where the climb is simulated.  When I try and access the solution I get print outs likes this
![image](https://cloud.githubusercontent.com/assets/6796415/16546380/76c8fcfc-4116-11e6-84ef-c7867ff8371f.png)

I think it would be better to store the solutions in a way that there are no nan entries and it isn't in a dict. This would make plotting the solution significantly easier. I think a single quantity whose value is a list would make the most sense, but I'm not sure that's actually the best solution.

**Comment by whoburg** [comment]
good issue. yeah, this seems like something we could do a lot better.

**Comment by bqpd** [comment]
Hmm, I actually think this is done right, but that global vector variables should be discouraged. What about having separate vector for climb / etc which are concatenated as necessary?

**Comment by mayork** [comment]
Interesting idea. I'm just curious, @bqpd why do you discourage global vector variables?

The only problem with that I can think of with using a few different vector variables is that I'm also linking the height from the flight profile with the height from an atmosphere model. I think this would just require me to make 3 atmosphere models as well, right? Because I'll need the three different height vectors to have different varkeys so they don't link to each other, which means I'll also need 3 atmosphere models. That's not a big deal, I could certainly do it.

**Comment by bqpd** [comment]
Whether you'd need 3 atm models depends on how your atm models are set up! So this ends up tying into another new design problem, "how do we vectorize our custom models?"

**Comment by whoburg** [comment]
@mayork, have your opinions on this issue changed with the new performance models approach?

**Comment by bqpd** [comment]
pinging @mayork  :p

**Comment by mayork** [comment]
I think this is a non-issue now that we are using performance modeling
