### ISSUE TITLE
Linking variables w/different varkeys

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#757]
@bqpd I was wondering what your thoughts on the below are. Hopefully you can understand what I'm trying to describe...if not I can try to clarify any or all of it. It's possible I'm just not understanding what is happening in linked.py, if this is the case I apologize in advance.

I'm trying to plan out linking together my engine and the discretized flight profile models, as well as eventually some of philippe's aircraft models. I'm looking over the linked.py file and I'm a little concerned with how the linking is going to be performed. I need to create an engine model for each flight segment. One model will be an on design engine model and the rest will be off design. The vast majority of the variables in each on and off design model share the same name, since they're constructed from the same submodels. This in and of itself doesn't seem like an issue, just put all these variables into the exclude only list. However, I also need to link the ambient pressure in each engine model with the pressure from the flight profile model, which is a vector variable.

Of course, I only want to link each engine ambient pressure with the piece (not sure what the proper word for this is) of the vector variable corresponding to the atmosphere's pressure for that flight segment.

It seems to me, that since the variables will be linked based on the varkeys with .str_without(["models"]) applied there is not a way to perform the linking above. I think the best I can do is link every instance of engine ambient pressure and flight profile ambient pressure. This is because all the engine ambient pressures will link to each other, since their varkey with .str_without(["models"])  will be identical. This is in turn will link all of the atmosphere pressures to each other.

Also, I don't see a way to link variables with different varkeys. Is there a way to do this?

**Comment by bqpd** [comment]
You're in luck! First, you don't need `exclude_only` if you use Named Models; the variables with the same name will have different `models` attributes and therefore not collide.

Second, you can link between things with different names manually; LinkedConstraintSets are just a convenient automation. Do this by making a constraintset with the various models you want to link in it, and then doing `constraints.subinplace({x1: y, x2: y, x3: z})` or similar.

**Comment by mayork** [comment]
ah okay linked.py won't drop the _model off the varkey of a variable in a named model? Also, is named model a class (I couldn't find it in the code base just now)?

Sub in place makes a lot of sense! sorry for all the questions, thanks for your help!

**Comment by bqpd** [comment]
Nope! and the class is NamedConstraintSet, but Model inherits from it, and if you inherit from Model then you get this by default

**Comment by bqpd** [comment]
No worries about the questions! You're finding the parts of the linking interface that are still just (udocumented) drafts.

**Comment by mayork** [comment]
ah okay that makes sense thanks!

**Comment by mayork** [comment]
@bqpd when using the subinplace method of linking the x1, y, etc. from your example are varkeys, correct?

**Comment by bqpd** [comment]
Or variables, doesn't matter. :)

**Comment by mayork** [comment]
or a mix of both...just figured out a minute ago that works which is really quite nice!

**Comment by mayork** [comment]
I talked this over with @whoburg this morning. However, I still can't get the linking to work and I think I know why, although I'm not sure what to do to fix the issue. The piece of code where I attempt to perform the substitution is below. TSFC is  a vector variable of length 6.
```
self.submodels = [cmc, climb1, climb2, cruise2, eonD]
constraints = ConstraintSet([self.submodels])
constraints.subinplace({TSFC[4]: TSFCe})
lc = LinkedConstraintSet(constraints)
```
I believe the problem is that I'm calling sub in place on something that isn't a list. For example if I run this code
```
constraints = ConstraintSet([self.submodels])
 print TSFC[4]
print TSFCe
print constraints
constraints.subinplace({TSFC[4]: TSFCe})
print constraints
lc = LinkedConstraintSet(constraints)
```
I get the following output

```
TSFC_(4,) [1/hr]
TSFC_E [1/hr]

        CommericalMissionConstraints_0
        Climb1_0
        Climb2_0
        Cruise2_0
        EngineOnDesign_0

        CommericalMissionConstraints_0
        Climb1_0
        Climb2_0
        Cruise2_0
        EngineOnDesign_0
```
so the variables print as expected but constraints isn't a list. How should I be creating the submodels so that constraints becomes a list? @bqpd thoughts?

Also, the code that I'm running can be found at https://github.com/hoburg/gpkit-models/pull/73/commits/9a944cadcb549f6b5b5a25eef1f2e9d29b969d43

**Comment by bqpd** [comment]
That really should work; the constraints are always nested lists, they just print sometimes in a "collapsed" form.

**Comment by mayork** [comment]
Hmm I don't think it is because I'm getting a warning that TSFC[4] is unbounded. I am assigning values to all the other TSFC variables and linking TSFC[4] to the engine model. If I link all the TSFC variables to the engine then the model solves, so this method should work.

**Comment by bqpd** [comment]
When I try to run that file I get `ImportError: No module named engine_components`

**Comment by bqpd** [comment]
Is engine_components not added to the repository yet?

**Comment by mayork** [comment]
Sorry, it wasn't. just pushed it with this commit https://github.com/hoburg/gpkit-models/pull/73/commits/17751baa290c932b68986658b56db9c86dccefc7

**Comment by mayork** [comment]
Also, the model ```eonD``` is itself composed of a few submodels that live in ```engine.py```. Not sure if that has anything to do with what's happening.

**Comment by mayork** [comment]
Was there any ideas on what was wrong here? Getting these variables linked is my biggest hold up for this Aurora model right now

**Comment by whoburg** [comment]
I think part or all of the problem has to do with the named submodels `Climb1`, `Cruise2`, etc. When these models get created `gpkit.Model` appends their name to the `TSFC` varkeys.

```python
In [15]: m["TSFC"]
Out[15]:
[gpkit.Variable(TSFC_Climb1, CommercialAircraft_(0,) [1/hr]),
 gpkit.Variable(TSFC_Climb1, CommercialAircraft_(1,) [1/hr]),
 gpkit.Variable(TSFC_Climb2, CommercialAircraft_(2,) [1/hr]),
 gpkit.Variable(TSFC_Climb2, CommercialAircraft_(3,) [1/hr]),
 gpkit.Variable(TSFC_Cruise2, CommercialAircraft_(4,) [1/hr]),
 gpkit.Variable(TSFC_Cruise2, CommercialAircraft_(5,) [1/hr])]
```
Note above you can access the string `"TSFC"`, but you can't similarly use the varkey `TSFC[4]` -- because that doesn't collide with the varkeys in the named models:

```python
In [29]: m[TSFC[4]]
Out[29]: []
```

@bqpd will probably weigh in on the design decisions and global vector variables. For now some options to consider are making the submodels ConstraintSets instead of Models (note this will cause all same-named variables to collide), or using full string access, e.g. `constraints.subinplace({"TSFC_Cruise2_(4,)": TSFCe})`.

@mayork, note you currently have two Variables named `TSFC_E`.

**Comment by mayork** [comment]
Ah yes that makes sense!

@whoburg just to make sure I haven't missed something you're referring to the ```TSFC_E``` declared in flight profile and the second instance in the ```engine_components.py```, right? I created the instance in ```engine_components.py``` as an experiment to try and better understand what was happening

**Comment by whoburg** [comment]
yep, the one in `FanAndLPC`

**Comment by mayork** [comment]
okay that's what I thought, thanks!

**Comment by bqpd** [comment]
@mayork, let's meet up sometime after wednesday next week and go over vecvars :D

**Comment by mayork** [comment]
@bqpd sounds good I'll be gone  next week but when I'm back we should meet up

**Comment by mayork** [comment]
After making everything into constraint sets and TSFC into a series of local vector variables I get the same error...

**Comment by whoburg** [comment]
Hmm, that does seem odd.

It seems the code has moved along since it no longer contains the line `constraints.subinplace({'TSFC_Cruise2_(4,)': 'TSFC_E'})`. Is there a commit hash where this can be debugged? Instructions on what file to run or what object to create would also be helpful.

**Comment by mayork** [comment]
Yeah sorry...ended up moving on without linking which is suboptimal, but it lets me work on engine integration. I believe this commit should demonstrate what I was seeing https://github.com/hoburg/gpkit-models/pull/73/commits/9eea9e55f6bd2623f7815dad427ad4de9a4d519f....All the code needed to run should be on git, just run the file ```Commerical_Flight_Profile.py```

**Comment by mayork** [comment]
the problem linking vector variables is a duplicate of #822 so I'm going to close this isssue
