### ISSUE TITLE
another slow-building model to profile

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#768]
On the `commercial_sizing` branch of gpkit-models, at commit 386de4077ce9e0786087ae5b6c2ea4fa310538e5, in the file `gpkitmodels/Commercial Sizing/Commerical_Flight_Profile.py`,

running `%time m = CommercialAircraft()` takes 25.5 seconds (!)

**Comment by bqpd** [comment]
covered by by #801 (newer commit of same model)
