### ISSUE TITLE
Windows mosek_cli erroneously not supported

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#773]
It gives a `"mosek_cli" not supported for this architecture`, which is a bizarre error message that doesn't really make sense for a command line solver interface.

**Comment by whoburg** [comment]
do we know how to reproduce this?

**Comment by bqpd** [comment]
Easy to show in `build.py`

**Comment by bqpd** [comment]
https://github.com/hoburg/gpkit/blob/master/gpkit/build.py#L177

**Comment by bqpd** [comment]
I think the particular issue is that a 32bit python can still use a 64bit mosek_cli, so the error is actually incorrect.
