### ISSUE TITLE
windows mingw install instructions not working

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#774]
after adding gcc to the path...

```
C:\Program Files\Mosek\7\tools\platform\win64x86\bin\mosek64_7_1.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
```

**Comment by bqpd** [comment]
mingw64 on this machine appears to have installed itself to the 32-bit program files folder, sheesh. It might just be a 32/64bit error.

**Comment by bqpd** [comment]
@galbramc, the test machines have 32-bit or 64-bit mosek?

**Comment by galbramc** [comment]
the windows 10 machine has 64-bit mosek. I have not been able to use 32-bit mosek on windows

**Comment by bqpd** [comment]
Hmmk. I think it's mingw's fault here...

**Comment by galbramc** [comment]
What do you get from running gcc --version

**Comment by whoburg** [comment]
do we know how to reproduce this?

**Comment by bqpd** [comment]
Nope, I need to do some Windows test installs; we haven't seen this come up again from @pgkirsch's side, though. @pgkirsch, what c compiler do you use to install mosek?

**Comment by pgkirsch** [comment]
I don't use Mosek (can't get academic license for a company)

On Nov 18, 2016, at 15:12, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope, I need to do some Windows test installs; we haven't seen this come up again from @pgkirsch<https://github.com/pgkirsch>'s side, though. @pgkirsch<https://github.com/pgkirsch>, what c compiler do you use to install mosek?

**Comment by bqpd** [comment]
ah, of course!

**Comment by bqpd** [comment]
Subsumed by #970
