### ISSUE TITLE
Installation instructions > installing cvxopt

### ISSUE THREAD

**Issue by tonystao** [hoburg/gpkit#775]
CVXOPT package installation instructions on gpkit.readthedocs is incomplete. Need to install BLAS and LAPACK via: 

`sudo apt-get install libblas-dev liblapack-dev`

before running `sudo pip install cvxopt`. 
(on Ubuntu)

**Comment by whoburg** [comment]
Does @galbramc agree?

**Comment by galbramc** [comment]
Yes that is correct. We have those packages installed on all our testing machines for other codes, so I didn't realize they were needed for cvxopt as well.

**Comment by whoburg** [comment]
@aechevarria1, this should be fairly easy to add to the docs.

**Comment by whoburg** [comment]
this was fixed by #934
