### ISSUE TITLE
Install permissions error

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#777]
I was installing on OSX 10.11.5 and get the following permissions error. I got around this by running the commands with sudo, but seems like it might be worth looking into why this occurred. The permissions on `~/.gpkit/expopt.so` were the same on my computer and Woody's (but Woody doesn't see this permissions error on his machine). My python version is 2.7.12 and my shutil is coming from `'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.pyc'`

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7d/1mt4zdqx4433fkghc5rxrc3h0000gn/T/pip-build-5vTY0r/gpkit/setup.py", line 9, in <module>
        build_gpkit()
      File "gpkit/build.py", line 299, in build_gpkit
        solvers = [CVXopt(), Mosek(), MosekCLI()]
      File "gpkit/build.py", line 90, in __init__
        self.installed = self.build()  # pylint: disable=not-callable
      File "gpkit/build.py", line 238, in build
        solib_dir = replacedir(pathjoin(os.path.expanduser("~"), ".gpkit"))
      File "gpkit/build.py", line 41, in replacedir
        shutil.rmtree(path)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
        onerror(os.remove, fullname, sys.exc_info())
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
        os.remove(fullname)
    OSError: [Errno 13] Permission denied: '/Users/mayork/.gpkit/expopt.so'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7d/1mt4zdqx4433fkghc5rxrc3h0000gn/T/pip-build-5vTY0r/gpkit/
```

**Comment by whoburg** [comment]
@galbramc, does the OSX ElCap machine require sudo anywhere during the install process?

**Comment by galbramc** [comment]
Ahhh, yeah I got so used to using virtualenv that I forgot you need to use sudo on the easy_install and pip commands in the install instructions if you are installing all the packages in your system. 

So what happened here is you ran ```sudo pip install gpkit```, which means gpkit created ```~/.gpkit/expopt.so```. If you run ```ls -l ~/.gpkit``` is expect the owner and group to be root. The simple fix here is to run ```sudo chown -R mayork: ~/.gpkit``` it will fix the permission problem. 

I'm guessing we should add --user to the pip commands in the install instructions, or recommend virtualenv. Not sure what the preferred solution is.

**Comment by whoburg** [comment]
@mayork, can you check on your machine whether `pip install --user gpkit` avoids the need for sudo?

**Comment by mayork** [comment]
I  ran `sudo chown -R mayork: ~/.gpkit` this morning...in any case that didn't seem to fix the permissions problem and neither did running `pip install --user gpkit`, I still had to use sudo

**Comment by whoburg** [comment]
ok, so based on that we should probably update the docs to suggest that if not using a virtualenv, i.e. if installing directly to the system python, then sudo will be needed.

Any volunteers?

**Comment by mayork** [comment]
I was going to try add to the docs some after next week so I could do this then as well

**Comment by galbramc** [comment]
can you show me the output from running ```ls -l ~/.gpkit``` and ```ls -ld ~/.gpkit```

**Comment by mayork** [comment]
`s -l ~/.gpkit` yields

```total 96```

and 'ls -ld ~/.gpkit` yields
```
drwxr-xr-x  3 root  staff  102 Aug  4 13:59 /Users/mayork/.gpkit
```

**Comment by galbramc** [comment]
Hmm, still says that root owns the directory. Try ```sudo chown mayork ~/.gpkit```.

**Comment by mayork** [comment]
`chown: /Users/mayork/.gpkit.: No such file or directory`

**Comment by galbramc** [comment]
You copied the period on the end of my sentence. don't include that in the command.

```sudo chown mayork ~/.gpkit```

**Comment by mayork** [comment]
wow i'm an idiot didn't think that made sense...now it returns nothing...I ran this `$ sudo chown mayork ~/.gpkit`

**Comment by mayork** [comment]
```
dhcp-18-111-68-18:~ mayork$ ls -l ~/.gpkit
total 96
-rwxr-xr-x  1 root  staff  48740 Aug  4 13:59 expopt.so
dhcp-18-111-68-18:~ mayork$ ls -ld ~/.gpkit
drwxr-xr-x  3 mayork  staff  102 Aug  4 13:59 /Users/mayork/.gpkit
```

looks like it worked

**Comment by galbramc** [comment]
Almost, you see expopt.so is still owned by root.

```chown mayork ~/.gpkit/*```

that should take care of it. Double check with the ls commands.

**Comment by mayork** [comment]
```
ls -l ~/.gpkit
total 96
-rwxr-xr-x  1 mayork  staff  48740 Aug  4 13:59 expopt.so
dhcp-18-111-68-18:~ mayork$ ls -ld ~/.gpkit
drwxr-xr-x  3 mayork  staff  102 Aug  4 13:59 /Users/mayork/.gpkit
```

ah right this looks good now though

**Comment by galbramc** [comment]
Yep, that looks good. Everything should work now.

**Comment by mayork** [comment]
just had to run sudo when I did `python setup.py install` to install a new branch...

**Comment by galbramc** [comment]
Yeah you are installing into your system python, you will always need to run sudo when you do that. If you use a virtualenv you will not need to use sudo.

**Comment by mayork** [comment]
ah I see good to know

**Comment by galbramc** [comment]
Or if you add --user to just install in your home directory.

**Comment by mayork** [comment]
updated docs to reflect needing to run sudo...changes are on the branch mymods

**Comment by bqpd** [comment]
changes merged.
