### ISSUE TITLE
don't print top level model anywhere

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#780]

**Comment by whoburg** [comment]
i.e. don't print the top-level model.

**Comment by whoburg** [comment]
should we also take this a step further and not append model names to varkeys until needed, by having Model.__init__ call a method on any submodels asking them to name themselves?

**Comment by bqpd** [comment]
Quite possibly!

**Comment by bqpd** [comment]
I am now shying away from this: I think we should always print modelnames, but we should not print them in variables names.

**Comment by whoburg** [comment]
Yeah, it's really the variable names / subscripts that are an issue. I recall this especially being a problem in some early latex printouts, for example.
