### ISSUE TITLE
GPs should not accept varkeys/monomials as values in their substitutions

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#782]

**Comment by whoburg** [comment]
... whereas varkeys/monomials used as values in a substitution dict passed to `solve()` or `ConstraintSet.__init__` will raise an informative error.

**Comment by bqpd** [comment]
Highly related to #781

**Comment by bqpd** [comment]
After retitle, so highly related it supersedes.

**Comment by whoburg** [comment]
shouldn't it be "as values" instead of "as keys"?

**Comment by bqpd** [comment]
oops yes!
