### ISSUE TITLE
Model.__getitem__ should return highest-level varkey

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#786]
list of varkeys all with the same name should be in `.byname`. Also there could be a fuzzy search, `.search("W wing")` which would get all of `W_wing`, `W with model=['wing']`, `W descr="wing weight"` and return a list sorted by relevance (or just the most relevant)

**Comment by whoburg** [comment]
👍 , this will avoid danger associated with the fact that in the constraint `T0 >= T1 + T2 + submodel["T"]`, submodel["T"] currently might return a Variable or a list, depending on the submodel's varkeys.
