### ISSUE TITLE
in boundendess debugging tool allow only upper or lower bounding

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#796]

**Comment by bqpd** [comment]
What's the idea behind this?

**Comment by bqpd** [comment]
@mayork, is this issue still open? what's your desired use case for this?

**Comment by mayork** [comment]
sometimes when models are dual infeasible they will solve in a BCS but none of the variables will be near the upper or lower bound. At one point I encountered this and lower bounded all the variables. It ended up being informative.

I haven't really looked at the BCS code but I thought maybe a keyword would allow for only upper or lower obunding

**Comment by bqpd** [comment]
yeah! this will be an easy thing to add.

**Comment by whoburg** [comment]
I have a vague recollection that we found and fixed an early bug in `Bounded` in which we weren't properly looping through the `nu`'s and/or `lambda`'s to generate the final "sensitive to" printout. I wonder if maybe that could explain the (odd) behavior @mayork observed where using only an upper or lower bound was somehow more informative.

**Comment by bqpd** [comment]
This exists in #1021! Syntax is `Bounded(cset, lower=0.01)`, etc
