### ISSUE TITLE
Control panel not rendering well

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#798]
Trying to interact with a model using `.controlpanel()` in an ipython notebook and things aren't rendering well. The slider is very narrow and the units overlap with the value in some cases. See attached screenshot for an example. I have tried different browsers (Chrome and IE) with no luck. This may be a Windows issue, but any suggestions would be greatly appreciated! @mayork any similar experiences?

![bad_sliders](https://cloud.githubusercontent.com/assets/8702579/17445180/7ca21dd8-5af8-11e6-9cbb-83ce105af805.PNG)

**Comment by bqpd** [comment]
eww. You could try changing the css on line 117-126 of interactive/widgets.py, or the slide-width setting on line 49

**Comment by pgkirsch** [comment]
Hmmm no luck yet, but I'll keep exploring. By the way, are you aware of this:
![latex_widget_deprecated](https://cloud.githubusercontent.com/assets/8702579/17446950/ad7e4b22-5b00-11e6-8ddf-5c9bc9974440.PNG)


Does it require a new issue?

**Comment by bqpd** [comment]
Ack, looks like a new version of ipywidgets. Good to know.

**Comment by pgkirsch** [comment]
Proposed solution is to not use PythonXY (or not support 32-bit machines?)

**Comment by whoburg** [comment]
@pgkirsch, can you post a little more info on what you know about this? (OS versions, installation settings, how to reproduce, etc?) It sounds like there are a lot of variables in the mix so I think we need to narrow down what's going on a bit before closing this.

**Comment by pgkirsch** [comment]
Windows 7 (64 bit), I followed the Python(x,y) installation instructions for cvxopt, and installed GPkit from source, and later installed ipywidgets  using pip, however it generated some errors in a way that broke ipython to an extent (when I tried to start an ipython shell, it crashed). The problem occurred in every browser I tried. I feel like it has something to do with the 32-bit python(x,y) but could easily be wrong.

**Comment by whoburg** [comment]
Ok so just to be clear the ipython notebook issue occurs after being in a state where typing `ipython` at a terminal causes the terminal (or ipython) to crash?

My hope is that we can reproduce this independent of GPkit, i.e. show that installing ipywidgets can lead to a broken ipython. If so, we can close this.

**Comment by bqpd** [comment]
@pgkirsch, what do you get from `pip show ipywidgets`?

**Comment by pgkirsch** [comment]
Unfortunately I have cleansed my work machine of all the evil (PythonXY), so I can't reproduce it without asking IT to help re-install it, which I would prefer not to do. Does anyone else in the group have Windows 7 or Windows 7 emulation capabilities?

**Comment by whoburg** [comment]
I propose we close this for now as potentially caused by an ipython issue that's independent of GPkit; please reopen if anyone observes this again.

**Comment by bqpd** [comment]
Debugged this. They changed the way width is assigned to sliders in the new ipywidgets. (grumble grumble backwards compatibility)


```python
# line 49 of interactive/widgets.py
                floatslider.width = "20ex"
```

That width now applies to the entire slider box, not just the slider. Increasing that number (or removing that line and using the default) fixes this.

**Comment by bqpd** [comment]
Still looking for a fix that's backwards compatible on our end.

**Comment by whoburg** [comment]
gotcha, thanks for debugging!

This is gross, but should we set `floatslider.width` based on a conditional involving the ipywidgets version number, and add a TODO to take it out when the old one is a super stale version?

**Comment by whoburg** [comment]
or, would removing that line and using default be backwards compatible for us?

**Comment by bqpd** [comment]
Yeah, I think that's our best bet for now...it looks like there's a new property that's just the slider itself in the new version.

**Comment by bqpd** [comment]
Should I make that PR?

**Comment by bqpd** [comment]
Pushed that change to https://github.com/hoburg/gpkit/tree/sliderwidth if you decide it looks like a reasonable solution.

**Comment by whoburg** [comment]
thanks - looks great to me. I'm going to merge that change now.

**Comment by whoburg** [comment]
@pgkirsch, try now on master, and close this if you like it?

**Comment by bqpd** [comment]
pining @pgkirsch

**Comment by pgkirsch** [comment]
My bad. I'm not in a position to try it out with the old setup (PythonXY), but it looks fine with my current setup, I actually kind of like the wide sliders.
