### ISSUE TITLE
code to profile...very slow at result packing

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#801]
thought it might be interesting to profile the code at this commit https://github.com/hoburg/gpkit-models/pull/73/commits/20147d3f71d0946a33960c0e5829844a7654ba40

The model is 738 variables and it takes 21 gp solves w/Mosek. The code solves in 28 seconds...each solve takes about 0.05 seconds, but result packing takes about 130% of the solve time for most iterations. 

If this is normal when using Mosek just let me know and I'll close the issue

**Comment by whoburg** [comment]
Thanks -- this is a priority issue. What's also interesting is that something is taking a long time outside of what we print out timing info for:

if result packing takes 130% of a 0.05 second solve time, then that's 0.05 + 0.065 = 0.115 seconds per iteration, so 28 iters should take < 4 seconds. But @mayork reports 28 seconds...

**Comment by bqpd** [comment]
That model does not work on the current master. :(

**Comment by bqpd** [comment]
Closing for now, will profile with code at https://github.com/hoburg/gpkit-models/issues/8#issuecomment-264752421
