### ISSUE TITLE
access initial guesses of an SP that doesn't solve

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#802]
is there a way to see the what the initial guess is for an SP solve?

@whoburg also mentioned a way to possibly choose your own initial guess...I'd be really interested in using that on the integrated flight profile and engine model and could help test stuff if that would be helpful

**Comment by bqpd** [comment]
Yup! It's stored in the solution as "startpoint"

**Comment by bqpd** [comment]
If that's blank, it means it started with a guess of 1 for everything.

**Comment by mayork** [comment]
is there a way to see it if the problem never solves?

**Comment by bqpd** [comment]
`sol["startpoint"]` should get it...

**Comment by mayork** [comment]
okay sounds good. guess its starting with a guess of 1.

if a sol is never generated tho, like a problem hits the iteration limit, can I see this somehow with something like gps?

**Comment by bqpd** [comment]
it should raise a RuntimeWarning with that message, then.

**Comment by mayork** [comment]
right, it does, but I'd still like to see what the initial guess was

**Comment by bqpd** [comment]
Ooh. Good call. Unless you're intentionally declaring a start point it'll be all ones, but this feature should definitely exist.

**Comment by mayork** [comment]
ah okay. no chance running with boundedness debugging tool changes the inital guess then?

**Comment by bqpd** [comment]
nope, sorry. I realized though that the boundedness constraint set as written now does not recurse, but it probably should.

**Comment by bqpd** [comment]
Nope. :-/

**Comment by mayork** [comment]
no worries, just a theory about some behavior I'm observing right now

**Comment by whoburg** [comment]
I think we should implement something called `x0s` (parallel to `gps`) that gives the initial guess at every iteration. This could be useful for debugging (to recreate the approximations done). As far as I can tell it's hard to get this info (and awkward to look up from `gp.result for gp in gps` because one needs to figure out which variables appear in negys).

**Comment by bqpd** [comment]
How about storing it as `gp.x0`?

**Comment by whoburg** [comment]
sure, attaching an `x0` attribute to every gp in `SignomialProgram.gps` sounds good.
