### ISSUE TITLE
remove sol.sens

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#806]
I can't figure out how to access a sensitivity...no matter what I try I get a key error. Here it is for one of the examples in the gpkit docs

```python
In [20]: x = gpkit.Variable("x")

In [21]: x_min = gpkit.Variable("x_{min}", 2)

In [22]: sol = gpkit.Model(x, [x_min <= x]).solve()
Using solver 'cvxopt'
Solving for 1 variables.
Solving took 0.0114 seconds.

In [23]: assert sol.sens(x_min) == 1
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-f25f4b83c012> in <module>()
----> 1 assert sol.sens(x_min) == 1

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/solution_array.pyc in sens(self, key)
     76     def sens(self, key):
     77         "Returns sensitivity of the given variable (unitless)."
---> 78         return NomialArray(self["variables"]["sensitivities"][key])
     79 
     80     def table(self, tables=("cost", "sweepvariables", "freevariables",

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/keydict.pyc in __getitem__(self, key)
     94         keys = self.keymap[key]
     95         if not keys:
---> 96             raise KeyError("%s was not found." % key)
     97         values = []
     98         for key in keys:

KeyError: 'sensitivities was not found.'
```

any help would be much appreciated...really need to access some sensitivies right now

**Comment by bqpd** [comment]
For right now you can access them with the dictionaries structure:
sol["sensitivities"]["constants"][x_min]

**Comment by mayork** [comment]
got it thanks, much appreciated. Is this a permanent change or will it go back to the previous way at some point?

**Comment by bqpd** [comment]
Naw, it's a bug! This should have been unit tested...

**Comment by bqpd** [comment]
Actually, tempted to remove `sol.sens`...@mayork, I think you're the only one who has wanted to use it, would you mind if I did?

**Comment by mayork** [comment]
Is there another way to pull the sensitivities out and plot them when sweeping? I know there's the sensitivity plotting tool but I'd like to make a few custom plots

**Comment by bqpd** [comment]
there's always `sol["sensitivities"]["constants"]`

**Comment by mayork** [comment]
That'll work fine, feel free to dump sol.sens

**Comment by mayork** [comment]
@mjburton11
