### ISSUE TITLE
signomial program w/no trust region does not terminate

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#808]
How does gpkit decide that a signomial program is at the optimal point and stop solving it? I keep running into models that run seemingly forever and are primal feasible every solve. I just ran one model for 500 iterations and the cost after the 500th solve was
![image](https://cloud.githubusercontent.com/assets/6796415/17480143/6ce426d6-5d44-11e6-933e-5eb859cecaac.png). Running the exact same model for 1500 interations the cost at termination was 
![image](https://cloud.githubusercontent.com/assets/6796415/17480165/7f25cf5c-5d44-11e6-9598-2127468499ee.png). The cost makes physical sense for the problem. I'm not sure I believe that the change in the cost is something other than numerical errors accumulating over 1,000 iterations.

**Comment by mayork** [comment]
@whoburg or @bqpd anythoughts on this? It's preventing me from doing a few sweeps across altitude

**Comment by whoburg** [comment]
looking

**Comment by mayork** [comment]
the code was on the commercial sizing branch comit 2256aea...the file to run is Commerical_Flight_Profile_alt_sweeps.py

**Comment by whoburg** [comment]
There's something strange going on with this model: the cost is bouncing back and forth by about 3% every SP iteration:

```python
In [8]: [gp.result["cost"] for gp in m.program.gps if gp.result is not None]
Out[8]:
[None,
 None,
 3782.141688923044,
 None,
 None,
 None,
 922292.8665515694,
 395756.369675086,
 None,
 115026.19442412675,
 178537.15738140553,
 229403.96569277905,
 231170.74367403315,
 216230.25026980691,
 229930.10049234226,
 215577.73536430477,
 229821.81073440774,
 215524.1431134788,
 229816.6112359477,
 215499.48395317158,
 229814.42247986203,
 215491.2712866609,
 229813.6500532619,
 215488.96258315793,
 229813.42598232577,
 215488.36585500705,
 229813.36710639604,
 215488.21834730165,
 229813.35245427553,
 215488.18285956228,
 229813.34887086725,
 215488.17459905738,
 229813.3480230247,
 215488.17268325464,
 229813.34783110535,
 215488.17174636046,
 229813.34780991205,
 215488.17190668988,
 229813.3478112825,
 215488.17205377689,
 229813.34776915432,
 215488.1718026783,
 229813.34779038068,
 215488.17190456964,
 229813.34779487937,
 215488.17192374557,
 229813.34778274677,
 215488.17194895688,
 229813.34778488672,
 215488.17197894838,
 229813.34777783454,
 215488.1718796925,
 229813.34779391924,
 215488.17184994102,
 229813.34780447933,
 215488.17174583222,
 229813.34778360894,
 215488.1716004111,
 229813.347807597,
 215488.17181871503,
 229813.34777610732,
 215488.17208225638,
 229813.34780252146,
 215488.17169674707,
 229813.347769614,
 215488.17178405548,
 229813.34780601264,
 215488.17193646432,
 229813.34777683273,
 215488.17183637668,
 229813.34778439888,
 215488.17173691947,
 229813.347786022,
 215488.17176659594,
 229813.34778092118,
 215488.1718729892,
 229813.34779704505,
 215488.17170931768,
 229813.3477775745,
 215488.17197923354,
 229813.34777914453,
 215488.17194257892,
 229813.34776938456,
 215488.1720966196,
 229813.34780470713,
 215488.17174663223,
 229813.3478130783,
 215488.17193505223,
 229813.34780030517,
 215488.1715779723,
 229813.3477887747,
 215488.1718217394,
 229813.3477922618,
 215488.17203145637,
 229813.3478235833,
 215488.17177430063,
 229813.34777267,
 215488.17185583204,
 229813.34777691358,
 215488.17174005677,
 229813.34778729445,
 215488.171998847,
 229813.3478153342,
 215488.17186587516,
 229813.3478144471,
 215488.17172043145,
 229813.34779509492,
 215488.17206872843,
 229813.34779921683,
 215488.17208901636,
 229813.34778921478,
 215488.17182395956,
 229813.34778744183,
 215488.17170202642,
 229813.3477830117,
 215488.1718294437,
 229813.3477916115,
 215488.17206469848,
 229813.34780741573,
 215488.17191907944,
 229813.34778832566,
 215488.17181511878,
 229813.34778875878,
 215488.1717508413,
 229813.3477992552,
 215488.17169881793,
 229813.34776355585,
 215488.1718900001,
 229813.3477911306,
 215488.17197651233,
 229813.3477937951,
 215488.1719664589,
 229813.34779382165,
 215488.17200633846,
 229813.34781599144,
 215488.17197708652,
 229813.3478222851,
 215488.17185884455,
 229813.34779049907,
 215488.1717671793,
 229813.3477967164,
 215488.17203313948,
 229813.3477865584,
 215488.17180942488,
 229813.34781198791,
 215488.17193097482,
 229813.3477972214,
 215488.17194831648,
 229813.34778278146,
 215488.17196096518,
 229813.34780846856,
 215488.1718515219,
 229813.34780283007,
 215488.17198369183,
 229813.3477956101,
 215488.17192287513,
 229813.34778002306,
 215488.17186839043]
```

**Comment by whoburg** [comment]
The two solutions it's bouncing between are quite different (freevariables different by up to a factor of two; sensitivities different by up to 0.43.

This smells to me like a possible SignomialEquality issue that @mopg might be interested in. In the meantime, @mayork is there any way to turn any of the SignomialEqualities into SignomialInequalities?

**Comment by mayork** [comment]
I'll check into that, now that the model has evolved I think more realistic pressures exist so I can probably relax a few of those constraints. Unfortunately, I don't think the signomial equalities in the engine code can be removed.

**Comment by mayork** [comment]
cvxopt does the same thing...just flips between the points 215539.9958 and 229818.8167

**Comment by whoburg** [comment]
yep, would be surprised if choice of solver to make a difference here - the solvers only solve GPs, not SPs.

**Comment by mayork** [comment]
I tried removing a few of the signomial equalities but the model wen't dual feasible when I did. This problem arose when I changed the L/D constraint from `LD[icruise2]  == 17` to `LD[icruise2]  == Wstart[icruise2]/D[icruise2]`...does that still make you think it's a signomial equality problem?

**Comment by mopg** [comment]
Sometimes when you change the objective function, you change pressure in the problem and an equality constraint could cause a problem. I’m currently merging the current master branch into my branch which implements different methods for signomial equality constraints. So when I’ve done that, perhaps you can use one of the other methods for a few constraints. Not sure it will work though. I’ll let you know when I’m done.

**Comment by mopg** [comment]
Ok, if you pull the equality branch, you can instead of SignomialEquality, use SignomialEqualityLinTrust or SignomialEqualityTrivTrust. These are trust region methods, and therefore they are slower. I've attached an example of how to use them. Note that you do need to set "trust region" for each constraint using these methods (otherwise it defaults to 0.9). 

I've also attached a paper about this (which we'll submit within the next week or so), so perhaps that can give you some insight.

`import gpkit 
import time
x = gpkit.Variable('x')
y = gpkit.Variable('y')

ymin = gpkit.Variable('ymin',4)

# must enable signomials for subtraction
with gpkit.SignomialsEnabled():
	constr = [gpkit.nomials.SignomialEqualityLinTrust(x,1+y),
			y >= ymin]

objective = x

constr[0].trustregion = 0.50

m = gpkit.Model(objective, constr)

t1 = time.clock()
sol = m.localsolve(verbosity=2, x0={x.key:1,y.key:1}, iteration_limit=101)
dt = time.clock() - t1

print len(m.program.gps)
print m.program.soltime
print m.program.result['cost']
print abs(sol['cost'] - 5)
print m.program.result["constr_viol"]`

The constr_voil might be useful to determine whether all constraints are properly satisfied, especially important for SignomialEqualityTrivTrust. 
[main.pdf](https://github.com/hoburg/gpkit/files/407687/main.pdf)

**Comment by mayork** [comment]
great, thank you! I read that paper a few weeks ago, pretty interesting. I talked with Woody about the model this afternoon and we have a good idea how to proceed. In a bit of a crunch right now to get some stuff together for a presentation, but after we're done I'll go back and run the problematic code with the trust region methods and see what insight that gives

**Comment by whoburg** [comment]
Thanks @mopg !

**Comment by bqpd** [comment]
What's the status of this issue?

**Comment by mayork** [comment]
@1ozturkbe

**Comment by whoburg** [comment]
I think @mayork was going to go back and try to gain some physical insight about what solutions this is bouncing back and forth between. A goal is to find a small but non-contrived MWE of an SP algorithm bounding back and forth in this way, to give insight about what's happening.

**Comment by mayork** [comment]
@1ozturkbe and I are going to be looking into this issue in more detail. Step 1 is for me to more deeply look at the differences in the two solutions. Step 2 is to go back and run this with a signomial equality that has a trust region and see what happens.

**Comment by bqpd** [comment]
@mayork, @1ozturkbe, what's the status of this?

**Comment by 1ozturkbe** [comment]
Since we have switched to the relaxed_constants solve we have not experienced the same behavior. And I don't think we can replicate the error we had without backtracking a bunch, and it was likely due to the ill-conditioning of the problem than some solver error. The models have since gotten better and it is likely that we won't have similar 'cycling'. @mayork what are your thoughts?
