### ISSUE TITLE
cvxopt installation works on 64-bit Windows 7

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#811]
Possibly related to #730.

If I have 64-bit Windows 7 and I want to use cvxopt then Anaconda is the way to go, and I found it to be much faster/less cumbersome than the PythonXY installation method. The PythonXY installation generated errors for me when trying to work with ipywidgets, and even when the installation works there were rendering issues with `controlpanel` (#798). These issues go away with the Anaconda installation method.

**Steps:**
1. Download and install [Anaconda](http://www.continuum.io/downloads#_windows), as per the installation instructions for MOSEK.
2. `conda install -c https://conda.anaconda.org/omnia cvxopt`
3. `pip install gpkit`
(4. `pip install ipywidgets`)

EDIT:
5. `unzip cvxopt-1.1.8-py2.7-win-amd64.egg` (in `site-packages`)
6. `mv EGG-INFO/ cvxopt-1.1.8-py2.7-win-amd64.egg-info/` (also in `site-packages`)

Obviously this isn't an issue, but maybe this can stay open until the documentation is updated accordingly? Unless there is a reason this solution isn't preferable?

**Comment by pgkirsch** [comment]
As discovered in #812, this installation results in very long solve time. See #812 for more detailed explanation, but I have amended the original ticket above accordingly.

**Comment by whoburg** [comment]
Thanks @pgkirsch for all the info.

I'm losing track of all the known incompatibilities with Windows versions, anaconda/pythonXY, and solvers. I think the docs would benefit from a table of suggested installation methods, with OS version on one axis and solver on the other. Hopefully most cells are green "anything works", but some of the windows cells would state "anaconda recommended", or "Python XY recommended", or link to more detailed discussions of known issues. These cells could also function as links to the relevant section of the installation instructions.

If others like this too, maybe @aechevarria1 could take a shot at it.

**Comment by aechevarria1** [comment]
Okay, how about something like this?
![table](https://cloud.githubusercontent.com/assets/10841125/17827892/2e6a01d8-6653-11e6-9317-039d9ac130a1.png)

If this looks good, any preferences on font size, color, or boldness? Also which solvers work for which OS's, and what would you want to go into the cells that aren't green?

**Comment by whoburg** [comment]
Looks nice, although I'd with an html table instead of plotly in this case so we get the css from read the docs. Also, no need for the Mosek CLI column, it will be the same as Mosek for this purpose.

**Comment by aechevarria1** [comment]
Okay, we could do something like this then
![image](https://cloud.githubusercontent.com/assets/10841125/17907906/fd81449a-694b-11e6-9480-7b0a11a5cc68.png)

Now do I need to make the html work with python, or is there a way to paste in directly the html code?

**Comment by whoburg** [comment]
No, much easier, just put it sphinx directly via rest: http://rest-sphinx-memo.readthedocs.io/en/latest/ReST.html#tables

**Comment by bqpd** [comment]
wait ugh do you really have to unzip the package. This will be fun to put in the install instructions...

**Comment by bqpd** [comment]
documented, should be checked as part of #970

**Comment by emergencyd** [comment]
I really want to know, why would "conda install -c https://conda.anaconda.org/omnia cvxopt" work?
I've tried "conda install cvxopt", but failed on both python2.7 & python 3.6

**Comment by bqpd** [comment]
It worked years ago, but now there's windows binaries on pip, so I'm not sure anyone's maintaining the conda package!
