### ISSUE TITLE
have m.program.gps[x].result be able to print a table

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#819]
this could make debugging a lot more user friendly

**Comment by whoburg** [comment]
@bqpd, should we give `SolutionArray` an init, such that it's possible to do

`print SolutionArray(m.program.gps[i].result).table()`

**Comment by bqpd** [comment]
Ooh yes we should

**Comment by whoburg** [comment]
ok that sounds straightforward, let's gitrdone

**Comment by whoburg** [comment]
+ unit test for initializing a SolutionArray this way

**Comment by whoburg** [comment]
Reopening due to #921
