### ISSUE TITLE
A ConstraintSet without any constraints

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#821]
This might sound like a bizarre request, but hear me out. Say I am modelling a system and I want to try interchanging different subsystem models. One of the subsystem models just makes the design variables fixed values. Would it be unreasonable to ask for the following to work:

``` python
In [1]: from gpkit import Variable, ConstraintSet

In [2]: x = Variable('x')

In [3]: y = Variable('y')

In [4]: constraints = []

In [5]: substitutions = {'x': 100, 'y': 200}

In [6]: ConstraintSet(con
%config      constraints  constraints= continue

In [6]: ConstraintSet(cons
constraints  constraints=

In [6]: ConstraintSet(constraints, sub
substitutions  substitutions=

In [6]: c = ConstraintSet(constraints, substitutions)

In [7]: c
Out[7]: gpkit.ConstraintSet()

In [8]: c.substitutions
Out[8]: {}
```

Currently, a not unreasonable workaround is to do the following:

``` python
In [9]: constraints = [x == x, y == y]

In [10]: c = ConstraintSet(constraints, substitutions)

In [11]: c
Out[11]:
gpkit.ConstraintSet(
        x = x
        y = y)

In [12]: c.substitutions
Out[12]: {x: 100, y: 200}
```

Maybe this is just how it should be. Interested to hear other thoughts though.

The only real requirement I have is that I want to be able to import this `ConstraintSet` into a `LinkedConstraintSet` just like any other model so it really feels interchangeable.

**Comment by bqpd** [comment]
@whoburg was asking for this a year ago kinda. Something like this should probably exis, as part of figuring out the right way for a model to include variables that aren't used in it.

**Comment by bqpd** [comment]
This now exists on master! See https://gpkit.readthedocs.io/en/latest/modelbuilding.html

**Comment by whoburg** [comment]
Example (from the docs):

```python
class FlightState(Model):
    "Context for evaluating flight physics"
    def setup(self):
        Variable("V", 40, "knots", "true airspeed")
        Variable("\\mu", 1.628e-5, "N*s/m^2", "dynamic viscosity")
        Variable("\\rho", 0.74, "kg/m^3", "air density")
```

now, one can do, for example:

```python
fs = FlightState()
fs["\\mu"]  # A Variable, can be used in creating constraints
```
