### ISSUE TITLE
Sub in place w/vector variables

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#822]
I'm trying to use subinplace with vector variables. I have two vector variables in different models. They are 

```
hClimb1 = VectorVariable(2, 'hClimb1', 'm', 'Altitude [meters]')
```
and 
```
 h = VectorVariable(2, 'h', 'm', 'Altitude [meters]')
```
inside subinplace I'd like to just put `'h': 'hClimb1'` and link each index but that doesn't work. I also tried to individually link each index `'h_(0,)': 'hClimb1_(0,)'` and that didn't work. In both cases I get the following error
```
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/nomials/substitution.pyc in append_sub(sub, keys, constants, sweep, linkedsweep)
     61                                  " variable %s of shape %s." %
     62                                  (sub.shape, key.str_without("model"),
---> 63                                   key.shape))
     64         if not sweepsub:
     65             try:

ValueError: cannot substitute array of shape () for variable h_Atmosphere_(0,) of shape (2,).
```
@bqpd any idea what I'm doing wrong?

**Comment by mayork** [comment]
also, does linked constraint set not link vector variables with the same varkey? It seems like its not...

**Comment by bqpd** [comment]
@whoburg has a workaround for this, but yeah it's currently a bug.

**Comment by whoburg** [comment]
this seems like a priority, @bqpd what would it take to get this working?

**Comment by bqpd** [comment]
Hmm, I don't think much. I'll get it today.

**Comment by bqpd** [comment]
Okay, so this is working as intended I think, because this works:

```python
x = gpkit.VectorVariable(3, "x")
y = gpkit.VectorVariable(3, "y")
m = gpkit.Model(x.prod(), [x >= range(1,4)])
m.subinplace({"x": y})
```

The trick is that you're substituting a string for a string, and gpkit looks up the key string and gets the corresponding vector variable, but does not look up the value string. I'm not sure if it should, either?

**Comment by bqpd** [comment]
The bigger issue is that right now `m["x"]` does not return a nomial array, so you can't just do `m.subinplace({m["x"]: m["y"]})`

**Comment by mayork** [comment]
the problem I was having was using subinplace on one index of a vector variable, like this

```python
x = VectorVariable(3, "x")
m = Model(x.prod(), [x>=1])
m.subinplace("x_(0,)": "y")
```

which gives this error
```
ValueError: cannot substitute array of shape () for variable x_(0,) of shape (3,).
```

**Comment by bqpd** [comment]
Right, and the problem there is that you should be substituting

```python
x = VectorVariable(3, "x")
y = gpkit.Variable("y")
m = Model(x.prod(), [x>=1])
m.subinplace(m["x"][0]: y)
```

I think allowing string substitutions is potentially too 'magic', leading users to expect gpkit to know of variables that aren't in scope.

**Comment by bqpd** [comment]
The above works on https://github.com/hoburg/gpkit/tree/vectorget

**Comment by mayork** [comment]
I agree that's a much better set up

**Comment by bqpd** [comment]
@mayork, @whoburg, how do you feel about not allowing string substitutions anymore? You'd still be able to access solutions / set values in the substitutions dictionary with strings.

**Comment by mayork** [comment]
I take it this would apply to vector and non-vector variables? I think that's a really good idea because if you have a typo in a varkey when accessing it like `model["varkey"]` you will get an index error, so I think this negate the need for an invalid sub inplace warning.

**Comment by bqpd** [comment]
Yup! When doing `.subinplace({k: v, ...})` or `.sub({k: v, ...})`, k and v could no longer be strings.

**Comment by mayork** [comment]
I like that a lot better, seems far more user friendly to me and I don't think changing it now is going to cause too many backwards compatibility problems since I don't think this feature is used in too many models

**Comment by bqpd** [comment]
++ Implementing in the vectorget branch

**Comment by bqpd** [comment]
@pgkirsch's fmincon code uses string substitution to rename variables...

**Comment by whoburg** [comment]
great discussion guys, I'll review that PR soon.

**Comment by mayork** [comment]
since #830 was merged this can be closed, right?

**Comment by bqpd** [comment]
I think so, yeah. #857 is still relevant for the string stuff...

**Comment by mayork** [comment]
okay I'll close this then
