### ISSUE TITLE
calling solve w/SignomialEquality

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#828]
I just accidentally used solve on a model with a SignomialEquality. Instead of getting the usual message about needing to use localsolve I got this message
```
TypeError: SignomialEquality could not simplify to a PosynomialInequality
```
I'm not sure if that is intentional or not, but I found it rather confusing. It took me a while to realize I was using solve not localsolve because I'm accustomed to seeing the usual warning when I make that mistake

**Comment by whoburg** [comment]
was this on `master` or `equality`?

**Comment by mayork** [comment]
`master`

**Comment by whoburg** [comment]
ok good issue.

**Comment by bqpd** [comment]
The bug is that we're currently checking the exact error message in `geometric_program.py`. Proposed fix is the creation of a new Error type named `NotValidGPConstraint` or something similar.

**Comment by bqpd** [comment]
About to start implementing the above solution.

**Comment by whoburg** [comment]
sounds good.
