### ISSUE TITLE
refactor value_option in variables.py

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#843]
carry over from #841. See inline comments in ec7206a797876e8b07f9e83646772a741757be34. The logic surrounding the loop variable `value_option` used again later in `__new__` is confusing and possibly bug-prone.

**Comment by bqpd** [comment]
@galbramc and @whoburg , by the construction of the code, value_option is guaranteed to have a value which makes sense if values is truthy. I do think it could use a bit more clarity there, but `value_option` is not the problem.

**Comment by galbramc** [comment]
Yes it is, but the default value is actually "sp_init", and not None in case the 'if' statement inside the loop never evaluates to true. This is just a tad confusuing to parse out the logic that "sp_init" is the default only because its the last thing in the list in the for loop.
