### ISSUE TITLE
Check substitutions dict for phantom varkeys

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#848]
It's easy to forget to update the substitutions dict when changing a variable's varkey, or even to just type it in wrong. It might therefore be nice to have some kind of check to ensure that every entry in the substitutions dict is a varkey in the model that it's being used for. Sorry, I know there are concerns about model building speed and this won't help but it shouldn't be a particularly hard fix.

e.g.
```python
rho = Variable('\\rho')
...

substitutions = {
    ...
    'rho': 1.225,
    ...
}

m = Model(objective, constraints, substitutions)
# Should return an error, something like "The varkey 'rho' does not appear in model"
```
This will at least prompt a user to check the varkey for rho and notice it is wrong.

**Comment by bqpd** [comment]
Yup, definitely!

**Comment by bqpd** [comment]
I'm thinking the best place to do this is actually in KeyDict
