### ISSUE TITLE
KeyError: 'shape' after Substitutions

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#863]
Not sure if this is solved in #859 or another PR, but I got this error after doing some substitutions, and I'm not sure why.  I was running gasmale.md in the 1682master branch. 

```python
  File "gasmale.md.py", line 222, in <module>
    sol = M.solve("mosek") # check for solving errors
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/constraints/prog_factories.py", line 81, in solvefn
    result = solvefn(solver, verbosity, *args, **kwargs)
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/geometric_program.py", line 202, in solve
    self.result = self._compile_result(solver_out)  # NOTE: SIDE EFFECTS
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/geometric_program.py", line 272, in _compile_result
    result = {"freevariables": KeyDict(zip(self.varlocs, np.exp(primal)))}
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/keydict.py", line 43, in __init__
    self.update(*args, **kwargs)
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/keydict.py", line 48, in update
    self[k] = v
  File "/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/keydict.py", line 119, in __setitem__
    emptyvec = np.full(key.descr["shape"], np.nan, **kwargs)
KeyError: 'shape'
```

**Comment by bqpd** [comment]
I'm getting a different error.

**Comment by mjburton11** [comment]
That's really interesting...

**Comment by bqpd** [comment]
Nevermind, that was on master. I get this one on `82fixes1

**Comment by bqpd** [comment]
It works on setsubs with fixlinks merged in, or rather finds new bugs `t_{loiter}` seems to be unfixed these days?

**Comment by mjburton11** [comment]
Ok cool.  Can I merge setsubs with fixlinks with 82fixes?

**Comment by bqpd** [comment]
I'll make a branch like that just for you

**Comment by mjburton11** [comment]
Thanks!

**Comment by bqpd** [comment]
checkout `82fixplus`

**Comment by bqpd** [comment]
oops, just a sec

**Comment by bqpd** [comment]
Okay, try it now. I couldn't merge 82fixes, it was causing a different bug in the .md file

**Comment by bqpd** [comment]
On line 245 of the md file, there's an unnecessary `del M.substitutions["t_{loiter}"]` (it's already been deleted in line 230). The sweep after that wants to sweep a ridiculous number of passes, though, and I'm not sure why.

**Comment by mjburton11** [comment]
I don't think I had edited that var in the file yet...

**Comment by mjburton11** [comment]
So it works! It's trying to do a bunch of sweeps because it wanted to substitute that sweep in for every single mission segment.  I got around it by using 
```python
M.substitutions.update({"V_{wind}_Wind, Loiter, Mission, GasMALE": ("sweep"...)})
```

**Comment by bqpd** [comment]
Perfect.

**Comment by mjburton11** [comment]
Check out my new error: #865
