### ISSUE TITLE
multiple variable error for single variables

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#865]
For some reason I cant access `"h"` because it says it is a multiple variable.  Even though every time I create `h` in different models I create it with the exact same varkey, value and description. 

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-2f70e2315426> in <module>()
----> 1 M["h"]

/Users/mjburton11/Documents/SuperUROP/gpkit/gpkit/constraints/set.pyc in __getitem__(self, key)
     84             raise ValueError("multiple variables are called '%s'; use"
     85                              " variable_byname('%s') to see all of them"
---> 86                              % (key, key))
     87 
     88     def variables_byname(self, key):

ValueError: multiple variables are called 'h'; use variable_byname('h') to see all of them
```

**Comment by bqpd** [comment]
What do you get with `variable_byname('h')`, what commit, what file :D

**Comment by mjburton11** [comment]
This is the commit: 80a45fad62d0591d45d53ed91c268d174a684424.  Same file, `gasmale.md`.  Not sure how to run `variable_byname('h')`...

**Comment by bqpd** [comment]
oh, just do `print M.variable_byname('h')` the line before

**Comment by bqpd** [comment]
How could the error message make it clearer that this is what you should do?

**Comment by mjburton11** [comment]
That is what I tried, but it didn't work...

**Comment by bqpd** [comment]
Oh, typo. Should be variable*s*_byname

**Comment by mjburton11** [comment]
In that case, this is what I get: 
```python
[gpkit.Variable(h_Climb, Mission, GasMALE_(0,) [ft]),
 gpkit.Variable(h_Climb, Mission, GasMALE_(0,) [ft]),
 gpkit.Variable(h_Cruise, Mission, GasMALE_(0,) [ft]),
 gpkit.Variable(h_Cruise, Mission, GasMALE_(0,) [ft]),
 gpkit.Variable(h_Loiter, Mission, GasMALE_(0,) [ft]),
 gpkit.Variable(h_Loiter, Mission, GasMALE_(1,) [ft]),
 gpkit.Variable(h_Loiter, Mission, GasMALE_(2,) [ft]),
 gpkit.Variable(h_Loiter, Mission, GasMALE_(3,) [ft]),
 gpkit.Variable(h_Loiter, Mission, GasMALE_(4,) [ft])]
```

**Comment by bqpd** [comment]
looks like you have a lot of different elevations...which makes sense, right?

**Comment by mjburton11** [comment]
Yes.  That is true.  But if I'm trying to access the label this makes it difficult.

**Comment by mjburton11** [comment]
`M["h"].descr["label"]` should work right?

**Comment by bqpd** [comment]
`M[...]` no longer works if there's multiple possible answers, so I'd recommend `M.variable_byname("h")[0].label`
