### ISSUE TITLE
Posynomial Inequalities not pickleable after 0.4

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#867]
per @tonystao

**Comment by bqpd** [comment]
@tonystao it's because of pint

**Comment by bqpd** [comment]
I can make unitless posynomials / posynomial inequalities pickleable very easily, working on united ones...

**Comment by whoburg** [comment]
possibly related to https://github.com/hgrecco/pint/issues/349

**Comment by bqpd** [comment]
superseded by #927
