### ISSUE TITLE
Disambiguate identically-named models in table, solution array

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#868]
but how?

**Comment by whoburg** [comment]
can't we use `_nums`?

This is a current issue for the 1682 model (e.g. at https://github.com/hoburg/gpkit-models/commit/980a885ac45c4d622714a57a70c3b81386c4a079)

**Comment by bqpd** [comment]
oh for sure. But would should it look like?

**Comment by whoburg** [comment]
Here's an example to discuss:

```python
In [1]: from gasmale import GasMALE

In [2]: m = GasMALE()
sol =
In [3]: sol = m.solve("mosek")
Using solver 'mosek'
Solving for 247 variables.
Solving took 0.0332 seconds.

In [4]: sol["sensitivities"]["constants"]["K_{fuse}"]
Out[4]:
{K_{fuse}_Aerodynamics, Climb, Mission, GasMALE: 2.1366974371725446e-05,
 K_{fuse}_Aerodynamics, Cruise, Mission, GasMALE: 0.00076621295169603616,
 K_{fuse}_Aerodynamics, Cruise, Mission, GasMALE: 0.00021400529479052464,
 K_{fuse}_Aerodynamics, Loiter, Mission, GasMALE: 0.051613718217133828,
 K_{fuse}_Aerodynamics, Climb, Mission, GasMALE: 0.010189425316369056}
```

Just print `Climb1`, `Climb2`, instead of `Climb`?

**Comment by bqpd** [comment]
But what if the climb model nums are 4, 5? Should we print 1, 2? 0, 1? 4, 5?

**Comment by whoburg** [comment]
#965 seems to handle the results table portion of this ticket; do we want to do something about solution array as well, or do we feel including all models there is important? (see printout above)

**Comment by bqpd** [comment]
The solution array component was about the accessing of specific modelnumm'd vars, and I think that's okat now that, with performance modeling, it's standard practice to use an attribute chain (`aircraft.wing.fuse`) to increase specificity.

The issue you bring up above, and which I ran into today with @mjburton11, is that latex and str output should start reflecting model numbers by default.

**Comment by whoburg** [comment]
yep!
