### ISSUE TITLE
modelnum counting through different model instances

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#874]
I discovered that if I create multiples of the same model, i.e.: 

```python
M = GasMALE()
M2 = GasMALE(DF70=True)
```

The model count is preserved throughout.  In the example below the `modelnums` should be `[0,0,0]` or `[1,0,0]` because there are only two Climb flight segments.  But because I created two `GasMALE`'s the count kept going... 

```python
In [18]: solM2("V").items()[2][0].descr
Out[18]: 
{'label': 'cruise speed',
 'modelnums': [2, 1, 1],
 'models': ['Climb', 'Mission', 'GasMALE'],
 'name': 'V',
 'shape': (5,),
 'unitrepr': "<Quantity(1.0, 'meter / second')>",
 'units': <Quantity(1.0, 'meter / second')>}
```

**Comment by whoburg** [comment]
@mjburton11, let me or @bqpd if you have further questions about this.

**Comment by mjburton11** [comment]
@bqpd explanation was sufficiently clear.  Thanks.
