### ISSUE TITLE
pip uninstall hangs

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#882]
This has happened on several machines that I have worked with. Pip uninstall gets to `varkey.py` and then hangs for several minutes without making any progress.

**Comment by bqpd** [comment]
Windows machines?

**Comment by pgkirsch** [comment]
Yes

**Comment by bqpd** [comment]
How do you resolve this? Ctrl-C try again?

**Comment by pgkirsch** [comment]
rm the site-packages directory

On Oct 27, 2016, at 09:55, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


How do you resolve this? Ctrl-C try again?

**Comment by bqpd** [comment]
ayayaye

**Comment by pgkirsch** [comment]
#badboy

On Oct 27, 2016, at 10:08, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:


ayayaye

**Comment by bqpd** [comment]
contained in #970
