### ISSUE TITLE
Seg fault on test_call_time on Windows 10

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#883]
Installed gpkit from "git/pip -e" combo but getting seg fault on unit tests:
```python
...
test_sigs_not_allowed_in_cost (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_small_named_signomial (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_initial_guess_sub (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_sp_substitutions (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_trivial_sp2 (gpkit.tests.t_model.TestSP_cvxopt) ... ok
test_unbounded_debugging (gpkit.tests.t_model.TestSP_cvxopt)
Test nearly-dual-feasible problems ... ok
test_call (gpkit.tests.t_solution_array.TestSolutionArray) ... ok
test_call_time (gpkit.tests.t_solution_array.TestSolutionArray) ... Segmentation fault
```

EDIT: On an HP tablet running Windows 10 with 8GB of RAM.

**Comment by pgkirsch** [comment]
My theory is that for some reason a tablet with little RAM can't handle the LDL kktsolver.

**Comment by bqpd** [comment]
hmmmm....

**Comment by pgkirsch** [comment]
Reattempting to debug this. Reproduced on yet another tablet. This time in the standard command prompt (vs. UNIX terminal emulator) it looks like this screenshot. Running basic examples like simple_flight works fine. I want to figure out what is going on in that solution array test that is causing such a problem.
<img width="678" alt="capture" src="https://cloud.githubusercontent.com/assets/8702579/18568191/d4892046-7b50-11e6-89a8-bfb43893927b.PNG">

**Comment by pgkirsch** [comment]
Commenting out the `test_call_time` unit test results in 144 successfully completed unit tests

**Comment by bqpd** [comment]
heh! @whoburg, looks like that silly timing test is actually causing bugs...

**Comment by pgkirsch** [comment]
Changing the line `[x >= y, y >= z1, z1 >= z2, z2 >= z3, z3 >= z4, z4 >= L])` to `[x >= L])` fixes. I'm convinced this is some anti-virus crap, but so far none of my tinkering with Windows defender has yielded any results..

**Comment by pgkirsch** [comment]
More clues. Looking at the Windows Event Viewer in the aftermath of the unit test failure.
<img width="530" alt="capture" src="https://cloud.githubusercontent.com/assets/8702579/18602345/4e200466-7c1d-11e6-9016-fe71f5941033.PNG">

**Comment by bqpd** [comment]
cvxopt bug...

**Comment by pgkirsch** [comment]
Is there a way for me to see what is being passed to cvxopt from gpkit so I can try to make a MWE for them, if it is indeed a cvxopt bug and not an antivirus thing?

**Comment by bqpd** [comment]
Yup! You can add debug statements to `_cvxopt.py`

**Comment by pgkirsch** [comment]
I don't think this is a cvxopt bug. I hacked the following code together to try solving the problem unit test with cvxopt, and it solved fine.

```python
from cvxopt import spmatrix, matrix, log
from cvxopt.cvxprog import gp
import numpy as np

c = np.ones(120,)
g = log(matrix(c))

data = np.dstack([np.ones((100,), dtype=np.int), -np.ones((100,), dtype=np.int)]).flatten()
row =[73, 93, 31, 51, 63, 83, 24, 44, 78, 98, 65, 85, 22, 42, 90, 110, 13, 23,
42, 62, 28, 48, 34, 54, 74, 94, 1, 39, 5, 34, 4, 29, 57, 77, 83, 103, 18, 21,
46, 66, 9, 38, 39, 59, 17, 31, 10, 27, 35, 55, 77, 97, 54, 74, 14, 24, 96, 116,
45, 65, 68, 88, 87, 107, 72, 92, 53, 73, 56, 76, 2, 30, 58, 78, 50, 70, 21, 41,
66, 86, 82, 102, 41, 61, 55, 75, 75, 95, 36, 56, 67, 87, 20, 40, 61, 81, 26,
46, 94, 114, 71, 91, 40, 60, 69, 89, 49, 69, 86, 106, 32, 52, 76, 96, 81, 101,
3, 33, 98, 118, 8, 25, 51, 71, 85, 105, 44, 64, 6, 37, 92, 112, 59, 79, 48, 68,
95, 115, 99, 119, 79, 99, 23, 43, 64, 84, 52, 72, 97, 117, 16, 20, 0, 22, 37,
57, 91, 111, 38, 58, 29, 49, 89, 109, 70, 90, 30, 50, 43, 63, 33, 53, 93, 113,
80, 100, 88, 108, 15, 32, 27, 47, 60, 80, 25, 45, 62, 82, 84, 104, 11, 26, 12,
35, 19, 28, 7, 36, 47, 67]
col1 = np.linspace(0, 99, 100, dtype=np.int)
col = np.dstack([col1, col1]).flatten()
F = spmatrix(data.tolist(), row, col.tolist(), tc='d')

k = np.append([20], np.ones((100,), dtype=np.int))
k = k.tolist()
sol = gp(k, F, g)
```
```python
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  2.9957e+00  1e+02  1e+00  1e+00
 1:  7.6707e+00  2.1176e+00  6e+00  1e-02  1e-02
 2:  3.7565e+00  2.9957e+00  8e-01  2e-16  1e-16
 3:  3.0033e+00  2.9957e+00  8e-03  5e-17  3e-17
 4:  2.9958e+00  2.9957e+00  8e-05  3e-18  9e-18
 5:  2.9957e+00  2.9957e+00  8e-07  1e-17  3e-17
Optimal solution found.
```

I got `A`, `c`, and `k` using print statements so that I could create a ticket on the cvxopt page which is why this looks so gross.

**Comment by pgkirsch** [comment]
Using `pdb` for debugging.

![image](https://cloud.githubusercontent.com/assets/8702579/18642829/13123b78-7e57-11e6-891a-5fd394fb744b.png)

**Comment by pgkirsch** [comment]
Delving deeper.... (sorry for the spam)

![image](https://cloud.githubusercontent.com/assets/8702579/18643153/a3713f1a-7e58-11e6-883e-0c9fd8701c04.png)

**Comment by pgkirsch** [comment]
Tested on a different machine also running Windows 10. A few observations:

1. The offending unit test runs fine with the pip installed version of gpkit but not with the git cloned version of gpkit
2. This doesn't appear to be a "tablet" issue as I thought it might be, given that I am testing it on a relatively powerful laptop now too

**Comment by pgkirsch** [comment]
Correction on the cvxopt test code I wrote above. I forgot to pass the kktsolver kwarg. When I remembered to do this I was able to replicate the issue. Gonna open a cvxopt ticket now.

**Comment by pgkirsch** [comment]
Closing this because it seems to be much lower-level than GPkit

**Comment by whoburg** [comment]
Thanks @pgkirsch for the really careful debugging and reporting. Just curious: is this still an issue for you and/or slowing you down at all?
