### ISSUE TITLE
update md_template now that latex table printing bug fixed

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#890]
latex table printing doesn't seem to be working in [gpkit-models/md_template](https://github.com/hoburg/gpkit-models/pull/70/files/a1da5de0e4ebb9233825c32ad6e3981d3c76d674..a1b23a27a1a6ac048aa9f77d27d0409eff8fb170#r78415403)

**Comment by whoburg** [comment]
now that https://github.com/hoburg/gpkit/pull/900 is merged, the md_template should be updated to remove the part about not working.

@mjburton11, you up for this one?

**Comment by mjburton11** [comment]
Sure, I got it.

**Comment by bqpd** [comment]
@mjburton11, could you either close this soon or make it a gpkit-models issue?

**Comment by mjburton11** [comment]
Solution table still not printing.  Moved to issue 93 in gpkit-models.

**Comment by bqpd** [comment]
Dang, my bad, what I did really doesn't fix this issue. reopening. sorry @mjburton11! reopening.

**Comment by mjburton11** [comment]
No worries!

**Comment by whoburg** [comment]
@bqpd said this wasn't fixed and that he was reopening, but the issue didn't get reopened. Reopening now; feel free to close if actually fixed (in which case we should merge https://github.com/hoburg/gpkit-models/issues/93?)

**Comment by bqpd** [comment]
Covered by #628
