### ISSUE TITLE
Multiple chartjs objects linked to a single control panel instance

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#895]
Building on #523, it would be nice if one could link multiple `BarChart` objects to a single `controlpanel` instance. Unless I'm mistaken, I don't believe that's currently possible.

**Comment by whoburg** [comment]
This seems to generate the two barcharts (perhaps not positioned where you want them though?)

separately, the bar charts disappear for me when I move a slider, seems like something broke?

```python
from gpkit import Model, Variable
from gpkit.interactive.chartjs import BarChart

x = Variable("x", "-", "the variable called x")
y = Variable("y", "-", "the variable called y")
x_min = Variable("x_{min}", 2, "-", "min x val")
y_min = Variable("y_{min}", 2, "-", "min y val")

m = Model(x + y,
          [x >= x_min,
           y >= y_min])
sol = m.solve(verbosity=0)
bc1 = BarChart(["x", "y"])
bc2 = BarChart(["x", "y"])
def bc_update(sol):
    bc1.update(sol)
    bc2.update(sol)
m.controlpanel(fn_of_sol=bc_update)
```

**Comment by pgkirsch** [comment]
Ah clever, thanks! For some reason sliders don't even appear for me though...
Also shouldn't that last line read `m.controlpanel(fn_of_sol=bc_update(sol))`?

**Comment by bqpd** [comment]
C-c-c-callback functions

**Comment by pgkirsch** [comment]
aka voodoo

For some reason I don't need the `sol=m.solve()` line for this to work.

**Comment by bqpd** [comment]
Yup, interact solves it for you.

**Comment by pgkirsch** [comment]
Dope.

By the way, I found a (perhaps unsatisfying) fix to the disappearing chart issue above. Separating the last 4 lines into a separate cell of the ipython notebook works just fine.
![capture1](https://cloud.githubusercontent.com/assets/8702579/18523961/4c4f6a18-7a6b-11e6-9430-337b52700185.PNG)

From my point of view this issue can be closed - although it might be super sweet if it made it into the docs at some point.

**Comment by bqpd** [comment]
Oh, yeah, that's always been necessary. It's mentioned in the original PR, I think.

**Comment by pgkirsch** [comment]
Note to future self:

To get kktsolver="ldl" for bar charts/control panel do the following:

```python
kwargdict = {'kktsolver': 'ldl'}
m.controlpanel(fn_of_sol=bc_update, **kwargdict)
```

**Comment by bqpd** [comment]
shouldn't

m.controlpanel(fn_of_sol=bc_update, kktsolver="ldl")

work too?

**Comment by pgkirsch** [comment]
Note to future self:

Do what Ned said.
