### ISSUE TITLE
linking within nested models

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#899]
@bqpd: this is what we were talking about yesterday. 

I have a `Mission` model which creates 5 `FlightSegment` models.  Each `FlightSegment` has an `Engine` model.  The engine weight should be the same across the whole mission.  When I link it however, the weight shows up as `W_Mission, GasMALE`, instead of `W_Engine, Mission, GasMALE`.

**Comment by bqpd** [comment]
As we no longer recommend linking, I'll close this issue (since linking was working as intended, see the reference issue above).

**Comment by whoburg** [comment]
This says to see #896 and that says to see this...

"Did you mean recursion?"

**Comment by bqpd** [comment]
Haha, bad reference in this one.

**Comment by bqpd** [comment]
This is part of a general discussion on how linking should work between submodels, which are no longer relevant.
