### ISSUE TITLE
Sub into a vector variable

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#902]
I keep running into places where I want to do this

``` python
x = VectorVariable(1, 'x')
subs = {'x': 1}
m = Model(x, [x >= .5], subs)
```

is there a reason we don't allow it? I've also wanted to do this for vector variables of length > 1 (expecting the entire vector variable to assume the substituted value).

**Comment by bqpd** [comment]
`{'x': [1]}` should work, right?

**Comment by mayork** [comment]
don't thinks so...just ran this and got the following error

```python
x = VectorVariable(1, 'x')

subs = {'x': [1]}

m = Model(x, [x >= .5], subs)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-bd19a0f8ce23> in <module>()
----> 1 m = Model(x, [x >= .5], subs)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/model.pyc in __init__(self, cost, constraints, substitutions, name)
     49         cost = cost if cost else Monomial(1)
     50         constraints = constraints if constraints else []
---> 51         CostedConstraintSet.__init__(self, cost, constraints, substitutions)
     52         if self.__class__.__name__ != "Model" and not name:
     53             name = self.__class__.__name__

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gpkit/constraints/costed.pyc in __init__(self, cost, constraints, substitutions)
     15     def __init__(self, cost, constraints, substitutions=None):
     16         self.cost = cost
---> 17         subs = dict(self.cost.values)
     18         if substitutions:
     19             subs.update(substitutions)

AttributeError: 'NomialArray' object has no attribute 'values'
```

**Comment by bqpd** [comment]
As the error says, your cost is a vector. (admittedly a vector of length 1,
but we don't check for that).

**Comment by mayork** [comment]
shoot didn't even read the error, just assumed it was the sub. That's my bad. The vector of length 1 seems like something potentially worth checking though?

**Comment by bqpd** [comment]
Too special-case for my taste...we could potentially make it a
zero-dimensional array.

**Comment by mayork** [comment]
fair enough, in real models its likely not a real use case

**Comment by bqpd** [comment]
Decided in #930 not to allow scalar substitution for a vector, but open to reconsideration on that issue.

**Comment by whoburg** [comment]
but just want to confirm, we do support subbing a vector for a vector? and is that unit tested?

**Comment by whoburg** [comment]
agree with do special-casing the 1-element cost -- users should make `c.sum()` their cost if c is a 1-element vector.

**Comment by bqpd** [comment]
We've supported vector/vector for years! It's tested. :)
