### ISSUE TITLE
substitute into variables not in a constraint

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#904]
I was wondering if there can be a keyword which disables the new feature where you can't substitute into a variable not in any constraints. I understand why it's no longer allowed to substitute a value for a variable not in a constraint, but its kind of a pain when developing a model and testing different constraints. I keep running into the case where changing one constraint leads to editing code in multiple places (i.e. change a constraint removing a variable --> comment out the substitution into said variable).

thoughts?

**Comment by bqpd** [comment]
@whoburg, @pgkirsch what do you think?

**Comment by pgkirsch** [comment]
Ah yeah that's fair, should have seen this coming... Is a kwarg the right way to handle it?

**Comment by bqpd** [comment]
or a `updateskipfailures` method, with a less obnoxious name

**Comment by whoburg** [comment]
I think a keyword would be fine, but for gpkit simplicity, what about just letting users do the filtering?

something like
```python
# define subs dict
validsubs = {k: subs[k] for k in subs if k in model.varkeys}
```

**Comment by bqpd** [comment]
Yeah that's way better! @mayork, @pgkirsch, that seem good to you?

**Comment by mayork** [comment]
yeah that's a better idea

**Comment by pgkirsch** [comment]
Agree!
