### ISSUE TITLE
macOS Sierra and numpy 1.8.0rc1

### ISSUE THREAD

**Issue by galbramc** [hoburg/gpkit#907]
Well, looks like macOS Sierra comes with numpy 1.8.0rc1, and gpkit isn't happy with that. See https://acdl.mit.edu/csi/job/gpkit_PullRequest_Unit/buildnode=macys_Sierra,optimizer=cvxopt/1595/console.

@bqpd and @whoburg , not sure what you want to do about this. You could tell all your users they have to upgrade to a newer version of numpy. Either by upgrading their system numpy or using virtualenv's to install a newer version. Ideally you can fix gpkit so it works with 1.8.0rc1.

**Comment by whoburg** [comment]
discussed this with @galbramc.

There is historical precedent: OSX ElCap came with numpy 1.7 which we flat out refused to support by requiring `install_requires=["numpy >= 1.8", "pint", "scipy"],` in setup.py.

Now Sierra comes with 1.8.0rc1, which satisfies our `numpy >= 1.8` but fails our unit tests.

So, we should:

1. See if the failures are easy to fix (see link above to see the failures)
2a. If easy, fix it and keep `numpy >= 1.8`
2b. If not easy to fix change requirement to `numpy >= 1.8.2`.

**Comment by whoburg** [comment]
may also want to update install docs to mention this issue (new Sierra users may need to upgrade numpy)

**Comment by bqpd** [comment]
These don't seem like particularly easy failures to fix; NomialArrays don't seem to be inheriting np.array's operator overloading for scalar quantities such as `numpy.float64`

**Comment by galbramc** [comment]
I just tried out bumpy 1.8.1, and that worked. So I would suggest that you change the setup.py to specify `numpy >= 1.8.1`. I'll update the testing to use that version as part of the dependency tests instead of 1.8.2. I'll also just have the unit tests use the latest version of numpy.
