### ISSUE TITLE
better way to handle subinplace with variables in different models

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#914]
I think we need an easier way to do something like this

```python
        for i in range(Nclimb):
            for atmvar, climbvar in [("\\rho", "\\rhoClimb"), ("T_{atm}", "TClimb"), ("h", "hftClimb")]:
                descr = dict(atmvec[i][atmvar].key.descr)
                model = climb if atmvar != "h" else cmc
                climbkey = model[climbvar][i]
                climbdescr = dict(climbkey.key.descr)
                # new variable is same as atmvar but with extended models, modelnums
                descr["models"].extend(climbdescr["models"])
                descr["modelnums"].extend(climbdescr["modelnums"])
                subs[climbkey] = Variable(**descr)
```

**Comment by mayork** [comment]
@bqpd that linking does not appear to be working...running the file with the code form above I get this table output 
<img width="1125" alt="screen shot 2016-09-27 at 9 51 44 pm" src="https://cloud.githubusercontent.com/assets/6796415/18898035/e37bcf9e-84fc-11e6-8494-abbd9d9cd49c.png">
note that both `"T_{atm}"` and `"T_{climb}"' are still alive...

the code is at commit e39690cf2eb8f5195b73bb186b4e941e894c894d on gpkit-models

**Comment by mayork** [comment]
so I want linking to work like I have it set up in this commit https://github.com/hoburg/gpkit-models/pull/89/commits/703af956dc127f2e706d806853318a6de625d409...this method of linking works on master until this commit https://github.com/hoburg/gpkit/commit/ba9c35fd06c2c0649bbf0b827c787f647d794508 so I think that somehow fast subinplace messed up linking

@mjburton11 just in case this is relevant to the 82 plane

**Comment by mayork** [comment]
@bqpd is there a quick local fix for this?

**Comment by bqpd** [comment]
Going back to ba9c35f (or the feasmodtest branch, if that works?)

**Comment by mayork** [comment]
feasmodtest works!...I tried checking out 
https://github.com/hoburg/gpkit/commit/ba9c35fd06c2c0649bbf0b827c787f647d794508
yesterday but the engine model wouldn't run on it

**Comment by mayork** [comment]
nope just kidding, linking doesn't work on feasmodtest either...

**Comment by bqpd** [comment]
Did this linking...ever work?

**Comment by mayork** [comment]
yeah up to commit ba9c35f on master...the problem is that after the fast subs merge I had to modify the engine model to run it on master, and I want to link the flight profile with the same engine model I'm using for validation

**Comment by bqpd** [comment]
@mayork what's the status of this?

**Comment by mayork** [comment]
aborted, I thought the game plan was to use vectorize and performance models now

**Comment by bqpd** [comment]
Sounds good to me. I'll close this, then.
