### ISSUE TITLE
Variable with different units in different linked models not flagged

### ISSUE THREAD

**Issue by pgkirsch** [hoburg/gpkit#924]
This could fall into the class of issue that can be dismissed as user error.

I have the same fixed variable declared in two separate sub-models, and I have the substitution only 
declared in one of these models, but I accidentally use different units for the two variable declarations. 

``` python
# model 1
x = Variable('x', 'm')
....
substitutions = {...
                          'x': 5, # I really meant for this to be 5 in
                          ...
                          }
# model 2
x = Variable('x', 'in')
```

This can easily slip by unnoticed. It might be nice if GPkit checked consistency.

This issue also gently nudges another can of worms: that it seems bad/risky/less readable to have the substitutions dictionary not have units associated with it. 

I was heavily in favour of adopting the following model format as a standard back in spring of this year - I don't even know if other people follow the same convention - but I'm wondering if it should be discussed again.

``` python

a = Variable('a', 'm')
b = Variable('b', 's')
....

objective = a

constraints = [
                       a >= b,
                       ....
                      ]

substitutions = {
                          'b': 7, # the units are so far away
                          ...
                         }

m = Model(objective, constraints, substitutions}
sol = m.solve()
```

I think @whoburg was also a big fan of this structure. I like it because it allows you to see very clearly which variables are fixed and also because it takes a very minor change to make a variable free.

Anyway, interested to hear other people's thoughts on both the issue and the ensuing brain dump.

**Comment by bqpd** [comment]
You could specify your substitution as a Quantity!

From the top level, we're trying to prevent variable duplication as much as possible, replacing linking with smart sequential creation and, when absolutely necessary, subinplace, both of which don't have this issue.

As for _requiring_ Quantity substitutions, I'm still shying away for backwards compatibility reasons, but we could force it in 0.5?

**Comment by whoburg** [comment]
I like both the issue report and the suggested resolution.

At one point I had advocated for requiring substitutions to have units (or be dimensionless), but we dropped that for backwards compatibility and perceived ease of use. That said, I still advocate always using substitutions with units as a good modeling practice.

**Comment by bqpd** [comment]
Should we force quantity substitutions in 0.6?

**Comment by bqpd** [comment]
Covered by issue #583
