### ISSUE TITLE
Model Inheritance Best Practices

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#928]
I am converting some of my models to be in line with `performance_modeling_test.py`. I currently have an `AircraftPerformance` model and a `ClimbPerformance` model. The `ClimbPerformance` model inherits from `Aircraft Performance`. I want `ClimbPerformance` to have all the constraints that are in `AircraftPerformance` in addition to its own constraints.

I am not sure how to handle the initialization of the different classes. Thoughts?

**Comment by bqpd** [comment]
@mayork, I think we talked about this, but I don't remember exactly the design pattern you ended up following...could you describe your solution here briefly and then close the issue?

**Comment by mayork** [comment]
What I ended up doing was having both `AircraftPerformance` and `ClimbPerformance` inherit from `Model` and then each instance of `ClimbPerformance` creates its own `AircraftPerformance` model
