### ISSUE TITLE
Erroneously reporting Dual Infeasible

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#942]
A number of times I've seen Mosek return primal infeasible only for GPkit to tell me the model is Dual Infeasible...the inverse has happened as well. I'm guessing this is an error. If it isn't, it is confusing and I think could warrant some better explanation in the error print out.

[Screen Shot 2016-11-08 at 9.25.41 AM.PDF](https://github.com/hoburg/gpkit/files/578382/Screen.Shot.2016-11-08.at.9.25.41.AM.PDF)

**Comment by bqpd** [comment]
Why is your screenshot a pdf?

**Comment by bqpd** [comment]
Also, this is expected :) MOSEK is solving the dual as the primal (and vice versa), so GPkit flips the error messages.

**Comment by bqpd** [comment]
We could reach in an edit the raw MOSEK output before printing it...but I don't think we should?

**Comment by mayork** [comment]
ah okay didn't realize that!

**Comment by bqpd** [comment]
The More You Know :rainbow:

**Comment by whoburg** [comment]
yeah I agree that we shouldn't edit at that level. Note that right below where mosek reports "PRIMAL_INFEASIBLE_CER", it also reports,

```
* End solution on dual form. *
Transforming to primal solution.
```
(as expected)

**Comment by whoburg** [comment]
Here's the relevant section of the MOSEK docs in case anyone is interested: http://docs.mosek.com/8.0/capi/advanced-expopt.html#choosing-primal-or-dual-form
