### ISSUE TITLE
Substitutions issue in newvectorized

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#950]
This is in aircraft_mission_class of gpkit models.  The directory is 
~\gpkit-models\gpkitmodels\Commercial Sizing\
I do:
```python
run Wing_simple_performance.py
```
The substitutions have gone out of whack since the switch from feassweep to newvectorized. For the vectorized variables, it seems there are many variables that have arbitrary '1' substituted for their members....

eg. The sutherland coefficient is substituted in line 298. 
```python
C_1 = Variable('C_1', 1.458E-6, "kg/(m*s*K^0.5)",  'Sutherland coefficient')
```
which is part of the Atmosphere model. 

Then when I look at the substitutions of the model:
<img width="909" alt="debug" src="https://cloud.githubusercontent.com/assets/15684191/20458529/c72080c2-ae75-11e6-8946-645a7ac421a2.PNG">
Real odd...

**Comment by 1ozturkbe** [comment]
Also, note that there are arbitrary '1' substitutions for other variables as well. I will try to ascertain why this is happening to certain variables but not others.

**Comment by 1ozturkbe** [comment]
Ha, figured it out. It happens to substituted variables in Signomial Equalities.

**Comment by mayork** [comment]
this is pretty weird - is this happening to the signomial equalities in the fuselage code?

**Comment by 1ozturkbe** [comment]
No, good point. CFP_Fuselage_Performance runs fine, but that is only because it doesn't have the wing model in it. It seems just to be the wing, and only the atmosphere model. Perhaps it is model specific.

**Comment by mayork** [comment]
same thing is happening in the VT model.

@bqpd `SignomialEqualityConstraint` doesn't appear to be on `newvectorize` (or at least `from gpkit.constraints.sigeq import SignomialEqualityConstraint` won't work). I suspect that this is the problem. thoughts?

**Comment by 1ozturkbe** [comment]
I actually noted that, and switched all mentioned of SignomialEqualityConstraint in all of our codes to SignomialEquality. I think that was intentional on ned's part?

**Comment by mayork** [comment]
I'm not sure. I remember he made `SignomialEqualityConstraint` to address an issue I was having inside vectorize, hence why I assumed not using could cause the error

**Comment by 1ozturkbe** [comment]
K, I don't know the history of that, so that might very well be it. I also noticed that the sigeqs within the fuselage model were never vectorized, so would make sense.

**Comment by mayork** [comment]
ah that makes sense then

**Comment by bqpd** [comment]
The new signomialequality is vectorizable, berk is right. Just about to
come online...

**Comment by bqpd** [comment]
I don't have mosek installed on this computer, but capitalizing `Vectorize` and using `from gpkit import SignomialEquality` it seems to be running? Not solving with cvxopt, though.

**Comment by bqpd** [comment]
My guess is that it's something different about the way `x0`s are passed between SP solves in these, but I can't debug on this computer :-/ will fix this computer or see you Monday to fix this.

**Comment by bqpd** [comment]
also @1ozturkbe, can you check this with older commits on the `newvectorized` branch to see when the difference occurs?

**Comment by 1ozturkbe** [comment]
Well, it doesnt work until commit bbd626, which is the second-to-last one... Before that, running 
```python
Wing_simple_performance.py
```
it gives:
```python 
TypeError: object of type 'int' has no len()
```
which is due to some issue vectorizing SignomialEqualities.

**Comment by whoburg** [comment]
we need a MWE for this issue so that we can write a unit test - any ideas?

**Comment by bqpd** [comment]
This was caused by forgetting to apply substitutions to fill x0s, I think, and the tests currently don't include any SPs with manual substitutions.

I think the best test would be just to check that the correct monomial approximations are made by an SP with various different x0/sp_init/etc

**Comment by whoburg** [comment]
sounds reasonable, @1ozturkbe are you able to help by coming up with a simple unit test for this? I think we just need a simplified SP involving a couple of your constrains, plus the manual substitution.

**Comment by 1ozturkbe** [comment]
Sure. Never written a test before, so should be informative. I will need a bit of getting-up-to-speed on where we keep and maintain the tests; after that it shouldn't take long.

**Comment by bqpd** [comment]
It's basically just a function testing out what should work. Right now an SP solve accepts parameters from var.sp_init and m.substitutions, so the basic test would just show that both methods of giving initial guesses get the same result?

**Comment by 1ozturkbe** [comment]
@bqpd I had sent you a small test by email. Will that do?

**Comment by bqpd** [comment]
Yes! See #984

**Comment by 1ozturkbe** [comment]
Merci! Now I know what happens when a test is added :)
