### ISSUE TITLE
Windows specific: Anaconda Mosek package supported?

### ISSUE THREAD

**Issue by norheim** [hoburg/gpkit#962]
Instead of going through the long "painful"(ok, it wasnt that bad) process of installing mosek and mingw, is there any support for [Anaconda's Mosek package](https://anaconda.org/MOSEK/mosek)?
Would just be a one liner:
 `conda install -c mosek mosek=8.0.43` 
and the licence download I guess.
Might make the installation more streamlined!

**Comment by bqpd** [comment]
This looks great! @galbramc, are you already using anaconda on the VMs to install cvxopt for windows? If so, let's try installing MOSEK that way as well.

**Comment by galbramc** [comment]
So you would not compile expopt.so anymore? If we don't install mosek and only do the conda step I don't think you have any source to compile.

**Comment by bqpd** [comment]
I was thinking it would save the user the download step, but that might be
silly...

**Comment by galbramc** [comment]
Unless you remove your custom compile of expopt.so, I don't think this will do anything for you. I don't know why you are compiling that in the first place, so I don't know the difference between that and the conda mosek install.

**Comment by bqpd** [comment]
We're removing some debug statements in mosek's default expopt.so :-/

**Comment by galbramc** [comment]
Ok. You should probably close this then and look at the errors we are getting now that I installed mosek 8 on windows.

**Comment by norheim** [comment]
Hmmm, I got a little lost in that stream of thought, so back to my initial question, is it possible to just do the conda install instead of installing mosek and mingw? yes or no?

**Comment by bqpd** [comment]
Nope, because we need to patch some of the MOSEK code to avoid spamming the console.

**Comment by bqpd** [comment]
It could potentially save you from having to download MOSEK, but that's it.
