### ISSUE TITLE
Mosek 8 on Windows

### ISSUE THREAD

**Issue by galbramc** [hoburg/gpkit#967]
Looks like things don't work so well with mosek 8 on windows:

https://acdl.mit.edu/csi/job/gpkit_PullRequest_Unit/buildnode=windows10x64,optimizer=mosek/1740/console

**Comment by bqpd** [comment]
Yup, they improved their presolve. Good news, in general.

**Comment by galbramc** [comment]
What about all those "Number of Hessian non-zeros" messages?

**Comment by bqpd** [comment]
The indentation of that line in their code has changed, so I'll rewrite the patching function in `build.py` to ignore leading whitespace.

**Comment by bqpd** [comment]
Closed by #977
