### ISSUE TITLE
Default constraint tightness threshold for Tight

### ISSUE THREAD

**Issue by 1ozturkbe** [hoburg/gpkit#968]
This has come to my attention as the d8 model grows bigger and bigger. Tight is often implemented in models to see whether solutions makes sense (eg. for aircraft design, weight and drag constraints should always be tight since we are minimizing fuel burn or takeoff weight). 

But sometimes, a large number of constraints are shown to be not 'tight', although sometimes they have errors past the default threshold only due to numerical precision. The following example is from the solution of hoburg/d8/CFP_Fuselage_Performance.py, commit 3ab890. 

![image](https://cloud.githubusercontent.com/assets/15684191/20779336/ef4516d8-b741-11e6-97d7-7f663515a392.png)

Although all constraints are tight, the numerical errors in the SP solution add up to show that the constraints are past the error threshold. So, instead of having Tight work to e-6 (0.0001%), we should perhaps reduce the default error to something on the order of 0.1-0.01%.

**Comment by 1ozturkbe** [comment]
@bqpd and I talked about this earlier today as well.

**Comment by mayork** [comment]
i concur...setting a lower tolerance for every constraint is not pracitcal

**Comment by bqpd** [comment]
Alright, so 0.1% or 0.01%? Thumbs up this comment to vote for 0.1%, fireworks for 0.01%.

**Comment by 1ozturkbe** [comment]
@bqpd we also discussed tightness this morning with Woody. It would also make sense to perhaps have the rel_tol of Tight be an attribute of a Model

So calling in the class something on the lines of
```python
Tight.tol = 10**-2
```
might make sense at the beginning of a Model that you want to have low tolerances.

**Comment by bqpd** [comment]
but it would make me very sad :(

**Comment by 1ozturkbe** [comment]
ok then, let's change the tolerance and perhaps address in the future.
