### ISSUE TITLE
update cvxopt installation instructions

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#979]
cvxopt no longer includes SuiteSparse. @galbramc any suggestions on how we should update our install instructions? See https://github.com/cvxopt/cvxopt/issues/80 for some good possible suggestions.

**Comment by galbramc** [comment]
Nothing new is needed for windows or OSX. They come as precompiled binaries. Linux is a different story.

For Ubuntu 16.04:

```
sudo apt-get install suitesparse-dev
pip install cvxopt
```

For Ubuntu 14.04:

```
sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687 
sudo apt-get update 
sudo apt-get install suitesparse-dev
CVXOPT_SUITESPARSE_INC_DIR=/usr/include/suitesparse pip install cvxopt
```

**Comment by bqpd** [comment]
Added the 16.04 install instructions in #982; should we also include 14.04, or link to this issue / another page?

**Comment by whoburg** [comment]
that looks good; I'm ok with including only 16.04 instructions (with an eye toward the future; we'd probably remove the 14.04 instructions eventually anyway)
