### ISSUE TITLE
Invalid Array Struct

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#997]
@bqpd just got this error after pulling master. Any idea what might be going on here? Im pretty lost.

I'm running `gas.py` on `gas_solar_trade`.  You need to have `1682` branch checked out on `gpkit-models`.

```python
/Users/mjburton11/MIT/GPKIT/gpkit/gpkit/keydict.pyc in __contains__(self, key)
     88             if idx:
     89                 try:
---> 90                     return not np.isnan(dict.__getitem__(self, key)[idx])
     91                 except TypeError:
     92                     raise TypeError("%s has an idx, but its value in this"

ValueError: invalid __array_struct__
```

**Comment by mjburton11** [comment]
Just kidding, I had one model that hadn't been changed to `setup` yet, and it was throwing the error.  I wasn't getting any warnings from it because I didn't declare any variables in it; it was just building other models.

**Comment by bqpd** [comment]
Ack, we still would have caught that before the recent backwards compatibility patch. Sorry for the confusion!

**Comment by mjburton11** [comment]
That's ok.  It didn't take me too long to track down the problem.
