### ISSUE TITLE
new sweeping syntax?

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#999]
I'd like to remove the `("sweep", [...])` syntax. How about the following?

```python
m = BigModel()
m_sweepV = m.sweep("V", [30, 40, 50])
# m_sweepV contains m, so any modifications to m will show up in m_sweepV
m.solve()  # does not sweep
m_sweepV.solve()  # sweeps
```

**Comment by 1ozturkbe** [comment]
I prefer the explicit substitution scheme for sweeps. Although it is more verbose to say
```python
m.substitutions.update({"V" : ('sweep', [30, 40, 50]) } )
```
it is being 100% clear about what is going on under the hood (which is a subs.update, leading to a set of GPs). I personally don't  feel this adds very much, but perhaps I'm wrong.

**Comment by bqpd** [comment]
This would be part of a change to not use substitutions to hold sweeps any more...

**Comment by mayork** [comment]
i see the benefit of the new style. will you totally remove support for the old way of doing sweeps?

**Comment by bqpd** [comment]
Not for a couple of point versions, probably.

**Comment by 1ozturkbe** [comment]
Hmm, no substitutions for sweeps... I guess I don't feel that strongly about it either way :P But related to that, how does one know that a model is a sweep if it doesn't show up in the substitutions?

**Comment by bqpd** [comment]
We could make a `model.sweeps` attribute, but you're right that it's nice
to only have to check one place...

**Comment by bqpd** [comment]
My conclusion is that we should not remove `"sweep", ` substitutions, and I don't think we should add a second way to do the same thing, like the syntax in my first post. I think I can implement most of the internal cleanups I wanted to without any external changes.

**Comment by 1ozturkbe** [comment]
Sorry about being a buzzkill :P

**Comment by bqpd** [comment]
Haha, naw that was perfect!
